export const translator = {
    español: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        logIn: 'Iniciar sesión',
        createAnAccount: 'Crear una cuenta',
        slogan: 'Tus pensamientos, tu espacio, tu tranquilidad.',
        landingOwlAlt: `Búho de Journée usando su computadora portátil.`,
        journeesHomepage: `Página de inicio de Journée`,
        language: 'Idioma',
    },
    english: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        logIn: 'Log In',
        createAnAccount: 'Create an account',
        slogan: 'Your Thoughts, Your Space, Your Tranquility.',
        landingOwlAlt: `Journée's Owl Using Its Laptop.`,
        journeesHomepage: `Journée's Homepage`,
        language: 'Language',
    },
    français: {
        comingSoon: 'Prochainement',
        copyright: 'Droits d\'auteur ©',
        allRightsReserved: 'Tous droits réservés.',
        logIn: 'Se connecter',
        createAnAccount: 'Créer un compte',
        slogan: 'Vos pensées, votre espace, votre tranquillité.',
        landingOwlAlt: `Chouette de Journée utilisant son ordinateur portable.`,
        journeesHomepage: `Page d'accueil de Journée`,
        language: 'Langue',
    },
    deutsch: {
        comingSoon: 'Demnächst',
        copyright: 'Urheberrecht ©',
        allRightsReserved: 'Alle Rechte vorbehalten.',
        logIn: 'Anmelden',
        createAnAccount: 'Konto erstellen',
        slogan: 'Deine Gedanken, dein Raum, deine Ruhe.',
        landingOwlAlt: `Journée's Eule benutzt seinen Laptop.`,
        journeesHomepage: `Journée's Startseite`,
        language: 'Sprache',
    },
    italiano: {
        comingSoon: 'Prossimamente',
        copyright: 'Copyright ©',
        allRightsReserved: 'Tutti i diritti riservati.',
        logIn: 'Accedi',
        createAnAccount: 'Crea un account',
        slogan: 'I tuoi pensieri, il tuo spazio, la tua tranquillità.',
        landingOwlAlt: `Gufo di Journée che usa il suo laptop.`,
        journeesHomepage: `Homepage di Journée`,
        language: 'Lingua',
    },
    Русский: {
        comingSoon: 'Скоро',
        copyright: 'Авторское право ©',
        allRightsReserved: 'Все права защищены.',
        logIn: 'Войти',
        createAnAccount: 'Создать аккаунт',
        slogan: 'Ваши мысли, ваше пространство, ваша спокойствие.',
        landingOwlAlt: `Сова Джурне использует свой ноутбук.`,
        journeesHomepage: `Домашняя страница Journée`,
        language: 'Язык',
    },
};