export const translator = {
    español: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        logIn: 'Iniciar sesión',
        slogan: 'Tus pensamientos, tu espacio, tu tranquilidad.',
        landingOwlAlt: `Búho de Journée usando su computadora portátil.`,
        journeesHomepage: `Página de inicio de Journée`,
        language: 'Idioma',
        logInToJournee: 'Inicia sesión en Journée',
        beginYourJournee: 'Comienza tu viaje',
        email: 'Correo electrónico',
        password: 'Contraseña',
        confirmPassword: 'Confirmar contraseña',
        forgotPassword: '¿Olvidaste tu contraseña?',
        logInWithGoogle: 'Iniciar sesión con Google',
        logInWithApple: 'Iniciar sesión con Apple',
        newToJournee: '¿Nuevo en Journée?',
        createAnAccount: 'Crea una cuenta',
        alreadyHaveAnAccount: '¿Ya tienes una cuenta?',
        logYouIn: 'Inicia sesión',
    },
    english: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        logIn: 'Log In',
        slogan: 'Your Thoughts, Your Space, Your Tranquility.',
        landingOwlAlt: `Journée's Owl Using Its Laptop.`,
        journeesHomepage: `Journée's Homepage`,
        language: 'Language',
        logInToJournee: 'Log In To Journée',
        beginYourJournee: 'Begin Your Journée',
        email: 'Email',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        forgotPassword: 'Forgot your password?',
        logInWithGoogle: 'Log in with Google',
        logInWithApple: 'Log in with Apple',
        newToJournee: 'New to Journée?',
        createAnAccount: 'Create an account',
        alreadyHaveAnAccount: 'Already have an account?',
        logYouIn: 'Log in',
    },
    français: {
        comingSoon: 'Prochainement',
        copyright: 'Droits d\'auteur ©',
        allRightsReserved: 'Tous droits réservés.',
        logIn: 'Se connecter',
        slogan: 'Vos pensées, votre espace, votre tranquillité.',
        landingOwlAlt: `Chouette de Journée utilisant son ordinateur portable.`,
        journeesHomepage: `Page d'accueil de Journée`,
        language: 'Langue',
        logInToJournee: 'Se connecter à Journée',
        beginYourJournee: 'Commencez votre voyage',
        email: 'E-mail',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        forgotPassword: 'Mot de passe oublié?',
        logInWithGoogle: 'Se connecter avec Google',
        logInWithApple: 'Se connecter avec Apple',
        newToJournee: 'Nouveau sur Journée?',
        createAnAccount: 'Créez un compte',
        alreadyHaveAnAccount: 'Vous avez déjà un compte ?',
        logYouIn: 'Connectez-vous',
    },
    deutsch: {
        comingSoon: 'Demnächst',
        copyright: 'Urheberrecht ©',
        allRightsReserved: 'Alle Rechte vorbehalten.',
        logIn: 'Anmelden',
        slogan: 'Deine Gedanken, dein Raum, deine Ruhe.',
        landingOwlAlt: `Journée's Eule benutzt seinen Laptop.`,
        journeesHomepage: `Journée's Startseite`,
        language: 'Sprache',
        logInToJournee: 'Bei Journée anmelden',
        beginYourJournee: 'Beginnen Sie Ihre Reise',
        email: 'E-Mail',
        password: 'Passwort',
        confirmPassword: 'Passwort bestätigen',
        forgotPassword: 'Passwort vergessen?',
        logInWithGoogle: 'Mit Google anmelden',
        logInWithApple: 'Mit Apple anmelden',
        newToJournee: 'Neu bei Journée?',
        createAnAccount: 'Erstelle ein Konto',
        alreadyHaveAnAccount: 'Haben Sie bereits ein Konto?',
        logYouIn: 'Melden Sie sich an',
    },
    italiano: {
        comingSoon: 'Prossimamente',
        copyright: 'Copyright ©',
        allRightsReserved: 'Tutti i diritti riservati.',
        logIn: 'Accedi',
        slogan: 'I tuoi pensieri, il tuo spazio, la tua tranquillità.',
        landingOwlAlt: `Gufo di Journée che usa il suo laptop.`,
        journeesHomepage: `Homepage di Journée`,
        language: 'Lingua',
        logInToJournee: 'Accedi a Journée',
        beginYourJournee: 'Inizia il tuo viaggio',
        email: 'E-mail',
        password: 'Password',
        confirmPassword: 'Conferma password',
        forgotPassword: 'Hai dimenticato la password?',
        logInWithGoogle: 'Accedi con Google',
        logInWithApple: 'Accedi con Apple',
        newToJournee: 'Nuovo su Journée?',
        createAnAccount: 'Crea un account',
        alreadyHaveAnAccount: 'Hai già un account?',
        logYouIn: 'Accedi',
    },
    Русский: {
        comingSoon: 'Скоро',
        copyright: 'Авторское право ©',
        allRightsReserved: 'Все права защищены.',
        logIn: 'Войти',
        slogan: 'Ваши мысли, ваше пространство, ваша спокойствие.',
        landingOwlAlt: `Сова Джурне использует свой ноутбук.`,
        journeesHomepage: `Домашняя страница Journée`,
        language: 'Язык',
        logInToJournee: 'Войти в Journée',
        beginYourJournee: 'Начни свое путешествие',
        email: 'Электронная почта',
        password: 'Пароль',
        confirmPassword: 'Подтвердите пароль',
        forgotPassword: 'Забыли пароль?',
        logInWithGoogle: 'Войти с помощью Google',
        logInWithApple: 'Войти с помощью Apple',
        newToJournee: 'Новичок на Journée?',
        createAnAccount: 'Создайте аккаунт',
        alreadyHaveAnAccount: 'У вас уже есть аккаунт?',
        logYouIn: 'Войдите',
    },
};