type Multilingual = {
    'español': string,
    'english': string,
    'français': string,
    'deutsch': string,
    'italiano': string,
    'Русский': string,
}

export const categories: Multilingual[] = 
[
    {
        'español': 'Restauración',
        'english': 'Restoration',
        'français': 'Restauration',
        'deutsch': 'Restaurierung',
        'italiano': 'Restauro',
        'Русский': 'Реставрация',
    },
    {
        'español': 'Fabricación',
        'english': 'Manufacturing',
        'français': 'Fabrication',
        'deutsch': 'Herstellung',
        'italiano': 'Produzione',
        'Русский': 'Производство',
    },
    {
        'español': 'Personalización',
        'english': 'Customization',
        'français': 'Personnalisation',
        'deutsch': 'Individualisierung',
        'italiano': 'Personalizzazione',
        'Русский': 'Персонализация',
    },
];

export const guitarStorage: {
    name: Multilingual,
    category: number,
    edition: Multilingual,
    description: Multilingual,
    price: string,
    fileNames: string[],
    allowSmallSize: boolean,
    filesExtension: string,
}[] =
([
    {
        name: {
            'español': 'Mantidae',
            'english': 'Mantidae',
            'français': 'Mantidae',
            'deutsch': 'Mantidae',
            'italiano': 'Mantidae',
            'Русский': 'Mantidae',
        },
        category: 0,
        edition: {
            'español': 'CCS-Mantidae',
            'english': 'CCS-Mantidae',
            'français': 'CCS-Mantidae',
            'deutsch': 'CCS-Mantidae',
            'italiano': 'CCS-Mantidae',
            'Русский': 'CCS-Mantidae',
        },
        description: {
            'español': 'Descripción para que compres esta guitarra sin pensarlo dos veces.',
            'english': 'Description to make you buy this guitar without thinking twice.',
            'français': 'Description pour vous faire acheter cette guitare sans hésiter.',
            'deutsch': 'Beschreibung, um diese Gitarre zu kaufen, ohne zweimal nachzudenken.',
            'italiano': 'Descrizione per farti comprare questa chitarra senza pensarci due volte.',
            'Русский': 'Описание, чтобы заставить вас купить эту гитару, не задумываясь дважды.',
        },
        price: '3,699,000.00 COP',
        fileNames: [
            'guitarre1front',
            'guitarre1derriere',
        ],
        allowSmallSize: true,
        filesExtension: 'png',
    },
    {
        name: {
            'español': 'Boa constrictor',
            'english': 'Boa constrictor',
            'français': 'Boa constrictor',
            'deutsch': 'Boa constrictor',
            'italiano': 'Boa constrictor',
            'Русский': 'Boa constrictor',
        },
        category: 1,
        edition: {
            'español': 'CCS-Boa constrictor',
            'english': 'CCS-Boa constrictor',
            'français': 'CCS-Boa constrictor',
            'deutsch': 'CCS-Boa constrictor',
            'italiano': 'CCS-Boa constrictor',
            'Русский': 'CCS-Boa constrictor',
        },    
        description: {
            'español': 'Descripción para que compres esta guitarra sin pensarlo dos veces.',
            'english': 'Description to make you buy this guitar without thinking twice.',
            'français': 'Description pour vous faire acheter cette guitare sans hésiter.',
            'deutsch': 'Beschreibung, um diese Gitarre zu kaufen, ohne zweimal nachzudenken.',
            'italiano': 'Descrizione per farti comprare questa chitarra senza pensarci due volte.',
            'Русский': 'Описание, чтобы заставить вас купить эту гитару, не задумываясь дважды.',
        },
        price: '4,099,000.00 COP',
        fileNames: [
            'guitarre2front',
            'guitarre2derriere',
        ],
        allowSmallSize: true,
        filesExtension: 'png',
    },
    {
        name: {
            'español': 'Asio clamator',
            'english': 'Asio clamator',
            'français': 'Asio clamator',
            'deutsch': 'Asio clamator',
            'italiano': 'Asio clamator',
            'Русский': 'Asio clamator',
        },
        category: 1,
        edition: {
            'español': 'CCS-Asio clamator',
            'english': 'CCS-Asio clamator',
            'français': 'CCS-Asio clamator',
            'deutsch': 'CCS-Asio clamator',
            'italiano': 'CCS-Asio clamator',
            'Русский': 'CCS-Asio clamator',
        },
        description: {
            'español': 'Descripción para que compres esta guitarra sin pensarlo dos veces.',
            'english': 'Description to make you buy this guitar without thinking twice.',
            'français': 'Description pour vous faire acheter cette guitare sans hésiter.',
            'deutsch': 'Beschreibung, um diese Gitarre zu kaufen, ohne zweimal nachzudenken.',
            'italiano': 'Descrizione per farti comprare questa chitarra senza pensarci due volte.',
            'Русский': 'Описание, чтобы заставить вас купить эту гитару, не задумываясь дважды.',
        },
        price: '2,999,000.00 COP',
        fileNames: [
            'guitarre3front',
            'guitarre3derriere',
        ],
        allowSmallSize: true,
        filesExtension: 'png',
    },
]);