export const translator = {
    español: {
        error: "Ha ocurrido un error.",
        paginaNoDisponible: 'Página no disponible',
        idioma: 'Idioma',
        imagen: 'Imagen',

        masInformacion: 'Más información',
        inicio: 'Inicio',
        acercaDeNosotros: 'Acerca de nosotros',
        contactanos: 'Contáctanos',
        edicion: 'Edición',
        compartir: 'Compartir',
        guitarraAnterior: 'Guitarra Anterior',
        guitarraSiguiente: 'Siguiente Guitarra',

        restauracion: 'Restauración',
        fabricacion: 'Fabricación',
        personalizacion: 'Personalización',
        personalizable: 'Guitarras a pedido del cliente (color, escala y accesorios).',
        fabricacionCompleta: 'Fabricación desde 0.',
        conForro: 'Incluye forro o estuche semiduro.',
        garantia: '12 meses de garantía por defectos de fabricación.',

        resumenCCS: 'CSS-Guitars es una marca colombiana de instrumentos musicales, inspirada en la biodiversidad y riqueza presentes en este lado del mundo. El proyecto surge de la necesidad de muchos músicos de adquirir instrumentos de gran calidad a precios cómodos. Son guitarras artesanales, y en cada modelo se mezcla la potencia del sonido y la importancia de la fauna silvestre, por eso las referencias de cada instrumento se inspiran en especies emblemáticas y de gran importancia ecológica para los bosques. <br><br> Cada instrumento que se fabrique bajo nuestra marca será único, y el cliente podrá disfrutar de una pieza exclusiva en su colección.',
        elEquipoDeCCS: "El equipo de CCS",
    },
    english: {
        error: "An error has occurred.",
        paginaNoDisponible: 'Page not available',
        idioma: 'Language',
        imagen: 'Image',

        masInformacion: 'More Info',
        inicio: 'Home',
        acercaDeNosotros: 'About Us',
        contactanos: 'Contact Us',
        edicion: 'Edition',
        compartir: 'Share',
        guitarraAnterior: 'Previous Guitar',
        guitarraSiguiente: 'Next Guitar',

        restauracion: 'Restoration',
        fabricacion: 'Manufacturing',
        personalizacion: 'Customization',
        personalizable: 'Custom guitars (color, scale, and accessories) upon customer request.',
        fabricacionCompleta: 'Manufacturing from scratch.',
        conForro: 'Includes soft or semi-hard case.',
        garantia: '12 months warranty for manufacturing defects.',

        resumenCCS: 'CSS-Guitars is a Colombian brand of musical instruments, inspired by the biodiversity and richness found on this side of the world. The project arises from the need of many musicians to acquire high-quality instruments at comfortable prices. They are handmade guitars, and in each model, the power of sound is blended with the importance of wildlife. That\'s why the references for each instrument are inspired by emblematic species with great ecological significance for the forests. <br><br> Every instrument manufactured under our brand will be unique, and the customer will enjoy an exclusive piece in their collection.',
        elEquipoDeCCS: "The CCS Team",
    },
    français: {
        error: "Une erreur s'est produite.",
        paginaNoDisponible: 'Page non disponible',
        idioma: 'Langue',
        imagen: 'Image',

        masInformacion: 'Plus d\'informations',
        inicio: 'Accueil',
        acercaDeNosotros: 'À Propos de Nous',
        contactanos: 'Contactez-nous',
        edicion: 'Édition',
        compartir: 'Partager',
        guitarraAnterior: 'Guitare précédente',
        guitarraSiguiente: 'Guitare suivante',

        restauracion: 'Restauration',
        fabricacion: 'Fabrication',
        personalizacion: 'Personnalisation',
        personalizable: 'Guitares personnalisées (couleur, échelle et accessoires) sur demande du client.',
        fabricacionCompleta: 'Fabrication à partir de zéro.',
        conForro: 'Comprend une housse souple ou un étui semi-rigide.',
        garantia: 'Garantie de 12 mois contre les défauts de fabrication.',

        resumenCCS: "CSS-Guitars est une marque colombienne d'instruments de musique, inspirée par la biodiversité et la richesse présentes de ce côté du monde. Le projet naît du besoin de nombreux musiciens d'acquérir des instruments de grande qualité à des prix confortables. Ce sont des guitares artisanales, et dans chaque modèle, la puissance du son se mêle à l'importance de la faune sauvage. C'est pourquoi les références de chaque instrument s'inspirent d'espèces emblématiques et d'une grande importance écologique pour les forêts. <br><br> Chaque instrument fabriqué sous notre marque sera unique, et le client pourra profiter d'une pièce exclusive dans sa collection.",
        elEquipoDeCCS: "L'équipe de CCS",
    },
    deutsch:{
        error: "Ein Fehler ist aufgetreten.",
        paginaNoDisponible: 'Seite nicht verfügbar',
        idioma: 'Sprache',
        imagen: 'Bild',

        masInformacion: 'Mehr Info',
        inicio: 'Startseite',
        acercaDeNosotros: 'Über uns',
        contactanos: 'Kontaktiere uns',
        edicion: 'Ausgabe',
        compartir: 'Teilen',
        guitarraAnterior: 'Vorherige Gitarre',
        guitarraSiguiente: 'Nächste Gitarre',

        restauracion: 'Restaurierung',
        fabricacion: 'Herstellung',
        personalizacion: 'Individualisierung',
        personalizable: 'Maßgeschneiderte Gitarren (Farbe, Skala und Zubehör) auf Kundenwunsch.',
        fabricacionCompleta: 'Herstellung von Grund auf.',
        conForro: 'Enthält eine weiche oder halbharte Hülle.',
        garantia: '12 Monate Garantie auf Herstellungsfehler.',

        resumenCCS: "CSS-Guitars ist eine kolumbianische Marke für Musikinstrumente, inspiriert von der Biodiversität und dem Reichtum, die auf dieser Seite der Welt zu finden sind. Das Projekt entstand aus dem Bedarf vieler Musiker, hochwertige Instrumente zu erschwinglichen Preisen zu erwerben. Es handelt sich um handgefertigte Gitarren, und in jedem Modell verbindet sich die Kraft des Klangs mit der Bedeutung der Wildfauna. Daher lassen sich die Referenzen jedes Instruments von emblematischen Arten inspirieren, die für die Wälder von großer ökologischer Bedeutung sind. <br><br> Jedes unter unserer Marke hergestellte Instrument wird einzigartig sein, und der Kunde wird Freude an einem exklusiven Stück in seiner Sammlung haben.",
        elEquipoDeCCS: "Das CCS-Team",
    },
    italiano:{
        error: "Si è verificato un errore.",
        paginaNoDisponible: 'Pagina non disponibile',
        idioma: 'Lingua',
        imagen: 'Immagine',

        masInformacion: 'Ulteriori informazioni',
        inicio: 'Home',
        acercaDeNosotros: 'Chi siamo',
        contactanos: 'Contattaci',
        edicion: 'Edizione',
        compartir: 'Condividi',
        guitarraAnterior: 'Chitarra precedente',
        guitarraSiguiente: 'Prossima chitarra',

        restauracion: 'Restauro',
        fabricacion: 'Produzione',
        personalizacion: 'Personalizzazione',
        personalizable: 'Chitarre personalizzate (colore, scala e accessori) su richiesta del cliente.',
        fabricacionCompleta: 'Produzione da zero.',
        conForro: 'Include custodia morbida o semirigida.',
        garantia: 'Garanzia di 12 mesi per difetti di fabbricazione.',

        resumenCCS: "CSS-Guitars è un marchio colombiano di strumenti musicali, ispirato dalla biodiversità e dalla ricchezza presenti da questo lato del mondo. Il progetto nasce dalla necessità di molti musicisti di acquisire strumenti di alta qualità a prezzi comodi. Sono chitarre artigianali, e in ogni modello si mescola la potenza del suono con l'importanza della fauna selvatica. Per questo le referenze di ogni strumento si ispirano a specie emblematiche di grande importanza ecologica per le foreste. <br><br> Ogni strumento fabbricato sotto il nostro marchio sarà unico, e il cliente potrà godere di un pezzo esclusivo nella sua collezione.",
        elEquipoDeCCS: "Il team di CCS",
    },
    Русский: {
        error: "Произошла ошибка.",
        paginaNoDisponible: 'Страница недоступна',
        idioma: 'Язык',
        imagen: 'Изображение',

        masInformacion: 'Дополнительная информация',
        inicio: 'Главная',
        acercaDeNosotros: 'О нас',
        contactanos: 'Свяжитесь с нами',
        edicion: 'Издание',
        compartir: 'Поделиться',
        guitarraAnterior: 'Предыдущая гитара',
        guitarraSiguiente: 'Следующая гитара',

        restauracion: 'Реставрация',
        fabricacion: 'Производство',
        personalizacion: 'Персонализация',
        personalizable: 'Гитары на заказ (цвет, масштаб и аксессуары) по запросу клиента.',
        fabricacionCompleta: 'Производство с нуля.',
        conForro: 'Включает мягкий или полутвёрдый чехол.',
        garantia: '12 месяцев гарантии на производственные дефекты.',

        resumenCCS: "CSS-Guitars - это колумбийская марка музыкальных инструментов, вдохновленная биоразнообразием и богатством, присущими этой стороне света. Проект возник из потребности многих музыкантов в приобретении высококачественных инструментов по доступным ценам. Это ручные гитары, и в каждой модели сочетается мощь звука и важность дикой природы. Поэтому ссылки на каждый инструмент черпают вдохновение из символичных видов, имеющих великое экологическое значение для лесов. <br><br> Каждый инструмент, произведенный под нашим брендом, будет уникален, и клиент сможет наслаждаться эксклюзивным произведением в своей коллекции.",
        elEquipoDeCCS: "Команда CCS",
    },
};