export const translator = {
    es: {
        error: "Ha ocurrido un error.",
        paginaNoDisponible: 'Página no disponible',
        comingSoon: 'Próximamente',
        idioma: 'Idioma',
        imagen: 'Imagen',
        goBack: 'Volver',

        masInformacion: 'Más información',
        inicio: 'Inicio',
        acercaDeNosotros: 'Acerca de nosotros',
        contactanos: 'Contáctanos',
        edicion: 'Edición',
        compartir: 'Compartir',
        guitarraAnterior: 'Guitarra Anterior',
        guitarraSiguiente: 'Siguiente Guitarra',
        previousImage: 'Imagen anterior',
        nextImage: 'Siguiente imagen',
        girarGuitarra: "Girar guitarra",
        siteNavigation: 'Navegación del Sitio',
        emailCopied: 'Correo electrónico copiado al portapapeles',
        getInTouch: '¡Ponte en contacto con CCS Guitars!',
        gatewayToExceptional: 'Descubre un mundo de guitarras extraordinarias con un servicio excepcional.',
        ourEmail: 'Nuestro correo electrónico:',
        copyEmail: 'Copiar correo electrónico',
        visitOurInstagram: 'Visita nuestro Instagram',
        visitOurWonderland: 'Visita nuestro paraíso de guitarras',
        experienceExcellence: 'Descubre la excelencia en nuestra tienda especializada de guitarras.',
        stayTuned: '¡Estamos emocionados de revelarte pronto dónde nos encontramos! ¡No te lo pierdas!',
        ccsGuitarShop: 'La tienda de guitarras CCS',

        restauracion: 'Restauración',
        fabricacion: 'Fabricación',
        personalizacion: 'Personalización',
        personalizable: 'Guitarras a pedido del cliente (color, escala y accesorios).',
        fabricacionCompleta: 'Fabricación desde 0.',
        conForro: 'Incluye forro o estuche semiduro.',
        garantia: '12 meses de garantía por defectos de fabricación.',

        musicalInstrumentsInspired: 'Instrumentos musicales inspirados en la biodiversidad',
        resumenCCS: 'CSS-Guitars es una marca colombiana de instrumentos musicales, inspirada en la biodiversidad y riqueza presentes en este lado del mundo. El proyecto surge de la necesidad de muchos músicos de adquirir instrumentos de gran calidad a precios cómodos. Son guitarras artesanales, y en cada modelo se mezcla la potencia del sonido y la importancia de la fauna silvestre, por eso las referencias de cada instrumento se inspiran en especies emblemáticas y de gran importancia ecológica para los bosques. <br><br> Cada instrumento que se fabrique bajo nuestra marca será único, y el cliente podrá disfrutar de una pieza exclusiva en su colección.',
        connectWithUs: 'Conéctate con nosotros en CCS Guitars: tu destino único para guitarras excepcionales. Ponte en contacto a través de nuestra página "Contáctanos" para asistencia personalizada e inquiries.',
        elEquipoDeCCS: "El equipo de CCS",

        guitarNoctiliaAndArgia: 'Guitarra Noctilia y Argia en proceso de secado',
        guitarNoctiliaBeforeColor: 'Guitarra Noctilia previa al color',
        guitarNoctiliaColorProcess: 'Guitarra Noctilia en proceso de color',
        guitarNoctiliaBeforeAssembly: 'Guitarra Noctilia previa al ensamblaje',
        guitarAsioClamatorBeforeColor: 'Guitarra Asio Clamator previa al color',
        designingHeadsAsioClamatorBoaConstrictor: 'Diseñando las cabezas de Asio Clamator y Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Guitarra Asio Clamator en proceso de color',
        guitarBoaConstrictorBeforeColor: 'Guitarra Boa Constrictor previa al color',
        guitarBoaConstrictorColorProcess: 'Guitarra Boa Constrictor en proceso de color',
    },
    en: {
        error: "An error has occurred.",
        paginaNoDisponible: 'Page not available',
        comingSoon: 'Coming Soon',
        idioma: 'Language',
        imagen: 'Image',
        goBack: 'Back',

        masInformacion: 'More Info',
        inicio: 'Home',
        acercaDeNosotros: 'About Us',
        contactanos: 'Contact Us',
        edicion: 'Edition',
        compartir: 'Share',
        guitarraAnterior: 'Previous Guitar',
        guitarraSiguiente: 'Next Guitar',
        previousImage: 'Previous Image',
        nextImage: 'Next Image',
        girarGuitarra: "Rotate guitar",
        siteNavigation: 'Site Navigation',
        emailCopied: 'Email copied to clipboard',
        getInTouch: 'Get in Touch with CCS Guitars!',
        gatewayToExceptional: 'Your Gateway to Exceptional Guitars and Unparalleled Service.',
        ourEmail: 'Our Email:',
        copyEmail: 'Copy Email',
        visitOurInstagram: 'Visit our Instagram',
        visitOurWonderland: 'Visit Our Guitar Wonderland',
        experienceExcellence: 'Experience Excellence at Our Specialized Guitar Shop!',
        stayTuned: 'Stay tuned for the exciting location reveal!',
        ccsGuitarShop: 'The CCS Guitar Shop',

        restauracion: 'Restoration',
        fabricacion: 'Manufacturing',
        personalizacion: 'Customization',
        personalizable: 'Custom guitars (color, scale, and accessories) upon customer request.',
        fabricacionCompleta: 'Manufacturing from scratch.',
        conForro: 'Includes soft or semi-hard case.',
        garantia: '12 months warranty for manufacturing defects.',

        musicalInstrumentsInspired: 'Musical Instruments Inspired by Biodiversity',
        resumenCCS: 'CSS-Guitars is a Colombian brand of musical instruments, inspired by the biodiversity and richness found on this side of the world. The project arises from the need of many musicians to acquire high-quality instruments at comfortable prices. They are handmade guitars, and in each model, the power of sound is blended with the importance of wildlife. That\'s why the references for each instrument are inspired by emblematic species with great ecological significance for the forests. <br><br> Every instrument manufactured under our brand will be unique, and the customer will enjoy an exclusive piece in their collection.',
        connectWithUs: 'Connect with us at CCS Guitars - Your one-stop destination for exceptional guitars. Reach out through our \'Contact Us\' page for personalized assistance and inquiries.',
        elEquipoDeCCS: "The CCS Team",

        guitarNoctiliaAndArgia: 'Guitar Noctilia and Argia in the drying process',
        guitarNoctiliaBeforeColor: 'Guitar Noctilia prior to coloring',
        guitarNoctiliaColorProcess: 'Guitar Noctilia in the coloring process',
        guitarNoctiliaBeforeAssembly: 'Guitar Noctilia prior to assembly',
        guitarAsioClamatorBeforeColor: 'Guitar Asio Clamator prior to coloring',
        designingHeadsAsioClamatorBoaConstrictor: 'Designing the heads of Asio Clamator and Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Guitar Asio Clamator in the coloring process',
        guitarBoaConstrictorBeforeColor: 'Guitar Boa Constrictor prior to coloring',
        guitarBoaConstrictorColorProcess: 'Guitar Boa Constrictor in the coloring process',
    },
    fr: {
        error: "Une erreur s'est produite.",
        paginaNoDisponible: 'Page non disponible',
        comingSoon: 'Prochainement',
        idioma: 'Langue',
        imagen: 'Image',
        goBack: 'Retour',

        masInformacion: 'Plus d\'informations',
        inicio: 'Accueil',
        acercaDeNosotros: 'À Propos de Nous',
        contactanos: 'Contactez-nous',
        edicion: 'Édition',
        compartir: 'Partager',
        guitarraAnterior: 'Guitare précédente',
        guitarraSiguiente: 'Guitare suivante',
        previousImage: 'Image précédente',
        nextImage: 'Image suivante',
        girarGuitarra: "Faire tourner la guitare",
        siteNavigation: 'Navigation du Site',
        emailCopied: 'Courriel copié dans le presse-papiers',
        getInTouch: 'Entrez en contact avec CCS Guitars !',
        gatewayToExceptional: 'Votre passerelle vers des guitares exceptionnelles et un service inégalé.',
        ourEmail: 'Notre courriel :',
        copyEmail: 'Copier le courriel',
        visitOurInstagram: 'Visitez notre Instagram',
        visitOurWonderland: 'Visitez notre paradis des guitares',
        experienceExcellence: 'Vivez l\'excellence dans notre boutique spécialisée en guitares !',
        stayTuned: 'Restez à l\'écoute pour la révélation passionnante de l\'emplacement !',
        ccsGuitarShop: 'La boutique de guitares CCS',

        restauracion: 'Restauration',
        fabricacion: 'Fabrication',
        personalizacion: 'Personnalisation',
        personalizable: 'Guitares personnalisées (couleur, échelle et accessoires) sur demande du client.',
        fabricacionCompleta: 'Fabrication à partir de zéro.',
        conForro: 'Comprend une housse souple ou un étui semi-rigide.',
        garantia: 'Garantie de 12 mois contre les défauts de fabrication.',

        musicalInstrumentsInspired: 'Instruments de musique inspirés par la biodiversité',
        resumenCCS: "CSS-Guitars est une marque colombienne d'instruments de musique, inspirée par la biodiversité et la richesse présentes de ce côté du monde. Le projet naît du besoin de nombreux musiciens d'acquérir des instruments de grande qualité à des prix confortables. Ce sont des guitares artisanales, et dans chaque modèle, la puissance du son se mêle à l'importance de la faune sauvage. C'est pourquoi les références de chaque instrument s'inspirent d'espèces emblématiques et d'une grande importance écologique pour les forêts. <br><br> Chaque instrument fabriqué sous notre marque sera unique, et le client pourra profiter d'une pièce exclusive dans sa collection.",
        connectWithUs: 'Connectez-vous avec nous chez CCS Guitars - Votre destination unique pour des guitares exceptionnelles. Contactez-nous via notre page \'Contactez-nous\' pour une assistance personnalisée et des demandes de renseignements.',
        elEquipoDeCCS: "L'équipe de CCS",

        guitarNoctiliaAndArgia: 'Guitare Noctilia et Argia en cours de séchage',
        guitarNoctiliaBeforeColor: 'Guitare Noctilia avant la couleur',
        guitarNoctiliaColorProcess: 'Guitare Noctilia en cours de coloration',
        guitarNoctiliaBeforeAssembly: 'Guitare Noctilia avant l\'assemblage',
        guitarAsioClamatorBeforeColor: 'Guitare Asio Clamator avant la couleur',
        designingHeadsAsioClamatorBoaConstrictor: 'Conception des têtes d\'Asio Clamator et Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Guitare Asio Clamator en cours de coloration',
        guitarBoaConstrictorBeforeColor: 'Guitare Boa Constrictor avant la couleur',
        guitarBoaConstrictorColorProcess: 'Guitare Boa Constrictor en cours de coloration',
    },
    de:{
        error: "Ein Fehler ist aufgetreten.",
        paginaNoDisponible: 'Seite nicht verfügbar',
        comingSoon: 'Demnächst',
        idioma: 'Sprache',
        imagen: 'Bild',
        goBack: 'Zurück',

        masInformacion: 'Mehr Info',
        inicio: 'Startseite',
        acercaDeNosotros: 'Über uns',
        contactanos: 'Kontaktiere uns',
        edicion: 'Ausgabe',
        compartir: 'Teilen',
        guitarraAnterior: 'Vorherige Gitarre',
        guitarraSiguiente: 'Nächste Gitarre',
        previousImage: 'Vorheriges Bild',
        nextImage: 'Nächstes Bild',
        girarGuitarra: "Gitarre drehen",
        siteNavigation: 'Seitennavigation',
        emailCopied: 'E-Mail in die Zwischenablage kopiert',
        getInTouch: 'Nehmen Sie Kontakt mit CCS Guitars auf!',
        gatewayToExceptional: 'Ihr Tor zu außergewöhnlichen Gitarren und unvergleichlichem Service.',
        ourEmail: 'Unsere E-Mail:',
        copyEmail: 'E-Mail kopieren',
        visitOurInstagram: 'Besuchen Sie unser Instagram',
        visitOurWonderland: 'Besuchen Sie unser Gitarrenwunderland',
        experienceExcellence: 'Erleben Sie Exzellenz in unserem spezialisierten Gitarrengeschäft!',
        stayTuned: 'Bleiben Sie dran für die aufregende Enthüllung des Standorts!',
        ccsGuitarShop: 'Der CCS Gitarrenladen',

        restauracion: 'Restaurierung',
        fabricacion: 'Herstellung',
        personalizacion: 'Individualisierung',
        personalizable: 'Maßgeschneiderte Gitarren (Farbe, Skala und Zubehör) auf Kundenwunsch.',
        fabricacionCompleta: 'Herstellung von Grund auf.',
        conForro: 'Enthält eine weiche oder halbharte Hülle.',
        garantia: '12 Monate Garantie auf Herstellungsfehler.',

        musicalInstrumentsInspired: 'Musikinstrumente inspiriert von der Biodiversität',
        resumenCCS: "CSS-Guitars ist eine kolumbianische Marke für Musikinstrumente, inspiriert von der Biodiversität und dem Reichtum, die auf dieser Seite der Welt zu finden sind. Das Projekt entstand aus dem Bedarf vieler Musiker, hochwertige Instrumente zu erschwinglichen Preisen zu erwerben. Es handelt sich um handgefertigte Gitarren, und in jedem Modell verbindet sich die Kraft des Klangs mit der Bedeutung der Wildfauna. Daher lassen sich die Referenzen jedes Instruments von emblematischen Arten inspirieren, die für die Wälder von großer ökologischer Bedeutung sind. <br><br> Jedes unter unserer Marke hergestellte Instrument wird einzigartig sein, und der Kunde wird Freude an einem exklusiven Stück in seiner Sammlung haben.",
        connectWithUs: 'Verbinde dich mit uns bei CCS Guitars - Dein One-Stop-Ziel für außergewöhnliche Gitarren. Melde dich über unsere Seite "Kontaktiere uns" für persönliche Unterstützung und Anfragen.',
        elEquipoDeCCS: "Das CCS-Team",

        guitarNoctiliaAndArgia: 'Gitarre Noctilia und Argia im Trocknungsprozess',
        guitarNoctiliaBeforeColor: 'Gitarre Noctilia vor der Farbgebung',
        guitarNoctiliaColorProcess: 'Gitarre Noctilia im Färbeprozess',
        guitarNoctiliaBeforeAssembly: 'Gitarre Noctilia vor der Montage',
        guitarAsioClamatorBeforeColor: 'Gitarre Asio Clamator vor der Farbgebung',
        designingHeadsAsioClamatorBoaConstrictor: 'Entwurf der Köpfe von Asio Clamator und Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Gitarre Asio Clamator im Färbeprozess',
        guitarBoaConstrictorBeforeColor: 'Gitarre Boa Constrictor vor der Farbgebung',
        guitarBoaConstrictorColorProcess: 'Gitarre Boa Constrictor im Färbeprozess',
    },
    it:{
        error: "Si è verificato un errore.",
        paginaNoDisponible: 'Pagina non disponibile',
        comingSoon: 'Prossimamente',
        idioma: 'Lingua',
        imagen: 'Immagine',
        goBack: 'Indietro',

        masInformacion: 'Ulteriori informazioni',
        inicio: 'Home',
        acercaDeNosotros: 'Chi siamo',
        contactanos: 'Contattaci',
        edicion: 'Edizione',
        compartir: 'Condividi',
        guitarraAnterior: 'Chitarra precedente',
        guitarraSiguiente: 'Prossima chitarra',
        previousImage: 'Immagine precedente',
        nextImage: 'Immagine successiva',
        girarGuitarra: "Ruotare la chitarra",
        siteNavigation: 'Navigazione del Sito',
        emailCopied: 'Email copiata negli appunti',
        getInTouch: 'Entra in contatto con CCS Guitars!',
        gatewayToExceptional: 'Il tuo accesso a chitarre eccezionali e un servizio senza pari.',
        ourEmail: 'La nostra email:',
        copyEmail: 'Copia email',
        visitOurInstagram: 'Visita il nostro Instagram',
        visitOurWonderland: 'Esplora il nostro magico Mondo delle Chitarre',
        experienceExcellence: 'Vivi l\'eccellenza nel nostro negozio specializzato di chitarre!',
        stayTuned: 'Rimani sintonizzato per la sorprendente rivelazione della posizione!',
        ccsGuitarShop: 'Il negozio di chitarre CCS',

        restauracion: 'Restauro',
        fabricacion: 'Produzione',
        personalizacion: 'Personalizzazione',
        personalizable: 'Chitarre personalizzate (colore, scala e accessori) su richiesta del cliente.',
        fabricacionCompleta: 'Produzione da zero.',
        conForro: 'Include custodia morbida o semirigida.',
        garantia: 'Garanzia di 12 mesi per difetti di fabbricazione.',

        musicalInstrumentsInspired: 'Strumenti musicali ispirati dalla biodiversità',
        resumenCCS: "CSS-Guitars è un marchio colombiano di strumenti musicali, ispirato dalla biodiversità e dalla ricchezza presenti da questo lato del mondo. Il progetto nasce dalla necessità di molti musicisti di acquisire strumenti di alta qualità a prezzi comodi. Sono chitarre artigianali, e in ogni modello si mescola la potenza del suono con l'importanza della fauna selvatica. Per questo le referenze di ogni strumento si ispirano a specie emblematiche di grande importanza ecologica per le foreste. <br><br> Ogni strumento fabbricato sotto il nostro marchio sarà unico, e il cliente potrà godere di un pezzo esclusivo nella sua collezione.",
        connectWithUs: 'Collegati con noi presso CCS Guitars - La tua destinazione unica per chitarre eccezionali. Contattaci attraverso la nostra pagina "Contattaci" per assistenza personalizzata e richieste.',
        elEquipoDeCCS: "Il team di CCS",

        guitarNoctiliaAndArgia: 'Chitarra Noctilia e Argia in fase di essiccazione',
        guitarNoctiliaBeforeColor: 'Chitarra Noctilia prima della colorazione',
        guitarNoctiliaColorProcess: 'Chitarra Noctilia in fase di colorazione',
        guitarNoctiliaBeforeAssembly: 'Chitarra Noctilia prima dell\'assemblaggio',
        guitarAsioClamatorBeforeColor: 'Chitarra Asio Clamator prima della colorazione',
        designingHeadsAsioClamatorBoaConstrictor: 'Progettazione delle teste di Asio Clamator e Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Chitarra Asio Clamator in fase di colorazione',
        guitarBoaConstrictorBeforeColor: 'Chitarra Boa Constrictor prima della colorazione',
        guitarBoaConstrictorColorProcess: 'Chitarra Boa Constrictor in fase di colorazione',
    },
    ru: {
        error: "Произошла ошибка.",
        paginaNoDisponible: 'Страница недоступна',
        comingSoon: 'Скоро',
        idioma: 'Язык',
        imagen: 'Изображение',
        goBack: 'Назад',

        masInformacion: 'Дополнительная информация',
        inicio: 'Главная',
        acercaDeNosotros: 'О нас',
        contactanos: 'Свяжитесь с нами',
        edicion: 'Издание',
        compartir: 'Поделиться',
        guitarraAnterior: 'Предыдущая гитара',
        guitarraSiguiente: 'Следующая гитара',
        previousImage: 'Предыдущее изображение',
        nextImage: 'Следующее изображение',
        girarGuitarra: "Повернуть гитару",
        siteNavigation: 'Навигация по сайту',
        emailCopied: 'Email скопирована в буфер обмена',
        getInTouch: 'Свяжитесь с CCS Guitars!',
        gatewayToExceptional: 'Ваш вход в мир исключительных гитар и непревзойденного сервиса.',
        ourEmail: 'Наш email:',
        copyEmail: 'Скопировать email',
        visitOurInstagram: 'Посетите наш Instagram',
        visitOurWonderland: 'Посетите наше гитарное чудо',
        experienceExcellence: 'Опыт превосходства в нашем специализированном магазине гитар!',
        stayTuned: 'Будьте на связи для захватывающего раскрытия местоположения!',
        ccsGuitarShop: 'Магазин гитар CCS',

        restauracion: 'Реставрация',
        fabricacion: 'Производство',
        personalizacion: 'Персонализация',
        personalizable: 'Гитары на заказ (цвет, масштаб и аксессуары) по запросу клиента.',
        fabricacionCompleta: 'Производство с нуля.',
        conForro: 'Включает мягкий или полутвёрдый чехол.',
        garantia: '12 месяцев гарантии на производственные дефекты.',

        musicalInstrumentsInspired: 'Музыкальные инструменты, вдохновленные биоразнообразием',
        resumenCCS: "CSS-Guitars - это колумбийская марка музыкальных инструментов, вдохновленная биоразнообразием и богатством, присущими этой стороне света. Проект возник из потребности многих музыкантов в приобретении высококачественных инструментов по доступным ценам. Это ручные гитары, и в каждой модели сочетается мощь звука и важность дикой природы. Поэтому ссылки на каждый инструмент черпают вдохновение из символичных видов, имеющих великое экологическое значение для лесов. <br><br> Каждый инструмент, произведенный под нашим брендом, будет уникален, и клиент сможет наслаждаться эксклюзивным произведением в своей коллекции.",
        connectWithUs: 'Свяжитесь с нами в CCS Guitars - вашим единственным пунктом назначения для исключительных гитар. Обратитесь через нашу страницу "Свяжитесь с нами" для персонализированной помощи и запросов.',
        elEquipoDeCCS: "Команда CCS",

        guitarNoctiliaAndArgia: 'Гитара Noctilia и Argia в процессе сушки',
        guitarNoctiliaBeforeColor: 'Гитара Noctilia перед окраской',
        guitarNoctiliaColorProcess: 'Гитара Noctilia в процессе окрашивания',
        guitarNoctiliaBeforeAssembly: 'Гитара Noctilia перед сборкой',
        guitarAsioClamatorBeforeColor: 'Гитара Asio Clamator перед окраской',
        designingHeadsAsioClamatorBoaConstrictor: 'Проектирование голов Asio Clamator и Boa Constrictor',
        guitarAsioClamatorColorProcess: 'Гитара Asio Clamator в процессе окрашивания',
        guitarBoaConstrictorBeforeColor: 'Гитара Boa Constrictor перед окраской',
        guitarBoaConstrictorColorProcess: 'Гитара Boa Constrictor в процессе окрашивания',
    },
};