export const tasks = {
    es: [
        "Grita 3 comidas que empiecen con la letra P.",
        "Da la mano a un compañero. Ambos deben fingir recibir una descarga eléctrica.",
        "Inventa un dicho profundo y cuéntaselo a tu equipo como sabias palabras.",
        "¿Cuánto es 55 menos 29?",
        "Nombra cinco personas famosas de la historia.",
        "Di tres números que se lean igual al revés.",
        "Finge que haces un golpe de golf y haces un hoyo en uno, ¡celebra como corresponde!",
        "Haz el sonido de tres animales y haz que tu equipo los adivine.",
        "Tú y tu equipo deben ordenarse por altura.",
        "Di tres palabras en italiano (que no sean números).",
        "Abraza una silla.",
        "Dale un consejo a cada persona de tu equipo.",
        "Haz una bola con algo y lánzala al otro equipo.",
        "Grita cinco tipos de comida para llevar.",
        "Nombra cinco personajes de programas de televisión.",
        "Di “El carro rojo rueda rápido” cinco veces.",
        "Finge ser un aspersor de agua, pero sin el agua.",
        "Cruza los ocho dedos de tus manos al mismo tiempo.",
        "Finge apagar el interruptor de cada uno de tus compañeros, uno por uno.",
        "Equilibra algo en tu cabeza durante tres segundos.",
        "Intercambia una prenda de ropa con un compañero.",
        "Deletrea “Estoy loco” al revés y sin mirar el dispositivo.",
        "Acurrúcate en las piernas de un compañero y ronronea.",
        "Intercambia zapatos con un miembro de tu equipo.",
        "Juega “piedra, papel o tijeras” con un compañero hasta que ganes, sin hablar.",
        "Toca el lóbulo de la oreja de todos en tu equipo (pero no muy fuerte).",
        "Canta una canción que tenga un color en la letra.",
        "Truena los nudillos.",
        "Haz que todo tu equipo haga un movimiento de aeróbicos durante tres segundos.",
        "Haz el “moonwalk” alrededor de otro jugador.",
        "Finge que estás pescando y acabas de atrapar uno grande.",
        "Cuenta los dientes de tu boca.",
        "Lanza una moneda hasta que salga cara.",
        "Di los nombres de las personas de tu equipo en orden alfabético.",
        "Inventa un rap sobre tu equipo.",
        "Haz la ola con el resto de tu equipo tres veces.",
        "Imita el sonido de dos instrumentos; tu equipo debe adivinarlos.",
        "Llena tu boca con líquido y di tu nombre completo.",
        "Finge que sostienes un racimo de uvas y alimenta a cada uno de tus compañeros con una.",
        "Haz un ruido de eructo (real o falso).",
        "Cierra los ojos e intercambia lugares con un compañero.",
        "Sube ambas piernas del pantalón y grita “¡la marea está subiendo!”.",
        "Grita “¡alguien pisó popó de perro!” y haz que tu equipo huela sus zapatos.",
        "Haz una imitación de alguien de tu equipo; tu equipo debe adivinar quién es.",
        "Inventa el nombre de un invento y describe lo que hace.",
        "Haz un apretón de manos secreto con un jugador que dure al menos tres segundos.",
        "Toca un ritmo en la mesa y haz que tus compañeros se unan.",
        "Finge que caminas hacia un sótano.",
        "Tú y tus compañeros deben cerrar los ojos y tocar los dedos índices.",
        "Di “Soy Batman”. Por turnos, tus compañeros deben decir “Soy Batman”, cada uno diciéndolo en un tono más bajo.",
        "Aúlla a la luna. Todo tu equipo debe aullar de vuelta.",
        "Aplaude durante tres segundos usando una de tus manos y una de las manos de tu compañero.",
        "Nombra tres cosas del menú de McDonald’s.",
        "Grita tres cosas que odiarías recibir en Navidad.",
        "Nombra tres personas famosas con barba.",
        "Baila lento con un compañero durante tres segundos.",
        "Grita una palabra. Cada miembro de tu equipo debe rimarla con una nueva palabra.",
        "Grita un animal que se parezca a cada persona de tu equipo.",
        "Párate y haz que un compañero te corte como un árbol; debes gritar “¡fuera abajo!” mientras caes.",
        "Métete debajo de la mesa y tararea el tema de “Tiburón”.",
        "Grita dos spoilers de películas.",
        "Tu equipo debe adivinar de qué color es tu ropa interior.",
        "Señala tres objetos que cuesten menos de un dólar.",
        `Párate y toca los bongos en la cabeza de uno de tus compañeros.`,
        `Grita tres cosas que nunca debes comer.`,
        `Juega “Veo, veo” con tu equipo. Ellos deben adivinar el objeto.`,
        `Grita tres cosas que rimen con tu nombre.`,
        `Tararea un tema de televisión. Haz que tu equipo adivine cuál es.`,
        `Grita cuatro cosas que comiencen con la letra “E”.`,
        `Grita tres cosas que comiencen con la letra “B”.`,
        `Haz una guerra de pulgares con tu compañero.`,
        `Señala a cada uno de tus compañeros y di mal sus nombres.`,
        `Hazte pasar por un reloj y usa tus brazos para marcar la una y cincuenta y cinco.`,
        `Lanza y atrapa algo con la misma mano.`,
        `¿Cuántos meses tienen 28 días?`,
        `¿Qué número ocupa la letra “T” en el alfabeto?`,
        `Ponte en el suelo e imita un cangrejo.`,
        `Grita tres apodos para ti mismo.`,
        `Grita cinco ingredientes que puedes poner en una hamburguesa.`,
        `Di tres palíndromos.`,
        `Haz que tus compañeros inventen el nombre de un paso de baile. Debes hacerlo.`,
        `Nombra cinco personajes de libros.`,
        `Haz un sonido de pedo en tu brazo durante tres segundos.`,
        `¿Qué pesa más? ¿Un kilogramo de plumas o un kilogramo de ladrillos?`,
        `Salta por encima de algo.`,
        `Haz la Macarena.`,
        `Equilibra tres cosas una encima de la otra.`,
        `Silba toda la canción de “Cumpleaños feliz.”`,
        `Di “Hola” en tres idiomas extranjeros.`,
        `Grita tres bebidas de café diferentes.`,
        `Toca un solo de guitarra imaginario durante tres segundos.`,
        `Muévete como un robot durante tres segundos.`,
        `Tararea tu canción favorita. Haz que tus compañeros adivinen cuál es.`,
        `Consigue dos personas y realiza una ceremonia de boda para ellos.`,
        `Grita una palabra con tres vocales, ni más ni menos.`,
        `Describe a tu pareja ideal en tres palabras.`,
        `Encuentra una cara en un objeto inanimado en la habitación.`,
        `Finge que tienes un control remoto. Apunta a tu equipo, presiona avanzar rápido y pausa.`,
        `Señala a la persona más alta de tu equipo y grita “¿Cómo está el clima allá arriba?”`,
        `Mueve un brazo en el sentido de las agujas del reloj y el otro en sentido contrario al mismo tiempo.`,
        `Quítate una prenda y envuélvela alrededor de tu cabeza.`,
        `Grita el nombre de tu futura autobiografía.`,
        `Aplaude con tus codos juntos cinco veces.`,
        `Nombra cinco países que empiecen con la letra “C”.`,
        `Recomienda tres libros a la sala.`,
        `Acuéstate en el suelo y finge ser un trozo de tocino chisporroteando en una sartén.`,
        `Finge que te quedas dormido y empiezas a roncar. Todo tu equipo debe quedarse dormido también.`,
        `Frota tu estómago y da palmaditas en tu cabeza al mismo tiempo durante tres segundos.`,
        `Grita tres palabras. Tu equipo debe gritar lo contrario.`,
        `Suma las tallas de zapatos de todos en tu equipo.`,
        `Recita los días de la semana en orden inverso.`,
        `Grita cinco cosas que sean más pequeñas que un ratón.`,
        `Grita cinco sabores de batido.`,
        `Di tres palabras en francés (que no sean números).`,
        `Señala tres objetos que sean verdes.`,
        `Canta una canción que tenga un animal en ella.`,
        'Cuenta hasta 10 como un cavernícola.',
    ],
    en: [
        "Shout out 3 fruits beginning with the letter P.",
        "Shake a teammate’s hand. You must both pretend to get an electric shock.",
        "Make up a profound saying and tell your team the wise words.",
        "What is 55 minus 29?",
        "Shout out the names of five famous people from history.",
        "Say three numbers that read the same upside down.",
        "Pretend to take a golf shot and get a hole-in-one, celebrate accordingly.",
        "Make the sound of three animals and get your team to guess them.",
        "You and your team must get into height order.",
        "Say three words in Italian (not numbers).",
        "Hug a chair.",
        "Give each person on your team a piece of advice.",
        "Make a ball out of something and throw it at the other team.",
        "Shout out five types of takeaway food.",
        "Shout out the names of five characters from TV shows.",
        "Say “Red Lorry Yellow Lorry” five times.",
        "Pretend to be a water sprinkler but without the water.",
        "Cross all eight of your fingers at the same time.",
        "Pretend to flip the off-switch on each one of your teammates one by one.",
        "Balance something on your head for three seconds.",
        "Swap an item of clothing with a teammate.",
        "Spell “I am a dummy” backwards.",
        "Curl up on a teammate’s lap and purr.",
        "Swap shoes with a member of your team.",
        "Play a teammate at rock paper scissors until you win - no talking.",
        "Flick the earlobe of everyone on your team (but not too hard).",
        "Sing a song with a color in it.",
        "Crack your knuckles.",
        "Make your whole team do an aerobics move for three seconds.",
        "Moonwalk around another player.",
        "Pretend you’re fishing and you just hooked a big one.",
        "Count the teeth in your mouth.",
        "Flip a coin until you get heads.",
        "Say the first names of the people in your team in alphabetical order.",
        "Make up a rap about your team.",
        "Do the wave with the rest of your team three times around.",
        "Make the sound of two instruments, your team must guess them.",
        "Fill your mouth with liquid and say your full name.",
        "Pretend to hold a bunch of grapes and feed one to each of your teammates.",
        "Make a burp noise (real or fake is fine).",
        "Close your eyes and swap places with a teammate.",
        "Roll up both pant legs and shout “the tide is coming in”.",
        "Shout “someone has stepped in dog-poop” and get your team to sniff their shoes.",
        "Do an impression of someone on your team, your team must guess who it is.",
        "Make up the name of an invention and describe what it does.",
        "Make a secret handshake with a player that lasts at least three seconds.",
        "Drum a rhythm on the table and get your teammates to join in.",
        "Pretend to walk into a basement.",
        "You and your teammates must close eyes and touch index fingertips.",
        "Say “I’m Batman”. In turn, your teammates must say “I’m Batman”, each saying it in a lower voice.",
        "Howl at the moon. Your team must all howl back.",
        "Clap for three seconds using one of your hands and one of your teammate’s hands.",
        "Shout out three things on the menu at McDonald’s.",
        "Shout out three things that you’d hate to get for Christmas.",
        "Name three famous people with beards.",
        "Slow dance with a teammate for three seconds.",
        "Shout out a word. Each member of your team must rhyme it with a new word.",
        "Shout out an animal lookalike for everyone on your team.",
        "Stand up and get a teammate to cut you down like a tree; you must shout “timber” as you fall.",
        "Get under the table and hum the theme from Jaws.",
        "Shout out two film spoilers.",
        "Your team has to guess the color of the underwear you’re wearing.",
        "Point to three items that are worth less than one dollar.",
        `Stand up and play the bongos on one of your teammate’s heads.`,
        `Shout out three things you should never eat.`,
        `Play a game of I spy with your team. They must guess the object.`,
        `Shout out three things that rhyme with your first name.`,
        `Hum a TV theme. Get your team to guess what it is.`,
        `Shout out four things beginning with the letter “Q”`,
        `Shout out three things beginning with the letter “B”`,
        `Have a thumb war with your teammate.`,
        `Point at each of your teammates and shout out their names just slightly wrong.`,
        `Pretend to be a clock and use your arms to display fifty-five minutes past one.`,
        `Throw and catch something with the same hand.`,
        `How many months have 28 days?`,
        `What number in the alphabet is the letter “T”?`,
        `Get on the floor and do a crab impression.`,
        `Shout out three nicknames for yourself.`,
        `Shout out five toppings you might have on a burger.`,
        `Shout out three palindromes.`,
        `Get your teammates to make up the name of a dance move. You must do it.`,
        `Name five characters from books.`,
        `Make a fart noise on your arm for three seconds.`,
        `Which weighs more? A kilogram of feathers or a kilogram of bricks?`,
        `Jump over something.`,
        `Do the Macarena.`,
        `Balance three things on top of each other.`,
        `Whistle the whole of “Happy Birthday”`,
        `Say “Hello” in three foreign languages.`,
        `Shout out three different coffee drinks.`,
        `Play an intense imaginary guitar solo for three seconds.`,
        `Move like a robot for three seconds.`,
        `Hum your favorite song. Get your teammates to guess what it is.`,
        `Get two people and perform a wedding service for them.`,
        `Shout out a word with three vowels in it.`,
        `Describe your ideal partner in three words.`,
        `Find a face on an inanimate object in the room.`,
        `Pretend you have a remote control. Point it at your team, press fast forward and pause.`,
        `Point to the tallest person on your team and shout “what’s the weather like up there?”`,
        `Swing one arm clockwise and the other arm counterclockwise at the same time.`,
        `Take off an item of clothing and wrap it around your head.`,
        `Shout out the name of your upcoming autobiography.`,
        `Clap your elbows together five times.`,
        `List five countries that begin with the letter “C”`,
        `Recommend three books to the room.`,
        `Lie on the floor and pretend to be a piece of bacon sizzling in a pan.`,
        `Pretend to fall asleep and start snoring. Everyone on your team must fall asleep too.`,
        `Rub your stomach and pat your head at the same time for three seconds.`,
        `Shout out three words. Your team must shout out the opposite.`,
        `Add up the shoe sizes of everyone on your team.`,
        `Recite the days of the week in reverse order.`,
        `Shout out five things that are smaller than a mouse.`,
        `Shout out five flavors of milkshake.`,
        `Say three French words (not numbers).`,
        `Point to three objects that are green.`,
        `Sing a song with an animal in it.`,
        'Count to 10 like a caveman.',
    ],
    fr: [
        "Criez 3 fruits commençant par la lettre P.",
        "Serrez la main d’un coéquipier. Vous devez tous les deux prétendre recevoir une décharge électrique.",
        "Inventez un dicton profond et dites-le à votre équipe comme des mots sages.",
        "Combien font 55 moins 29 ?",
        "Nommez cinq personnes célèbres de l’histoire.",
        "Dites trois nombres qui se lisent de la même manière à l’envers.",
        "Faites semblant de faire un coup de golf et de mettre la balle en un seul coup, célébrez en conséquence !",
        "Faites le son de trois animaux et faites deviner à votre équipe lesquels ils sont.",
        "Vous et votre équipe devez vous mettre en ordre de taille.",
        "Dites trois mots en italien (pas des chiffres).",
        "Serrez une chaise dans vos bras.",
        "Donnez un conseil à chaque personne de votre équipe.",
        "Faites une boule avec quelque chose et lancez-la à l’autre équipe.",
        "Criez cinq types de plats à emporter.",
        "Nommez cinq personnages de séries télévisées.",
        "Dites “Camion rouge, Camion jaune” cinq fois.",
        "Faites semblant d’être un arroseur d’eau, mais sans l’eau.",
        "Croisez tous vos doigts des deux mains en même temps.",
        "Faites semblant d’éteindre chaque membre de votre équipe un par un.",
        "Équilibrez quelque chose sur votre tête pendant trois secondes.",
        "Échangez un vêtement avec un coéquipier.",
        "Épelez “Je suis un idiot” à l’envers.",
        "Blottissez-vous sur les genoux d’un coéquipier et ronronnez.",
        "Échangez vos chaussures avec un membre de votre équipe.",
        "Jouez à “Pierre, Papier, Ciseaux” avec un coéquipier jusqu’à ce que vous gagniez - sans parler.",
        "Tirez le lobe d’oreille de chaque membre de votre équipe (mais pas trop fort).",
        "Chantez une chanson contenant une couleur.",
        "Faites craquer vos articulations.",
        "Faites faire un mouvement d’aérobic à toute votre équipe pendant trois secondes.",
        "Faites le “moonwalk” autour d’un autre joueur.",
        "Faites semblant de pêcher et de capturer un gros poisson.",
        "Comptez les dents dans votre bouche.",
        "Lancez une pièce jusqu’à ce que vous obteniez face.",
        "Dites les prénoms des membres de votre équipe par ordre alphabétique.",
        "Inventez un rap sur votre équipe.",
        "Faites la vague avec votre équipe trois fois.",
        "Faites le son de deux instruments, votre équipe doit les deviner.",
        "Remplissez votre bouche de liquide et dites votre nom complet.",
        "Faites semblant de tenir une grappe de raisins et nourrissez chacun de vos coéquipiers.",
        "Faites un bruit de rot (vrai ou faux, peu importe).",
        "Fermez les yeux et échangez de place avec un coéquipier.",
        "Remontez les deux jambes de votre pantalon et criez “la marée monte”.",
        "Criez “quelqu’un a marché dans du caca de chien” et faites sentir les chaussures de votre équipe.",
        "Faites une imitation de quelqu’un dans votre équipe, votre équipe doit deviner qui c’est.",
        "Inventez le nom d’une invention et décrivez ce qu’elle fait.",
        "Faites une poignée de main secrète avec un joueur qui dure au moins trois secondes.",
        "Battez un rythme sur la table et faites participer vos coéquipiers.",
        "Faites semblant de marcher dans un sous-sol.",
        "Vous et vos coéquipiers devez fermer les yeux et toucher vos index.",
        "Dites “Je suis Batman”. À tour de rôle, vos coéquipiers doivent dire “Je suis Batman”, chacun en le disant avec une voix plus grave.",
        "Hurlez à la lune. Votre équipe doit tous hurler en retour.",
        "Applaudissez pendant trois secondes en utilisant une de vos mains et celle d’un coéquipier.",
        "Criez trois choses du menu de McDonald’s.",
        "Criez trois choses que vous détesteriez recevoir pour Noël.",
        "Nommez trois personnes célèbres avec une barbe.",
        "Dansez lentement avec un coéquipier pendant trois secondes.",
        "Criez un mot. Chaque membre de votre équipe doit rimer avec un nouveau mot.",
        "Nommez un animal qui ressemble à chaque membre de votre équipe.",
        "Levez-vous et faites qu’un coéquipier vous abatte comme un arbre, vous devez crier “Timber !” en tombant.",
        "Glissez-vous sous la table et fredonnez le thème de “Jaws”.",
        "Criez deux spoilers de films.",
        "Votre équipe doit deviner la couleur de vos sous-vêtements.",
        "Pointez trois objets qui valent moins d’un euro.",
        `Levez-vous et jouez des bongos sur la tête de l’un de vos coéquipiers.`,
        `Criez trois choses que vous ne devriez jamais manger.`,
        `Jouez à “Je vois” avec votre équipe. Ils doivent deviner l’objet.`,
        `Criez trois choses qui riment avec votre prénom.`,
        `Fredonnez un thème de télévision. Faites deviner à votre équipe ce que c’est.`,
        `Criez quatre choses qui commencent par la lettre “Q”.`,
        `Criez trois choses qui commencent par la lettre “B”.`,
        `Faites une bataille de pouces avec votre coéquipier.`,
        `Pointez chacun de vos coéquipiers et prononcez leurs noms légèrement de travers.`,
        `Faites semblant d’être une horloge et utilisez vos bras pour indiquer une heure moins cinq.`,
        `Lancez et attrapez quelque chose avec la même main.`,
        `Combien de mois ont 28 jours ?`,
        `Quel numéro occupe la lettre “T” dans l’alphabet ?`,
        `Allongez-vous sur le sol et faites l’impression d’un crabe.`,
        `Criez trois surnoms pour vous-même.`,
        `Criez cinq garnitures que vous pourriez mettre sur un burger.`,
        `Criez trois palindromes.`,
        `Demandez à vos coéquipiers d’inventer le nom d’un mouvement de danse. Vous devez le faire.`,
        `Nommez cinq personnages de livres.`,
        `Faites un bruit de pet sur votre bras pendant trois secondes.`,
        `Qu’est-ce qui pèse le plus ? Un kilogramme de plumes ou un kilogramme de briques ?`,
        `Sautez par-dessus quelque chose.`,
        `Faites la Macarena.`,
        `Équilibrez trois choses l’une sur l’autre.`,
        `Sifflez toute la chanson “Joyeux anniversaire”.`,
        `Dites “Bonjour” en trois langues étrangères.`,
        `Criez trois boissons au café différentes.`,
        `Jouez un solo de guitare imaginaire intense pendant trois secondes.`,
        `Bougez comme un robot pendant trois secondes.`,
        `Fredonnez votre chanson préférée. Faites deviner à vos coéquipiers ce que c’est.`,
        `Prenez deux personnes et effectuez un service de mariage pour elles.`,
        `Criez un mot contenant trois voyelles.`,
        `Décrivez votre partenaire idéal en trois mots.`,
        `Trouvez un visage sur un objet inanimé dans la pièce.`,
        `Faites semblant d’avoir une télécommande. Pointez-la sur votre équipe, appuyez sur avance rapide et pause.`,
        `Pointez la personne la plus grande de votre équipe et criez “Quel temps fait-il là-haut ?”`,
        `Faites tourner un bras dans le sens des aiguilles d’une montre et l’autre dans le sens contraire en même temps.`,
        `Retirez un vêtement et enroulez-le autour de votre tête.`,
        `Criez le titre de votre prochaine autobiographie.`,
        `Tapez vos coudes ensemble cinq fois.`,
        `Nommez cinq pays qui commencent par la lettre “C”.`,
        `Recommandez trois livres à la salle.`,
        `Allongez-vous par terre et faites semblant d’être un morceau de bacon qui grésille dans une poêle.`,
        `Faites semblant de vous endormir et commencez à ronfler. Tout votre équipe doit s’endormir aussi.`,
        `Frottez votre ventre et tapotez votre tête en même temps pendant trois secondes.`,
        `Criez trois mots. Votre équipe doit crier l’opposé.`,
        `Additionnez les pointures des chaussures de chacun de votre équipe.`,
        `Récitez les jours de la semaine à l’envers.`,
        `Criez cinq choses plus petites qu’une souris.`,
        `Criez cinq saveurs de milkshake.`,
        `Dites trois mots en espagnol (pas des chiffres).`,
        `Pointez trois objets qui sont verts.`,
        `Chantez une chanson avec un animal dedans.`,
        'Compte jusqu’à 10 comme un homme des cavernes.',
    ],
    de: [
        "Rufen Sie 3 Früchte, die mit dem Buchstaben P beginnen.",
        "Schütteln Sie die Hand eines Teamkollegen. Ihr müsst beide so tun, als ob ihr einen elektrischen Schlag bekommt.",
        "Erfinden Sie einen tiefgründigen Spruch und sagen Sie Ihrem Team die weisen Worte.",
        "Was ist 55 minus 29?",
        "Nennen Sie fünf berühmte Personen aus der Geschichte.",
        "Sagen Sie drei Zahlen, die auf dem Kopf stehend gleich gelesen werden können.",
        "Tun Sie so, als würden Sie einen Golfschlag ausführen und ein Hole-in-One machen, feiern Sie entsprechend!",
        "Machen Sie das Geräusch von drei Tieren, und Ihr Team muss sie erraten.",
        "Sie und Ihr Team müssen sich nach der Größe ordnen.",
        "Sagen Sie drei Wörter auf Italienisch (keine Zahlen).",
        "Umarmen Sie einen Stuhl.",
        "Geben Sie jeder Person in Ihrem Team einen Rat.",
        "Formen Sie eine Kugel aus etwas und werfen Sie sie auf das andere Team.",
        "Rufen Sie fünf Arten von Take-away-Essen.",
        "Nennen Sie fünf Charaktere aus TV-Sendungen.",
        "Sagen Sie “Roter Laster, Gelber Laster” fünfmal.",
        "Tun Sie so, als wären Sie ein Wassersprenger, aber ohne Wasser.",
        "Kreuzen Sie gleichzeitig alle acht Finger.",
        "Stellen Sie sich vor, Sie schalten jeden Ihrer Teamkollegen nacheinander aus.",
        "Balancieren Sie etwas drei Sekunden lang auf Ihrem Kopf.",
        "Tauschen Sie ein Kleidungsstück mit einem Teamkollegen.",
        "Buchstabieren Sie “Ich bin ein Dummkopf” rückwärts.",
        "Kuscheln Sie sich auf den Schoß eines Teamkollegen und schnurren Sie.",
        "Tauschen Sie die Schuhe mit einem Mitglied Ihres Teams.",
        "Spielen Sie mit einem Teamkollegen Schere-Stein-Papier, bis Sie gewinnen – nicht sprechen.",
        "Schnippen Sie an das Ohrläppchen jedes Teammitglieds (aber nicht zu hart).",
        "Singen Sie ein Lied mit einer Farbe darin.",
        "Knacken Sie Ihre Fingerknöchel.",
        "Lassen Sie das ganze Team drei Sekunden lang eine Aerobic-Bewegung machen.",
        "Machen Sie einen Moonwalk um einen anderen Spieler.",
        "Stellen Sie sich vor, Sie angeln und haben gerade einen großen Fisch gefangen.",
        "Zählen Sie die Zähne in Ihrem Mund.",
        "Werfen Sie eine Münze, bis Sie Kopf haben.",
        "Nennen Sie die Vornamen der Personen in Ihrem Team in alphabetischer Reihenfolge.",
        "Erfinden Sie einen Rap über Ihr Team.",
        "Machen Sie mit dem Rest Ihres Teams dreimal die Welle.",
        "Machen Sie das Geräusch von zwei Instrumenten, Ihr Team muss sie erraten.",
        "Füllen Sie Ihren Mund mit Flüssigkeit und sagen Sie Ihren vollständigen Namen.",
        "Stellen Sie sich vor, Sie halten eine Traube und füttern jeden Ihrer Teamkollegen damit.",
        "Machen Sie ein Rülpsgeräusch (echt oder gefälscht, egal).",
        "Schließen Sie die Augen und tauschen Sie mit einem Teamkollegen die Plätze.",
        "Rollen Sie beide Hosenbeine hoch und rufen Sie “Die Flut kommt!”.",
        "Rufen Sie “Jemand ist in Hundekacke getreten!” und lassen Sie Ihr Team an ihren Schuhen schnuppern.",
        "Machen Sie eine Imitation von jemandem in Ihrem Team, Ihr Team muss raten, wer es ist.",
        "Erfinden Sie den Namen einer Erfindung und beschreiben Sie, was sie tut.",
        "Machen Sie mit einem Spieler einen geheimen Handschlag, der mindestens drei Sekunden dauert.",
        "Trommeln Sie einen Rhythmus auf den Tisch und lassen Sie Ihre Teamkollegen mitmachen.",
        "Tun Sie so, als würden Sie in einen Keller gehen.",
        "Sie und Ihre Teamkollegen müssen die Augen schließen und die Zeigefinger berühren.",
        "Sagen Sie “Ich bin Batman”. Nacheinander müssen Ihre Teamkollegen “Ich bin Batman” sagen, jeder in einer tieferen Stimme.",
        "Heulen Sie zum Mond. Ihr Team muss alle zurückheulen.",
        "Klatschen Sie drei Sekunden lang mit einer Ihrer Hände und einer Hand Ihres Teamkollegen.",
        "Rufen Sie drei Dinge auf der Speisekarte von McDonald’s.",
        "Rufen Sie drei Dinge, die Sie zu Weihnachten hassen würden.",
        "Nennen Sie drei berühmte Menschen mit Bart.",
        "Tanzen Sie drei Sekunden lang langsam mit einem Teamkollegen.",
        "Rufen Sie ein Wort. Jedes Teammitglied muss es mit einem neuen Wort reimen.",
        "Rufen Sie ein Tier aus, das jedem in Ihrem Team ähnlich sieht.",
        "Stehen Sie auf und lassen Sie sich von einem Teamkollegen wie einen Baum fällen; Sie müssen “Timber!” rufen, während Sie fallen.",
        "Kriechen Sie unter den Tisch und summen Sie das Thema von “Der Weiße Hai”.",
        "Rufen Sie zwei Film-Spoiler.",
        "Ihr Team muss die Farbe Ihrer Unterwäsche erraten.",
        "Zeigen Sie auf drei Gegenstände, die weniger als einen Dollar kosten.",
        `Stehen Sie auf und spielen Sie die Bongos auf dem Kopf eines Ihrer Teamkollegen.`,
        `Rufen Sie drei Dinge, die Sie niemals essen sollten.`,
        `Spielen Sie “Ich sehe was, was du nicht siehst” mit Ihrem Team. Sie müssen das Objekt erraten.`,
        `Rufen Sie drei Dinge, die sich auf Ihren Vornamen reimen.`,
        `Summen Sie ein TV-Thema. Lassen Sie Ihr Team raten, welches es ist.`,
        `Rufen Sie vier Dinge, die mit dem Buchstaben “Q” beginnen.`,
        `Rufen Sie drei Dinge, die mit dem Buchstaben “B” beginnen.`,
        `Machen Sie einen Daumen-Krieg mit Ihrem Teamkollegen.`,
        `Zeigen Sie auf jeden Ihrer Teamkollegen und sagen Sie ihre Namen leicht falsch.`,
        `Tun Sie so, als wären Sie eine Uhr und zeigen Sie fünf vor zwei mit Ihren Armen an.`,
        `Werfen und fangen Sie etwas mit derselben Hand.`,
        `Wie viele Monate haben 28 Tage?`,
        `Welcher Buchstabe im Alphabet ist “T”?`,
        `Legen Sie sich auf den Boden und machen Sie einen Krabben-Eindruck.`,
        `Rufen Sie drei Spitznamen für sich selbst.`,
        `Rufen Sie fünf Beläge, die man auf einem Burger haben könnte.`,
        `Rufen Sie drei Palindrome.`,
        `Lassen Sie Ihre Teamkollegen den Namen einer Tanzbewegung erfinden. Sie müssen sie machen.`,
        `Nennen Sie fünf Charaktere aus Büchern.`,
        `Machen Sie drei Sekunden lang ein Pupsgeräusch auf Ihrem Arm.`,
        `Was wiegt mehr? Ein Kilogramm Federn oder ein Kilogramm Ziegelsteine?`,
        `Springen Sie über etwas.`,
        `Machen Sie die Macarena.`,
        `Balancieren Sie drei Dinge übereinander.`,
        `Pfeifen Sie “Zum Geburtstag viel Glück”.`,
        `Sagen Sie “Hallo” in drei Fremdsprachen.`,
        `Rufen Sie drei verschiedene Kaffeesorten.`,
        `Spielen Sie drei Sekunden lang ein intensives imaginäres Gitarrensolo.`,
        `Bewegen Sie sich drei Sekunden lang wie ein Roboter.`,
        `Summen Sie Ihr Lieblingslied. Lassen Sie Ihre Teamkollegen raten, was es ist.`,
        `Holen Sie sich zwei Personen und führen Sie eine Trauungszeremonie für sie durch.`,
        `Rufen Sie ein Wort mit drei Vokalen aus.`,
        `Beschreiben Sie Ihren idealen Partner in drei Worten.`,
        `Finden Sie ein Gesicht auf einem unbelebten Objekt im Raum.`,
        `Tun Sie so, als hätten Sie eine Fernbedienung. Richten Sie sie auf Ihr Team, drücken Sie auf Vorspulen und Pause.`,
        `Zeigen Sie auf die größte Person in Ihrem Team und rufen Sie: “Wie ist das Wetter da oben?”`,
        `Schwingen Sie einen Arm im Uhrzeigersinn und den anderen gegen den Uhrzeigersinn gleichzeitig.`,
        `Ziehen Sie ein Kleidungsstück aus und wickeln Sie es um Ihren Kopf.`,
        `Rufen Sie den Namen Ihrer bevorstehenden Autobiografie aus.`,
        `Klatschen Sie fünfmal Ihre Ellbogen zusammen.`,
        `Nennen Sie fünf Länder, die mit dem Buchstaben “C” beginnen.`,
        `Empfehlen Sie drei Bücher für den Raum.`,
        `Legen Sie sich auf den Boden und tun Sie so, als wären Sie ein Stück Speck, das in der Pfanne brutzelt.`,
        `Tun Sie so, als würden Sie einschlafen und anfangen zu schnarchen. Alle in Ihrem Team müssen auch einschlafen.`,
        `Reiben Sie Ihren Bauch und klopfen Sie gleichzeitig drei Sekunden lang auf Ihren Kopf.`,
        `Rufen Sie drei Wörter. Ihr Team muss das Gegenteil rufen.`,
        `Addieren Sie die Schuhgrößen aller in Ihrem Team.`,
        `Sagen Sie die Wochentage in umgekehrter Reihenfolge auf.`,
        `Rufen Sie fünf Dinge, die kleiner sind als eine Maus.`,
        `Rufen Sie fünf Milchshake-Geschmacksrichtungen.`,
        `Sagen Sie drei französische Wörter (keine Zahlen).`,
        `Zeigen Sie auf drei Objekte, die grün sind.`,
        `Singen Sie ein Lied mit einem Tier darin.`,
        'Zähle bis 10 wie ein Höhlenmensch.',
    ],
    it: [
        "Grida 3 frutti che iniziano con la lettera P.",
        "Stringi la mano a un compagno di squadra. Entrambi dovete fingere di prendere una scossa elettrica.",
        "Inventa un detto profondo e racconta le parole sagge al tuo team.",
        "Quanto fa 55 meno 29?",
        "Nomina cinque persone famose della storia.",
        "Di’ tre numeri che si leggono allo stesso modo al contrario.",
        "Fingi di fare un tiro di golf e segnare un “hole-in-one”, festeggia di conseguenza!",
        "Fai il suono di tre animali e fai indovinare al tuo team di quali si tratta.",
        "Tu e il tuo team dovete mettervi in ordine di altezza.",
        "Di’ tre parole in spagnolo (che non siano numeri).",
        "Abbraccia una sedia.",
        "Dai un consiglio a ogni persona del tuo team.",
        "Fai una palla con qualcosa e lanciala all’altro team.",
        "Grida cinque tipi di cibo da asporto.",
        "Nomina cinque personaggi delle serie TV.",
        "Di’ “Camion rosso, camion giallo” cinque volte.",
        "Fingi di essere un irrigatore, ma senza acqua.",
        "Incrocia tutte e otto le dita delle mani allo stesso tempo.",
        "Fingi di spegnere ogni tuo compagno di squadra uno alla volta.",
        "Metti qualcosa in equilibrio sulla tua testa per tre secondi.",
        "Scambia un capo d’abbigliamento con un compagno di squadra.",
        "Scrivi “Sono un manichino” al contrario.",
        "Accoccolati sulle ginocchia di un compagno di squadra e fai le fusa.",
        "Scambia le scarpe con un membro del tuo team.",
        "Gioca a “sasso, carta, forbici” con un compagno di squadra finché non vinci - senza parlare.",
        "Tocca il lobo dell’orecchio di tutti nel tuo team (ma non troppo forte).",
        "Canta una canzone che contenga un colore.",
        "Schiocca le dita.",
        "Fai fare a tutto il team un movimento di aerobica per tre secondi.",
        "Fai il “moonwalk” intorno a un altro giocatore.",
        "Fingi di pescare e di aver appena preso un grosso pesce.",
        "Conta i denti nella tua bocca.",
        "Lancia una moneta finché non ottieni testa.",
        "Di’ i nomi delle persone del tuo team in ordine alfabetico.",
        "Inventa un rap sul tuo team.",
        "Fai l’onda con il resto del team per tre volte.",
        "Fai il suono di due strumenti, il tuo team deve indovinarli.",
        "Riempi la bocca di liquido e di’ il tuo nome completo.",
        "Fingi di tenere un grappolo d’uva e dai da mangiare a ciascuno dei tuoi compagni di squadra.",
        "Fai un rumore di rutto (vero o falso, va bene).",
        "Chiudi gli occhi e scambia i posti con un compagno di squadra.",
        "Alza entrambe le gambe dei pantaloni e grida “la marea sta salendo”.",
        "Grida “qualcuno ha pestato la cacca di cane” e fai annusare le scarpe al tuo team.",
        "Fai un’imitazione di qualcuno del tuo team; il tuo team deve indovinare chi è.",
        "Inventa il nome di un’invenzione e descrivi a cosa serve.",
        "Crea una stretta di mano segreta con un giocatore che duri almeno tre secondi.",
        "Suona un ritmo sul tavolo e fai in modo che i tuoi compagni si uniscano.",
        "Fingi di scendere in un seminterrato.",
        "Tu e i tuoi compagni dovete chiudere gli occhi e toccare i polpastrelli degli indici.",
        "Di’ “Sono Batman”. A turno, i tuoi compagni devono dire “Sono Batman”, ciascuno con una voce più bassa.",
        "Ulula alla luna. Tutto il tuo team deve ululare di rimando.",
        "Batti le mani per tre secondi usando una delle tue mani e una del tuo compagno.",
        "Grida tre cose del menù di McDonald’s.",
        "Grida tre cose che odierebbe ricevere per Natale.",
        "Nomina tre persone famose con la barba.",
        "Balla lentamente con un compagno di squadra per tre secondi.",
        "Grida una parola. Ogni membro del tuo team deve rimerla con una nuova parola.",
        "Grida un animale simile a ogni persona del tuo team.",
        "Alzati e fai tagliare un compagno come un albero; devi gridare “Albero!” mentre cadi.",
        "Mettiti sotto il tavolo e canticchia il tema di “Lo Squalo”.",
        "Grida due spoiler di film.",
        "Il tuo team deve indovinare il colore della tua biancheria intima.",
        "Indica tre oggetti che valgono meno di un dollaro.",
        `Alzati e suona i bonghi sulla testa di uno dei tuoi compagni di squadra.`,
        `Grida tre cose che non dovresti mai mangiare.`,
        `Gioca a “Vedo, vedo” con la tua squadra. Devono indovinare l’oggetto.`,
        `Grida tre cose che fanno rima con il tuo nome.`,
        `Canticchia una sigla televisiva. Fai indovinare alla tua squadra quale sia.`,
        `Grida quattro cose che iniziano con la lettera “Q”.`,
        `Grida tre cose che iniziano con la lettera “B”.`,
        `Fai una battaglia di pollici con il tuo compagno di squadra.`,
        `Indica ciascuno dei tuoi compagni di squadra e pronuncia i loro nomi in modo leggermente sbagliato.`,
        `Fai finta di essere un orologio e usa le tue braccia per segnare l’una e cinquantacinque.`,
        `Lancia e afferra qualcosa con la stessa mano.`,
        `Quanti mesi hanno 28 giorni?`,
        `Qual è la posizione della lettera “T” nell’alfabeto?`,
        `Mettiti sul pavimento e fai l’imitazione di un granchio.`,
        `Grida tre soprannomi per te stesso.`,
        `Grida cinque condimenti che potresti mettere su un hamburger.`,
        `Grida tre palindromi.`,
        `Fai inventare ai tuoi compagni di squadra il nome di un passo di danza. Devi farlo.`,
        `Nomina cinque personaggi dei libri.`,
        `Fai un rumore di scoreggia sul tuo braccio per tre secondi.`,
        `Quale pesa di più? Un chilo di piume o un chilo di mattoni?`,
        `Salta sopra qualcosa.`,
        `Fai la Macarena.`,
        `Bilancia tre oggetti uno sopra l’altro.`,
        `Fischia tutta “Tanti auguri a te”.`,
        `Di’ “Ciao” in tre lingue straniere.`,
        `Grida tre bevande al caffè diverse.`,
        `Suona un assolo di chitarra immaginario intenso per tre secondi.`,
        `Muoviti come un robot per tre secondi.`,
        `Canticchia la tua canzone preferita. Fai indovinare alla tua squadra quale sia.`,
        `Prendi due persone e celebra un matrimonio per loro.`,
        `Grida una parola con tre vocali.`,
        `Descrivi il tuo partner ideale in tre parole.`,
        `Trova un volto su un oggetto inanimato nella stanza.`,
        `Fingi di avere un telecomando. Puntalo verso la tua squadra, premi “avanti veloce” e poi “pausa”.`,
        `Indica la persona più alta della tua squadra e grida “com’è il tempo lassù?”`,
        `Fai girare un braccio in senso orario e l’altro in senso antiorario allo stesso tempo.`,
        `Togliti un capo d’abbigliamento e avvolgilo intorno alla testa.`,
        `Grida il titolo della tua prossima autobiografia.`,
        `Batti i gomiti insieme cinque volte.`,
        `Elenca cinque paesi che iniziano con la lettera “C”.`,
        `Consiglia tre libri a chi è nella stanza.`,
        `Sdraiati sul pavimento e fai finta di essere una fetta di pancetta che sfrigola in una padella.`,
        `Fai finta di addormentarti e inizia a russare. Tutti nella tua squadra devono addormentarsi anche loro.`,
        `Strofina lo stomaco e batti la testa contemporaneamente per tre secondi.`,
        `Grida tre parole. La tua squadra deve gridare il contrario.`,
        `Somma le taglie delle scarpe di tutti nella tua squadra.`,
        `Recita i giorni della settimana al contrario.`,
        `Grida cinque cose più piccole di un topo.`,
        `Grida cinque gusti di milkshake.`,
        `Di’ tre parole in francese (che non siano numeri).`,
        `Indica tre oggetti che sono verdi.`,
        `Canta una canzone con un animale.`,
        'Conta fino a 10 come un cavernicolo.',
    ],
    pt: [
        "Grite 3 frutas que começam com a letra P.",
        "Aperte a mão de um colega de equipe. Ambos devem fingir receber um choque elétrico.",
        "Invente um ditado profundo e conte as palavras sábias à sua equipe.",
        "Quanto é 55 menos 29?",
        "Diga os nomes de cinco pessoas famosas da história.",
        "Fale três números que se lêem da mesma forma de cabeça para baixo.",
        "Finja fazer uma tacada de golfe e acertar um “hole-in-one”, comemore como merece!",
        "Imite o som de três animais e faça com que sua equipe adivinhe quais são.",
        "Você e sua equipe devem se organizar por altura.",
        "Diga três palavras em italiano (que não sejam números).",
        "Abrace uma cadeira.",
        "Dê um conselho a cada pessoa da sua equipe.",
        "Faça uma bola com algo e jogue-a no outro time.",
        "Grite cinco tipos de comida para viagem.",
        "Diga os nomes de cinco personagens de programas de TV.",
        "Diga “Caminhão vermelho, Caminhão amarelo” cinco vezes.",
        "Finja ser um aspersor de água, mas sem água.",
        "Cruze todos os oito dedos das mãos ao mesmo tempo.",
        "Finja desligar cada um de seus colegas de equipe, um por um.",
        "Equilibre algo na sua cabeça por três segundos.",
        "Troque uma peça de roupa com um colega de equipe.",
        "Soletre “Eu sou um idiota” ao contrário.",
        "Aconchegue-se no colo de um colega e ronrone.",
        "Troque os sapatos com um membro da sua equipe.",
        "Jogue “pedra, papel ou tesoura” com um colega até ganhar - sem falar.",
        "Toque o lóbulo da orelha de todos na sua equipe (mas não muito forte).",
        "Cante uma música com uma cor.",
        "Estale os dedos.",
        "Faça todo o seu time fazer um movimento de aeróbica por três segundos.",
        "Faça o “moonwalk” ao redor de outro jogador.",
        "Finja estar pescando e pegar um peixe grande.",
        "Conte os dentes da sua boca.",
        "Jogue uma moeda até sair cara.",
        "Diga os primeiros nomes das pessoas do seu time em ordem alfabética.",
        "Invente um rap sobre o seu time.",
        "Faça a onda com o resto do time três vezes.",
        "Imite o som de dois instrumentos; seu time deve adivinhar quais são.",
        "Encha a boca com líquido e diga seu nome completo.",
        "Finja segurar um cacho de uvas e alimente cada um de seus colegas com uma.",
        "Faça um som de arroto (real ou falso, tanto faz).",
        "Feche os olhos e troque de lugar com um colega.",
        "Enrole as pernas da calça e grite “a maré está subindo”.",
        "Grite “alguém pisou em cocô de cachorro” e faça sua equipe cheirar os sapatos.",
        "Faça uma imitação de alguém da sua equipe; eles devem adivinhar quem é.",
        "Invente o nome de uma invenção e descreva o que ela faz.",
        "Faça um aperto de mão secreto com um jogador que dure pelo menos três segundos.",
        "Toque um ritmo na mesa e faça seus colegas se juntarem.",
        "Finja entrar em um porão.",
        "Você e seus colegas devem fechar os olhos e tocar os dedos indicadores.",
        "Diga “Eu sou o Batman”. Por sua vez, seus colegas devem dizer “Eu sou o Batman”, cada um dizendo em um tom mais baixo.",
        "Uive para a lua. Toda a sua equipe deve uivar de volta.",
        "Bata palmas por três segundos usando uma das suas mãos e uma de um colega.",
        "Grite três itens do cardápio do McDonald’s.",
        "Grite três coisas que você odiaria ganhar no Natal.",
        "Nomeie três pessoas famosas com barba.",
        "Dance devagar com um colega de equipe por três segundos.",
        "Grite uma palavra. Cada membro da sua equipe deve rimá-la com uma nova palavra.",
        "Grite um animal semelhante a cada pessoa do seu time.",
        "Fique de pé e peça a um colega que o derrube como uma árvore; você deve gritar “Árvore!” enquanto cai.",
        "Entre embaixo da mesa e hum o tema do filme “Tubarão”.",
        "Grite dois spoilers de filmes.",
        "Sua equipe tem que adivinhar a cor da sua roupa íntima.",
        "Aponte três itens que custam menos de um dólar.",
        `Fique de pé e toque os bongôs na cabeça de um dos seus colegas de equipe.`,
        `Grite três coisas que você nunca deve comer.`,
        `Jogue “Eu vejo” com sua equipe. Eles devem adivinhar o objeto.`,
        `Grite três coisas que rimam com seu nome.`,
        `Canteolar um tema de TV. Faça sua equipe adivinhar qual é.`,
        `Grite quatro coisas que começam com a letra “Q”.`,
        `Grite três coisas que começam com a letra “B”.`,
        `Faça uma guerra de polegares com seu colega de equipe.`,
        `Aponte para cada um dos seus colegas de equipe e diga seus nomes um pouco errado.`,
        `Finja ser um relógio e use os braços para mostrar uma hora e cinquenta e cinco minutos.`,
        `Jogue e pegue algo com a mesma mão.`,
        `Quantos meses têm 28 dias?`,
        `Qual o número da letra “T” no alfabeto?`,
        `Deite-se no chão e faça uma impressão de caranguejo.`,
        `Grite três apelidos para você mesmo.`,
        `Grite cinco coberturas que você pode colocar em um hambúrguer.`,
        `Grite três palíndromos.`,
        `Peça aos seus colegas de equipe para inventarem o nome de um movimento de dança. Você deve fazê-lo.`,
        `Nomeie cinco personagens de livros.`,
        `Faça um barulho de peido no seu braço por três segundos.`,
        `O que pesa mais? Um quilo de penas ou um quilo de tijolos?`,
        `Pule sobre algo.`,
        `Faça a Macarena.`,
        `Equilibre três coisas umas sobre as outras.`,
        `Assobie “Parabéns pra Você” inteira.`,
        `Diga “Olá” em três línguas estrangeiras.`,
        `Grite três tipos diferentes de café.`,
        `Faça um solo imaginário de guitarra por três segundos.`,
        `Movimente-se como um robô por três segundos.`,
        `Canteole sua música favorita. Faça sua equipe adivinhar qual é.`,
        `Pegue duas pessoas e faça uma cerimônia de casamento para elas.`,
        `Grite uma palavra com três vogais.`,
        `Descreva seu parceiro ideal em três palavras.`,
        `Encontre um rosto em um objeto inanimado na sala.`,
        `Finja que tem um controle remoto. Aponte para a sua equipe, pressione avançar rápido e pause.`,
        `Aponte para a pessoa mais alta da sua equipe e grite “como está o tempo aí em cima?”`,
        `Gire um braço no sentido horário e o outro no sentido anti-horário ao mesmo tempo.`,
        `Tire uma peça de roupa e a envolva na sua cabeça.`,
        `Grite o nome da sua futura autobiografia.`,
        `Bata os cotovelos cinco vezes.`,
        `Liste cinco países que começam com a letra “C”.`,
        `Recomende três livros para a sala.`,
        `Deite-se no chão e finja ser um pedaço de bacon fritando na panela.`,
        `Finja que está dormindo e comece a roncar. Todos na sua equipe devem dormir também.`,
        `Esfregue a barriga e bata na cabeça ao mesmo tempo por três segundos.`,
        `Grite três palavras. Sua equipe deve gritar o oposto.`,
        `Soma o tamanho do sapato de todos na sua equipe.`,
        `Recite os dias da semana na ordem inversa.`,
        `Grite cinco coisas menores que um rato.`,
        `Grite cinco sabores de milkshake.`,
        `Diga três palavras em francês (que não sejam números).`,
        `Aponte para três objetos que são verdes.`,
        `Cante uma música com um animal nela.`,
        'Conte até 10 como um homem das cavernas.',
    ],
    ru: [
        "Крикните 3 фрукта, начинающихся с буквы П.",
        "Пожмите руку товарищу по команде. Оба должны притвориться, что получили электрический разряд.",
        "Придумайте глубокую пословицу и расскажите своей команде мудрые слова.",
        "Сколько будет 55 минус 29?",
        "Назовите пять известных людей из истории.",
        "Назовите три числа, которые читаются одинаково вверх ногами.",
        "Сделайте вид, что бьете мяч в гольфе и попали с первого удара, отпразднуйте это соответственно!",
        "Изобразите звуки трех животных, и пусть ваша команда угадает их.",
        "Вы и ваша команда должны выстроиться в порядке роста.",
        "Скажите три слова на итальянском (не цифры).",
        "Обнимите стул.",
        "Дайте совет каждому члену своей команды.",
        "Скатайте что-то в шар и бросьте в другую команду.",
        "Назовите пять видов еды на вынос.",
        "Назовите пять персонажей из телевизионных шоу.",
        "Скажите “Красный грузовик, желтый грузовик” пять раз.",
        "Притворитесь водным распылителем, но без воды.",
        "Скрестите все восемь пальцев одновременно.",
        "Сделайте вид, что выключаете каждого члена своей команды по очереди.",
        "Удерживайте что-то на своей голове в течение трех секунд.",
        "Поменяйтесь предметом одежды с товарищем по команде.",
        "Произнесите “Я глупец” задом наперед.",
        "Свернитесь калачиком на коленях товарища по команде и замурлыкайте.",
        "Поменяйтесь обувью с членом вашей команды.",
        "Играйте с товарищем в “камень, ножницы, бумага”, пока не выиграете – без разговоров.",
        "Щелкните по мочке уха каждого в вашей команде (но не слишком сильно).",
        "Спойте песню, в которой есть цвет.",
        "Хрустните пальцами.",
        "Пусть вся ваша команда выполнит аэробное движение в течение трех секунд.",
        "Выполните лунную походку вокруг другого игрока.",
        "Притворитесь, что вы ловите рыбу, и вы только что поймали большую.",
        "Посчитайте зубы во рту.",
        "Подбрасывайте монету, пока не выпадет орел.",
        "Назовите имена членов вашей команды в алфавитном порядке.",
        "Придумайте рэп о своей команде.",
        "Сделайте “волну” с остальной частью команды три раза.",
        "Изобразите звуки двух инструментов, ваша команда должна угадать их.",
        "Наберите в рот жидкости и произнесите свое полное имя.",
        "Притворитесь, что держите гроздь винограда, и накормите каждого члена вашей команды.",
        "Издайте звук отрыжки (настоящий или фальшивый – не важно).",
        "Закройте глаза и поменяйтесь местами с товарищем по команде.",
        "Подкатайте штанины и крикните: “Прилив приближается!”",
        "Крикните “кто-то наступил на собачье дерьмо” и заставьте свою команду понюхать обувь.",
        "Изобразите кого-то из своей команды, ваша команда должна угадать, кто это.",
        "Придумайте название изобретения и опишите, что оно делает.",
        "Придумайте секретное рукопожатие с игроком, которое длится не менее трех секунд.",
        "Постучите ритм по столу и пригласите свою команду присоединиться.",
        "Притворитесь, что спускаетесь в подвал.",
        "Вы и ваша команда должны закрыть глаза и прикоснуться кончиками указательных пальцев.",
        "Скажите “Я - Бэтмен”. По очереди ваши товарищи должны сказать “Я - Бэтмен”, каждый раз понижая голос.",
        "Войте на луну. Вся ваша команда должна завыть в ответ.",
        "Хлопайте три секунды, используя одну из своих рук и руку товарища по команде.",
        "Назовите три блюда из меню McDonald’s.",
        "Назовите три вещи, которые вы ненавидите получать на Рождество.",
        "Назовите трех знаменитых людей с бородой.",
        "Медленно потанцуйте с товарищем по команде в течение трех секунд.",
        "Крикните слово. Каждый член вашей команды должен придумать рифму к нему.",
        "Назовите животное, похожее на каждого члена вашей команды.",
        "Встаньте и попросите товарища по команде срубить вас, как дерево; вы должны крикнуть “Лесоруб!” когда падаете.",
        "Заберитесь под стол и напойте тему из “Челюсти”.",
        "Крикните два спойлера к фильмам.",
        "Ваша команда должна угадать цвет вашего нижнего белья.",
        "Укажите на три предмета, которые стоят меньше одного доллара.",
        `Встаньте и играйте на бонго на голове одного из ваших товарищей по команде.`,
        `Крикните три вещи, которые никогда не стоит есть.`,
        `Поиграйте в “Я шпионю” с вашей командой. Они должны угадать предмет.`,
        `Крикните три слова, рифмующихся с вашим именем.`,
        `Напойте тему из телешоу. Пусть ваша команда угадает, что это.`,
        `Крикните четыре слова, начинающихся с буквы “Q”.`,
        `Крикните три слова, начинающихся с буквы “B”.`,
        `Устройте борьбу пальцами с вашим товарищем по команде.`,
        `Укажите на каждого из ваших товарищей по команде и слегка неправильно произнесите их имена.`,
        `Притворитесь, что вы часы, и используйте руки, чтобы показать без пяти минут два.`,
        `Бросьте и поймайте что-то одной и той же рукой.`,
        `Сколько месяцев имеет 28 дней?`,
        `Какая буква по номеру “Т” в алфавите?`,
        `Лягте на пол и изобразите краба.`,
        `Крикните три прозвища для себя.`,
        `Крикните пять начинок, которые можно положить в бургер.`,
        `Крикните три палиндрома.`,
        `Пусть ваша команда придумает название танцевального движения. Вы должны его исполнить.`,
        `Назовите пять персонажей из книг.`,
        `Издавайте звук пука на вашей руке в течение трех секунд.`,
        `Что тяжелее: килограмм перьев или килограмм кирпичей?`,
        `Перепрыгните через что-то.`,
        `Сделайте макарену.`,
        `Сбалансируйте три вещи одну на другой.`,
        `Просвистите всю песню “С днем рождения”.`,
        `Скажите “Привет” на трех иностранных языках.`,
        `Крикните три разных вида кофе.`,
        `Исполните интенсивное воображаемое соло на гитаре в течение трех секунд.`,
        `Двигайтесь, как робот, в течение трех секунд.`,
        `Напойте свою любимую песню. Пусть ваша команда угадает, что это.`,
        `Проведите свадебную церемонию для двух человек.`,
        `Крикните слово с тремя гласными.`,
        `Опишите своего идеального партнера тремя словами.`,
        `Найдите лицо на неодушевленном предмете в комнате.`,
        `Притворитесь, что у вас есть пульт. Укажите им на свою команду, нажмите на перемотку и паузу.`,
        `Укажите на самого высокого человека в вашей команде и крикните: “Как там погода наверху?”`,
        `Раскручивайте одну руку по часовой стрелке, а другую против часовой стрелки одновременно.`,
        `Снимите предмет одежды и оберните его вокруг головы.`,
        `Крикните название своей будущей автобиографии.`,
        `Пять раз хлопните локтями вместе.`,
        `Назовите пять стран, начинающихся с буквы “C”.`,
        `Порекомендуйте три книги для комнаты.`,
        `Лягте на пол и притворитесь куском бекона, шипящего на сковороде.`,
        `Притворитесь, что засыпаете, и начните храпеть. Вся ваша команда тоже должна уснуть.`,
        `Потрите живот и похлопайте по голове одновременно в течение трех секунд.`,
        `Крикните три слова. Ваша команда должна выкрикнуть противоположное.`,
        `Сложите размеры обуви всех членов вашей команды.`,
        `Перечислите дни недели в обратном порядке.`,
        `Крикните пять вещей, которые меньше мыши.`,
        `Крикните пять вкусов молочных коктейлей.`,
        `Скажите три французских слова (не числа).`,
        `Укажите на три объекта зеленого цвета.`,
        `Спойте песню с животным в ней.`,
        'Посчитай до 10, как пещерный человек.',
    ],
};