export const translator = {
    es: {
        errorOccurred: 'Se ha producido un error...',
        start: 'Iniciar',
        playAgain: 'Jugar de nuevo',
        resume: 'Reanudar',
        redTeamWins: '¡Equipo Rojo gana!',
        blueTeamWins: '¡Equipo Azul gana!',
        pause: 'Pausa',
        completeChallenges: '¡Completa emocionantes desafíos y no dejes que se acabe el tiempo de tu equipo!',
        settings: 'Configuración',
        initialTime: 'Tiempo inicial',
        language: 'Idioma',
        setParticipantsNames: 'Establecer nombres de los participantes',
        clear: 'Borrar',
        done: 'Hecho',
        blueTeam: 'Equipo Azul',
        redTeam: 'Equipo Rojo',
        addParticipantsNames: 'Añade los nombres de los participantes separados por una coma (ej. Santiago, Emma, etc.)',
    },
    en: {
        errorOccurred: 'An error has occurred...',
        start: 'Start',
        playAgain: 'Play Again',
        resume: 'Resume',
        redTeamWins: 'Red Team Wins!',
        blueTeamWins: 'Blue Team Wins!',
        pause: 'Pause',
        completeChallenges: 'Complete wild challenges and don’t let your team’s time run out!',
        settings: 'Settings',
        initialTime: 'Initial time',
        language: 'Language',
        setParticipantsNames: 'Set participant\'s names',
        clear: 'Clear',
        done: 'Done',
        blueTeam: 'Blue Team',
        redTeam: 'Red Team',
        addParticipantsNames: 'Add the names of the participants separated by a comma (e.g. Santiago, Emma, etc.)',
    },
    fr: {
        errorOccurred: 'Une erreur s\'est produite...',
        start: 'Démarrer',
        playAgain: 'Rejouer',
        resume: 'Reprendre',
        redTeamWins: 'L\'équipe Rouge gagne!',
        blueTeamWins: "L'équipe Bleue gagne!",
        pause: 'Pause',
        completeChallenges: 'Relevez des défis passionnants et ne laissez pas le temps de votre équipe s’écouler !',
        settings: 'Paramètres',
        initialTime: 'Temps initial',
        language: 'Langue',
        setParticipantsNames: 'Définir les noms des participants',
        clear: 'Effacer',
        done: 'Fait',
        blueTeam: 'Équipe Bleue',
        redTeam: 'Équipe Rouge',
        addParticipantsNames: 'Ajoutez les noms des participants séparés par une virgule (ex. Santiago, Emma, etc.)',
    },
    de: {
        errorOccurred: 'Ein Fehler ist aufgetreten...',
        start: 'Starten',
        playAgain: 'Nochmal spielen',
        resume: 'Fortsetzen',
        redTeamWins: 'Das Rote Team gewinnt!',
        blueTeamWins: 'Das Blaue Team gewinnt!',
        pause: 'Pause',
        completeChallenges: 'Meistern Sie spannende Herausforderungen und lassen Sie die Zeit Ihres Teams nicht ablaufen!',
        settings: 'Einstellungen',
        initialTime: 'Startzeit',
        language: 'Sprache',
        setParticipantsNames: 'Namen der Teilnehmer festlegen',
        clear: 'Löschen',
        done: 'Fertig',
        blueTeam: 'Blaues Team',
        redTeam: 'Rotes Team',
        addParticipantsNames: 'Fügen Sie die Namen der Teilnehmer durch ein Komma getrennt hinzu (z. B. Santiago, Emma, etc.)',
    },
    it: {
        errorOccurred: 'Si è verificato un errore...',
        start: 'Inizio',
        playAgain: 'Gioca di nuovo',
        resume: 'Riprendi',
        redTeamWins: 'La Squadra Rossa vince!',
        blueTeamWins: 'La Squadra Blu vince!',
        pause: 'Pausa',
        completeChallenges: 'Completa sfide emozionanti e non lasciare che il tempo della tua squadra si esaurisca!',
        settings: 'Impostazioni',
        initialTime: 'Tempo iniziale',
        language: 'Lingua',
        setParticipantsNames: 'Imposta i nomi dei partecipanti',
        clear: 'Cancella',
        done: 'Fatto',
        blueTeam: 'Squadra Blu',
        redTeam: 'Squadra Rossa',
        addParticipantsNames: 'Aggiungi i nomi dei partecipanti separati da una virgola (es. Santiago, Emma, ecc.)',
    },
    pt: {
        errorOccurred: 'Ocorreu um erro…',
        start: 'Iniciar',
        playAgain: 'Jogar novamente',
        resume: 'Retomar',
        redTeamWins: 'Equipe Vermelha vence!',
        blueTeamWins: 'Equipe Azul vence!',
        pause: 'Pausar',
        completeChallenges: 'Complete desafios emocionantes e não deixe o tempo da sua equipe acabar!',
        settings: 'Configurações',
        initialTime: 'Tempo inicial',
        language: 'Idioma',
        setParticipantsNames: 'Definir nomes dos participantes',
        clear: 'Limpar',
        done: 'Feito',
        blueTeam: 'Equipe Azul',
        redTeam: 'Equipe Vermelha',
        addParticipantsNames: 'Adicione os nomes dos participantes separados por uma vírgula (ex. Santiago, Emma, etc.)',
    },
    ru: {
        errorOccurred: 'Произошла ошибка...',
        start: 'Начать',
        playAgain: 'Играть снова',
        resume: 'Продолжить',
        redTeamWins: 'Победила Красная команда!',
        blueTeamWins: 'Победила Синяя команда!',
        pause: 'Пауза',
        completeChallenges: 'Выполняйте увлекательные задания и не дайте времени вашей команды истечь!',
        settings: 'Настройки',
        initialTime: 'Начальное время',
        language: 'Язык',
        setParticipantsNames: 'Установить имена участников',
        clear: 'Очистить',
        done: 'Готово',
        blueTeam: 'Синяя команда',
        redTeam: 'Красная команда',
        addParticipantsNames: 'Добавьте имена участников, разделенные запятой (например, Сантьяго, Эмма и т. д.)',
    },
};