export const translator = {
    es: {
        errorOccurred: 'Se ha producido un error...',
        start: 'Inicio',
        playAgain: 'Jugar de nuevo',
        resume: 'Reanudar',
        redTeamWins: '¡Equipo Rojo gana!',
        blueTeamWins: '¡Equipo Azul gana!',
        pause: 'Pausa',
    },
    en: {
        errorOccurred: 'An error has occurred...',
        start: 'Start',
        playAgain: 'Play Again',
        resume: 'Resume',
        redTeamWins: 'Red Team Wins!',
        blueTeamWins: 'Blue Team Wins!',
        pause: 'Pause',
    },
    fr: {
        errorOccurred: 'Une erreur s\'est produite...',
        start: 'Démarrer',
        playAgain: 'Rejouer',
        resume: 'Reprendre',
        redTeamWins: 'L\'équipe Rouge gagne!',
        blueTeamWins: "L'équipe Bleue gagne!",
        pause: 'Pause',
    },
    de: {
        errorOccurred: 'Ein Fehler ist aufgetreten...',
        start: 'Starten',
        playAgain: 'Nochmal spielen',
        resume: 'Fortsetzen',
        redTeamWins: 'Das Rote Team gewinnt!',
        blueTeamWins: 'Das Blaue Team gewinnt!',
        pause: 'Pause',
    },
    it: {
        errorOccurred: 'Si è verificato un errore...',
        start: 'Inizio',
        playAgain: 'Gioca di nuovo',
        resume: 'Riprendi',
        redTeamWins: 'La Squadra Rossa vince!',
        blueTeamWins: 'La Squadra Blu vince!',
        pause: 'Pausa',
    },
    pt: {
        errorOccurred: 'Ocorreu um erro…',
        start: 'Iniciar',
        playAgain: 'Jogar novamente',
        resume: 'Retomar',
        redTeamWins: 'Equipe Vermelha vence!',
        blueTeamWins: 'Equipe Azul vence!',
        pause: 'Pausar',
    },
    ru: {
        errorOccurred: 'Произошла ошибка...',
        start: 'Начать',
        playAgain: 'Играть снова',
        resume: 'Продолжить',
        redTeamWins: 'Победила Красная команда!',
        blueTeamWins: 'Победила Синяя команда!',
        pause: 'Пауза',
    },
};