export const translator = {
    en: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        language: 'Language',
        homepage: "Homepage",
        unitedStatesFlag: 'United States\' Flag',
        spanishFlag: 'Spanish Flag',
        siteNavigation: 'Site Navigation',
        darkMode: 'Dark Mode',
        home: 'Home',
        getInTouch: 'Get In Touch',
        socialMedia: 'Social Media',
        contactUs: 'Contact Us',
        myAccount: 'My Account',
        image: 'Image',
        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        refundPolicy: 'Refund and Cancellations Policy',
        refundsAndCancellations: 'Refunds and Cancellations',
        nextImage: 'Next Image',
        previousImage: 'Previous Image',
        close: 'Close',
        email: "Email",
        phoneNumber: "Phone Number",
        yourMessage: "Your Message",
        attachment: "Add an attachment",
        subscribeToNewsletter: "Subscribe to our newsletter",
        preferredContactMethod: "Preferred Contact Method",
        contactInformation: "Contact Information",
        preferToReachOut: "If you prefer to reach out directly, here is our contact information:",
        visitOurOffice: "Visit Our Office",
        comeAndVisit: "Come and visit our office located at:",
        leaveYourReview: 'Leave Your Review',
        writeYourReview: 'Write your review',
        submit: 'Submit',
        searchPlaceholder: 'Search...',

        catalog: 'Catalog',
        ourWork: 'Our Work',
        
        homeDescription: "",

        catalogSlogan: "Gear Up, Stand Out, Ride On.",
        discount: "off",
        addToCart: "Add to Cart",
    },
    es: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        language: 'Idioma',
        homepage: "Página de Inicio",
        unitedStatesFlag: 'Bandera de los Estados Unidos',
        spanishFlag: 'Bandera Española',
        siteNavigation: 'Navegación del Sitio',
        darkMode: 'Modo Oscuro',        
        home: 'Inicio',
        getInTouch: 'Ponte en Contacto',
        socialMedia: 'Redes Sociales',
        myAccount: 'Mi Cuenta',
        contactUs: 'Contáctanos',
        image: 'Imagen',
        termsOfService: 'Términos de Servicio',
        privacyPolicy: 'Política de Privacidad',
        refundPolicy: 'Política de Reembolso y Cancelaciones',
        refundsAndCancellations: 'Reembolsos y Cancelaciones',
        nextImage: 'Ver Imagen Siguiente',
        previousImage: 'Ver Imagen Previa',
        close: 'Cerrar',
        email: "Correo Electrónico",
        phoneNumber: "Número de Teléfono",
        yourMessage: "Tu Mensaje",
        attachment: "Añadir un adjunto",
        subscribeToNewsletter: "Suscríbete a nuestro boletín",
        preferredContactMethod: "Método de Contacto Preferido",
        contactInformation: "Información de Contacto",
        preferToReachOut: "Si prefieres comunicarte directamente, aquí está nuestra información de contacto:",
        visitOurOffice: "Visita Nuestra Oficina",
        comeAndVisit: "Ven y visita nuestra oficina ubicada en:",
        leaveYourReview: 'Deja tu Reseña',
        writeYourReview: 'Escribe tu reseña',
        submit: 'Enviar',
        searchPlaceholder: 'Buscar...',

        catalog: 'Catálogo',
        ourWork: 'Nuestro trabajo',

        homeDescription: "",

        catalogSlogan: "Viste para Impresionar, Pedalea para Triunfar.",
        discount: "de descuento",
        addToCart: "Añadir al carrito",
    },
};