export const translator = {
    es: {
        santiagoOvallesProjects: "Proyectos de Santiago Ovalles",
        attorneyCollaborativeOnlineService: "Servicio en Línea Colaborativo para Abogados",
        intranet: "Intranet de Canto Legal",
        backoffice: "Clapp Back Office - Características Menores",
        clappForms: "Formularios Clapp",
        pdfEditor: "Editor PDF",
        ticTacToe: "Tres en línea",
        profileCards: "Tarjetas de Perfil",
        sketch: "Bosquejo",
        comingSoon: 'Próximamente',
    },
    en: {
        santiagoOvallesProjects: "Santiago Ovalles' Projects",
        attorneyCollaborativeOnlineService: "Attorney's Collaborative Online Service",
        intranet: "Canto Legal Intranet",
        backoffice: "Clapp Back Office - Minor features",
        clappForms: "Clapp Forms",
        pdfEditor: "PDF Editor",
        ticTacToe: "Tic-tac-toe",
        profileCards: "Profile Cards",
        sketch: "Sketch",
        comingSoon: 'Coming Soon',
    },
    fr: {
        santiagoOvallesProjects: "Projets de Santiago Ovalles",
        attorneyCollaborativeOnlineService: "Service Collaboratif en Ligne pour Avocats",
        intranet: "Intranet de Canto Legal",
        backoffice: "Clapp Back Office - Fonctionnalités Mineures",
        clappForms: "Formulaires Clapp",
        pdfEditor: "Éditeur PDF",
        ticTacToe: "Morpion",
        profileCards: "Cartes de Profil",
        sketch: "Croquis",
        comingSoon: 'Prochainement',
    },
    de: {
        santiagoOvallesProjects: "Santiago Ovalles Projekte",
        attorneyCollaborativeOnlineService: "Kollaborativer Online-Dienst für Anwälte",
        intranet: "Canto Legal Intranet",
        backoffice: "Clapp Back Office - Kleinere Funktionen",
        clappForms: "Clapp Forms",
        pdfEditor: "PDF-Editor",
        ticTacToe: "Tic-tac-toe",
        profileCards: "Profilkarten",
        sketch: "Skizze",
        comingSoon: 'Demnächst',
    },
    it: {
        santiagoOvallesProjects: "Progetti di Santiago Ovalles",
        attorneyCollaborativeOnlineService: "Servizio Online Collaborativo per Avvocati",
        intranet: "Intranet di Canto Legal",
        backoffice: "Clapp Back Office - Funzionalità Minori",
        clappForms: "Moduli Clapp",
        pdfEditor: "Editor PDF",
        ticTacToe: "Tris",
        profileCards: "Carte del Profilo",
        sketch: "Schizzo",
        comingSoon: 'Prossimamente',
    },
    ru: {
        santiagoOvallesProjects: "Проекты Сантьяго Овальеса",
        attorneyCollaborativeOnlineService: "Совместный онлайн-сервис адвокатов",
        intranet: "Внутренняя сеть Canto Legal",
        backoffice: "Clapp Back Office - Мелкие функции",
        clappForms: "Формы Clapp",
        pdfEditor: "Редактор PDF",
        ticTacToe: "Крестики-нолики",
        profileCards: "Профильные карты",
        sketch: "Эскиз",
        comingSoon: 'Скоро',
    },
};