export const translator = {
    es: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Proyectos de Santiago Ovalles",
        intranet: "Intranet de Canto Legal",
        backoffice: "Clapp Back Office - Características Menores",
        clappForms: "Formularios Clapp",
        pdfEditor: "Editor PDF",
        ticTacToe: "Tres en línea",
        profileCards: "Tarjetas de Perfil",
        sketch: "Bosquejo",
        comingSoon: 'Próximamente',
        charades: 'Charadas',
        photoOfSantiago: 'Foto de Santiago',
        helloImSantiago: 'Hola. Soy Santiago. Aquí encontrarás algunos de mis proyectos web, bosquejos e ideas. Si quieres contactarme, por favor envíame un correo electrónico a:',
        description_journee: 'Necesitaba un lugar para almacenar mis pensamientos e ideas, organizar mis tareas y hacer lo que quisiera. Journée es mi espacio personal para la creatividad y la organización.',
        description_eb2: 'Un sitio diseñado para personas que buscan una Visa EB2 en Estados Unidos. Ofrece una herramienta para contactar a Canto Legal y ayuda a organizar eficientemente los datos de solicitudes de visa.',
        description_rada: 'Una plataforma de comercio electrónico para RADA Cycling Wear, que permite a los clientes comprar productos de manera fácil y segura o solicitar ropa de ciclismo personalizada.',
        description_subito: 'Un pequeño juego para disfrutar con mi familia, basado en "20 Second Showdown" de Big Potato Games. Dos equipos compiten para completar tareas lo más rápido posible.',
        description_ccs: 'Un proyecto para la empresa colombiana "CCS Guitars" para mostrar sus guitarras especializadas. El sitio web también presenta la historia de la empresa y sus detalles de contacto.',
        description_legalcollab: 'Un sitio web creado como proyecto final una clase de universidad. "Imagina un grupo de seis abogados que desean ofrecer asesoría legal accesible y te contactan para que construyas su sitio web."',
        description_intranet: 'La Intranet de Canto Legal. Un recurso para que los empleados encuentren información de la empresa, se comuniquen entre sí y organicen eventos internos.',
        description_destype: 'Una plataforma para mejorar habilidades de mecanografía. Así fue como aprendí a escribir sin mirar el teclado y finalmente logré aumentar mi productividad escribiendo más de 80 palabras por minuto.',
        description_threlte: 'Una escena espeluznante en un jardín con un fantasma. Este proyecto fue una experiencia de aprendizaje en Three.js, Blender y WebGL. Muchos de los elementos de la escena son interactivos.',
        description_clappforms: 'Una plataforma para crear formularios personalizables. Las respuestas pueden organizarse y analizarse utilizando gráficos y estadísticas. Hecho en una época cuando me atrevía a crear sitios web solo con Vanilla JS...',
        description_ovaliza: 'Un sitio de comercio electrónico para Ovaliza, una empresa dominicana especializada en piezas de autos usados. Los clientes pueden explorar el catálogo de productos y acceder a servicios especializados.',
        description_descalendar: 'Mi primer sitio web, diseñado para ayudar a las personas a gestionar sus calendarios fácilmente. Los usuarios pueden programar y administrar citas con otros sin problemas.',
        description_deschat: 'Un bosquejo de un servicio de mensajería donde los usuarios pueden chatear mediante texto, imágenes y archivos. La plataforma permite el envío de mensajes directos utilizando números de teléfono.',
        description_pdfeditor: 'Esta versión carga un Formulario G-28, permitiendo que los administradores asignen valores a los campos y los rellenen automáticamente con datos de los clientes.',
        description_profilecards: 'Un sitio que muestra tarjetas de empleados con detalles sobre días de trabajo, vacaciones y más. También ofrece evaluaciones usando un formulario de Clapp Forms.',
    },
    en: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Santiago Ovalles' Projects",
        intranet: "Canto Legal Intranet",
        backoffice: "Clapp Back Office - Minor features",
        clappForms: "Clapp Forms",
        pdfEditor: "PDF Editor",
        ticTacToe: "Tic-tac-toe",
        profileCards: "Profile Cards",
        sketch: "Sketch",
        comingSoon: 'Coming Soon',
        charades: 'Charades',
        photoOfSantiago: 'Photo of Santiago',
        helloImSantiago: 'Hello. I\'m Santiago. Here you\'ll find some of my web projects, sketches, and ideas. If you want to contact me, please send me an email at:',
        description_journee: 'I needed a place to store my thoughts and ideas, organize my tasks, and do whatever I want. Journée is my personal playground for creativity and organization.',
        description_eb2: 'A site designed for individuals seeking an EB2 Visa in the United States. It offers a tool to contact Canto Legal and helps organize visa application data efficiently.',
        description_rada: 'An e-commerce platform for RADA Cycling Wear, allowing customers to easily and securely purchase products or request custom cycling gear.',
        description_subito: 'A small game to enjoy with my family, based on "20 Second Showdown" by Big Potato Games. Two teams compete to complete tasks as fast as possible.',
        description_ccs: 'A project for the Colombian company "CCS Guitars" to showcase their specialized guitars. The website also features the company’s history and contact details.',
        description_legalcollab: 'A website created as a final project for university. "Imagine a group of six lawyers aiming to offer accessible legal advice contacts you to build their site."',
        description_intranet: 'Canto Legal\'s Intranet. A resource for employees to find company information, communicate with each other, and organize internal events.',
        description_destype: 'A platform for improving typing skills. It’s how I learned touch-typing and finally managed to increase my productivity by being able to write more than 80 words per minute.',
        description_threlte: 'A haunting scene in a garden with a ghost. This project was a learning experience in Three.js, Blender, and WebGL. Many scene elements are interactive.',
        description_clappforms: 'A platform for creating customizable forms. Responses can be organized and analyzed using graphs and statistics. Back when I dared to create websites using only Vanilla JS...',
        description_ovaliza: 'An e-commerce website for Ovaliza, a Dominican company specializing in used car parts. Customers can browse the product catalog and access specialized services.',
        description_descalendar: 'My first website, designed to help people manage their calendars easily. Users can schedule and manage appointments with others seamlessly.',
        description_deschat: 'A sketch for a messaging service where users can chat via text, images, and files. The platform allows direct messaging using phone numbers.',
        description_pdfeditor: 'A sketch for a larger project. This version loads a Form G-28, allowing administrators to assign values to fields and auto-fill them with client data.',
        description_profilecards: 'A site displaying employee cards with details on workdays, vacation days, and more. It also enables evaluation using a form powered by Clapp Forms.',
    },
    fr: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Projets de Santiago Ovalles",
        intranet: "Intranet de Canto Legal",
        backoffice: "Clapp Back Office - Fonctionnalités Mineures",
        clappForms: "Formulaires Clapp",
        pdfEditor: "Éditeur PDF",
        ticTacToe: "Morpion",
        profileCards: "Cartes de Profil",
        sketch: "Croquis",
        comingSoon: 'Prochainement',
        charades: 'Charades',
        photoOfSantiago: 'Photo de Santiago',
        helloImSantiago: 'Bonjour. Je suis Santiago. Ici, vous trouverez certains de mes projets web, esquisses et idées. Si vous souhaitez me contacter, veuillez m\'envoyer un e-mail à :',
        description_journee: 'J\'avais besoin d\'un endroit pour stocker mes pensées et idées, organiser mes tâches et faire ce que je voulais. Journée est mon terrain de jeu personnel pour la créativité et l\'organisation.',
        description_eb2: 'Un site conçu pour les personnes cherchant à obtenir un visa EB2 aux États-Unis. Il offre un outil pour contacter Canto Legal et aide à organiser efficacement les données de la demande de visa.',
        description_rada: 'Une plateforme de commerce en ligne pour RADA Cycling Wear, permettant aux clients d\'acheter facilement et en toute sécurité des produits ou de demander des équipements de cyclisme personnalisés.',
        description_subito: 'Un petit jeu à apprécier en famille, basé sur "20 Second Showdown" de Big Potato Games. Deux équipes s\'affrontent pour accomplir des tâches le plus rapidement possible.',
        description_ccs: 'Un projet pour l\'entreprise colombienne "CCS Guitars" afin de présenter leurs guitares spécialisées. Le site Web présente également l\'histoire de l\'entreprise et ses coordonnées.',
        description_legalcollab: 'Un site Web créé comme projet final d\'université. "Imaginez un groupe de six avocats cherchant à offrir des conseils juridiques accessibles vous contactant pour créer leur site."',
        description_intranet: 'L\'Intranet de Canto Legal. Une ressource pour les employés afin de trouver des informations sur l\'entreprise, communiquer entre eux et organiser des événements internes.',
        description_destype: 'Une plateforme pour améliorer les compétences en dactylographie. C\'est ainsi que j\'ai appris à taper à l\'aveugle et que j\'ai enfin réussi à augmenter ma productivité en écrivant plus de 80 mots par minute.',
        description_threlte: 'Une scène hantée dans un jardin avec un fantôme. Ce projet était une expérience d\'apprentissage sur Three.js, Blender et WebGL. De nombreux éléments de la scène sont interactifs.',
        description_clappforms: 'Une plateforme pour créer des formulaires personnalisables. Les réponses peuvent être organisées et analysées à l\'aide de graphiques et de statistiques. À l\'époque où j\'osais créer des sites Web uniquement avec Vanilla JS...',
        description_ovaliza: 'Un site e-commerce pour Ovaliza, une entreprise dominicaine spécialisée dans les pièces détachées de voitures d\'occasion. Les clients peuvent parcourir le catalogue de produits et accéder à des services spécialisés.',
        description_descalendar: 'Mon premier site Web, conçu pour aider les gens à gérer facilement leurs calendriers. Les utilisateurs peuvent planifier et gérer des rendez-vous avec d\'autres de manière transparente.',
        description_deschat: 'Un croquis pour un service de messagerie où les utilisateurs peuvent discuter par texte, images et fichiers. La plateforme permet la messagerie directe en utilisant des numéros de téléphone.',
        description_pdfeditor: 'Un croquis pour un projet plus vaste. Cette version charge un formulaire G-28, permettant aux administrateurs d\'attribuer des valeurs aux champs et de les remplir automatiquement avec les données des clients.',
        description_profilecards: 'Un site affichant des cartes d\'employés avec des détails sur les jours de travail, les jours de congé, et plus. Il permet également l\'évaluation via un formulaire alimenté par Clapp Forms.',
    },
    de: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Santiago Ovalles Projekte",
        intranet: "Canto Legal Intranet",
        backoffice: "Clapp Back Office - Kleinere Funktionen",
        clappForms: "Clapp Forms",
        pdfEditor: "PDF-Editor",
        ticTacToe: "Tic-tac-toe",
        profileCards: "Profilkarten",
        sketch: "Skizze",
        comingSoon: 'Demnächst',
        charades: 'Scharade',
        photoOfSantiago: 'Foto von Santiago',
        helloImSantiago: 'Hallo. Ich bin Santiago. Hier findest du einige meiner Webprojekte, Skizzen und Ideen. Wenn du mich kontaktieren möchtest, sende mir bitte eine E-Mail an:',
        description_journee: 'Ich brauchte einen Ort, um meine Gedanken und Ideen zu speichern, meine Aufgaben zu organisieren und zu tun, was ich wollte. Journée ist mein persönlicher Spielplatz für Kreativität und Organisation.',
        description_eb2: 'Eine Seite für Personen, die ein EB2-Visum in den USA suchen. Sie bietet ein Tool, um Canto Legal zu kontaktieren, und hilft, Visumantragsdaten effizient zu organisieren.',
        description_rada: 'Eine E-Commerce-Plattform für RADA Cycling Wear, die es Kunden ermöglicht, Produkte einfach und sicher zu kaufen oder maßgeschneiderte Radkleidung zu bestellen.',
        description_subito: 'Ein kleines Spiel, das ich mit meiner Familie genieße, basierend auf "20 Second Showdown" von Big Potato Games. Zwei Teams treten an, um Aufgaben so schnell wie möglich zu erledigen.',
        description_ccs: 'Ein Projekt für die kolumbianische Firma "CCS Guitars", um ihre spezialisierten Gitarren zu präsentieren. Die Website enthält auch die Geschichte des Unternehmens und Kontaktinformationen.',
        description_legalcollab: 'Eine Website, die als Abschlussprojekt an der Universität erstellt wurde. "Stellen Sie sich eine Gruppe von sechs Anwälten vor, die erschwingliche Rechtsberatung anbieten möchten und Sie kontaktieren, um ihre Website zu erstellen."',
        description_intranet: 'Das Intranet von Canto Legal. Eine Ressource für Mitarbeiter, um Firmeninformationen zu finden, miteinander zu kommunizieren und interne Veranstaltungen zu organisieren.',
        description_destype: 'Eine Plattform zur Verbesserung der Schreibfähigkeiten. So habe ich gelernt, blind zu tippen, und es geschafft, meine Produktivität zu steigern, indem ich mehr als 80 Wörter pro Minute schrieb.',
        description_threlte: 'Eine gruselige Szene in einem Garten mit einem Geist. Dieses Projekt war eine Lernerfahrung in Three.js, Blender und WebGL. Viele der Szenenelemente sind interaktiv.',
        description_clappforms: 'Eine Plattform zum Erstellen von anpassbaren Formularen. Antworten können mithilfe von Diagrammen und Statistiken organisiert und analysiert werden. Damals, als ich es wagte, Websites nur mit Vanilla JS zu erstellen...',
        description_ovaliza: 'Eine E-Commerce-Website für Ovaliza, ein dominikanisches Unternehmen, das sich auf gebrauchte Autoteile spezialisiert hat. Kunden können den Produktkatalog durchsuchen und auf spezialisierte Dienstleistungen zugreifen.',
        description_descalendar: 'Meine erste Website, die Menschen dabei hilft, ihre Kalender einfach zu verwalten. Benutzer können problemlos Termine mit anderen planen und verwalten.',
        description_deschat: 'Ein Entwurf für einen Messaging-Dienst, bei dem Benutzer über Text, Bilder und Dateien chatten können. Die Plattform ermöglicht direkte Nachrichten über Telefonnummern.',
        description_pdfeditor: 'Ein Entwurf für ein größeres Projekt. Diese Version lädt ein G-28-Formular und ermöglicht Administratoren, Felder mit Werten zu belegen und sie automatisch mit Kundendaten auszufüllen.',
        description_profilecards: 'Eine Website, die Mitarbeiterkarten mit Details zu Arbeitstagen, Urlaubstagen und mehr anzeigt. Sie ermöglicht auch Bewertungen mithilfe eines Formulars von Clapp Forms.',
    },
    it: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Progetti di Santiago Ovalles",
        intranet: "Intranet di Canto Legal",
        backoffice: "Clapp Back Office - Funzionalità Minori",
        clappForms: "Moduli Clapp",
        pdfEditor: "Editor PDF",
        ticTacToe: "Tris",
        profileCards: "Carte del Profilo",
        sketch: "Schizzo",
        comingSoon: 'Prossimamente',
        charades: 'Mimo',
        photoOfSantiago: 'Foto di Santiago',
        helloImSantiago: 'Ciao. Sono Santiago. Qui troverai alcuni dei miei progetti web, schizzi e idee. Se vuoi contattarmi, inviami una email a:',
        description_journee: 'Avevo bisogno di un posto dove conservare i miei pensieri e idee, organizzare i miei compiti e fare ciò che volevo. Journée è il mio parco giochi personale per la creatività e l\'organizzazione.',
        description_eb2: 'Un sito progettato per individui che cercano un visto EB2 negli Stati Uniti. Offre uno strumento per contattare Canto Legal e aiuta a organizzare i dati della domanda di visto in modo efficiente.',
        description_rada: 'Una piattaforma e-commerce per RADA Cycling Wear, che consente ai clienti di acquistare prodotti facilmente e in sicurezza o richiedere abbigliamento da ciclismo personalizzato.',
        description_subito: 'Un piccolo gioco da godere con la mia famiglia, basato su "20 Second Showdown" di Big Potato Games. Due squadre competono per completare le sfide il più velocemente possibile.',
        description_ccs: 'Un progetto per la compagnia colombiana "CCS Guitars" per mostrare le loro chitarre specializzate. Il sito presenta anche la storia dell\'azienda e i dettagli di contatto.',
        description_legalcollab: 'Un sito Web creato come progetto finale all\'università. "Immagina un gruppo di sei avvocati che mirano a offrire consulenze legali accessibili e ti contattano per costruire il loro sito."',
        description_intranet: 'L\'Intranet di Canto Legal. Una risorsa per i dipendenti per trovare informazioni aziendali, comunicare tra loro e organizzare eventi interni.',
        description_destype: 'Una piattaforma per migliorare le abilità di battitura. È così che ho imparato a scrivere alla cieca e finalmente sono riuscito a migliorare la mia produttività scrivendo più di 80 parole al minuto.',
        description_threlte: 'Una scena inquietante in un giardino con un fantasma. Questo progetto è stata un\'esperienza di apprendimento su Three.js, Blender e WebGL. Molti degli elementi della scena sono interattivi.',
        description_clappforms: 'Una piattaforma per creare moduli personalizzabili. Le risposte possono essere organizzate e analizzate utilizzando grafici e statistiche. Quando osavo creare siti Web solo con Vanilla JS...',
        description_ovaliza: 'Un sito di e-commerce per Ovaliza, un\'azienda dominicana specializzata in pezzi di ricambio per auto usate. I clienti possono sfogliare il catalogo dei prodotti e accedere a servizi specializzati.',
        description_descalendar: 'Il mio primo sito web, progettato per aiutare le persone a gestire facilmente i propri calendari. Gli utenti possono pianificare e gestire appuntamenti con altri senza problemi.',
        description_deschat: 'Uno schizzo per un servizio di messaggistica in cui gli utenti possono chattare tramite testo, immagini e file. La piattaforma consente la messaggistica diretta utilizzando numeri di telefono.',
        description_pdfeditor: 'Uno schizzo per un progetto più grande. Questa versione carica un modulo G-28, consentendo agli amministratori di assegnare valori ai campi e di compilarli automaticamente con i dati dei clienti.',
        description_profilecards: 'Un sito che mostra schede dei dipendenti con dettagli su giorni lavorativi, giorni di ferie e altro. Consente inoltre la valutazione tramite un modulo gestito da Clapp Forms.',
    },
    pr: {
        santiagoOvalles: "Santiago Ovalles",
        santiagoOvallesProjects: "Projetos de Santiago Ovalles",
        intranet: "Intranet Canto Legal",
        backoffice: "Clapp Back Office - Funcionalidades Menores",
        clappForms: "Formulários Clapp",
        pdfEditor: "Editor de PDF",
        ticTacToe: "Jogo da Velha",
        profileCards: "Cartões de Perfil",
        sketch: "Esboço",
        comingSoon: 'Em Breve',
        charades: 'Charadas',
        photoOfSantiago: 'Foto de Santiago',
        helloImSantiago: 'Olá. Sou Santiago. Aqui você encontrará alguns dos meus projetos web, esboços e ideias. Se quiser me contatar, por favor envie um e-mail para:',
        description_journee: 'Precisava de um lugar para armazenar meus pensamentos e ideias, organizar minhas tarefas e fazer o que eu quisesse. Journée é meu playground pessoal para criatividade e organização.',
        description_eb2: 'Um site projetado para indivíduos que procuram um visto EB2 nos Estados Unidos. Oferece uma ferramenta para entrar em contato com a Canto Legal e ajuda a organizar os dados da aplicação do visto de forma eficiente.',
        description_rada: 'Uma plataforma de e-commerce para a RADA Cycling Wear, permitindo que os clientes comprem produtos com facilidade e segurança ou solicitem equipamentos de ciclismo personalizados.',
        description_subito: 'Um pequeno jogo para aproveitar com a minha família, baseado em "20 Second Showdown" da Big Potato Games. Duas equipes competem para completar tarefas o mais rápido possível.',
        description_ccs: 'Um projeto para a empresa colombiana "CCS Guitars" para exibir suas guitarras especializadas. O site também apresenta a história da empresa e detalhes de contato.',
        description_legalcollab: 'Um site criado como projeto final na universidade. "Imagine um grupo de seis advogados que desejam oferecer consultoria jurídica acessível e entram em contato com você para construir o site deles."',
        description_intranet: 'O Intranet da Canto Legal. Um recurso para os funcionários encontrarem informações da empresa, se comunicarem entre si e organizarem eventos internos.',
        description_destype: 'Uma plataforma para melhorar as habilidades de digitação. Foi assim que aprendi a digitar sem olhar para o teclado e finalmente consegui aumentar minha produtividade escrevendo mais de 80 palavras por minuto.',
        description_threlte: 'Uma cena assombrada em um jardim com um fantasma. Este projeto foi uma experiência de aprendizado em Three.js, Blender e WebGL. Muitos elementos da cena são interativos.',
        description_clappforms: 'Uma plataforma para criar formulários personalizáveis. As respostas podem ser organizadas e analisadas usando gráficos e estatísticas. Na época em que me atrevi a criar sites usando apenas Vanilla JS...',
        description_ovaliza: 'Um site de e-commerce para Ovaliza, uma empresa dominicana especializada em peças de carros usados. Os clientes podem navegar pelo catálogo de produtos e acessar serviços especializados.',
        description_descalendar: 'Meu primeiro site, projetado para ajudar as pessoas a gerenciar seus calendários com facilidade. Os usuários podem agendar e gerenciar compromissos com outras pessoas sem problemas.',
        description_deschat: 'Um esboço de um serviço de mensagens onde os usuários podem conversar via texto, imagens e arquivos. A plataforma permite o envio de mensagens diretas usando números de telefone.',
        description_pdfeditor: 'Um esboço para um projeto maior. Esta versão carrega um Formulário G-28, permitindo que administradores atribuam valores aos campos e os preencham automaticamente com os dados do cliente.',
        description_profilecards: 'Um site que exibe cartões de funcionários com detalhes sobre dias de trabalho, dias de férias e muito mais. Ele também permite avaliações usando um formulário fornecido pelo Clapp Forms.',
    },
    ru: {
        santiagoOvalles: "Сантьяго Овальеса",
        santiagoOvallesProjects: "Проекты Сантьяго Овальеса",
        intranet: "Внутренняя сеть Canto Legal",
        backoffice: "Clapp Back Office - Мелкие функции",
        clappForms: "Формы Clapp",
        pdfEditor: "Редактор PDF",
        ticTacToe: "Крестики-нолики",
        profileCards: "Профильные карты",
        sketch: "Эскиз",
        comingSoon: 'Скоро',
        charades: 'Шарады',
        photoOfSantiago: 'Фото Сантьяго',
        helloImSantiago: 'Привет. Я Сантьяго. Здесь вы найдете некоторые из моих веб-проектов, набросков и идей. Если хотите связаться со мной, отправьте мне письмо на почту:',
        description_journee: 'Мне нужно было место, чтобы хранить свои мысли и идеи, организовать свои задачи и делать все, что я хочу. Journée — это моя личная площадка для творчества и организации.',
        description_eb2: 'Сайт, предназначенный для людей, ищущих визу EB2 в США. Он предлагает инструмент для связи с Canto Legal и помогает эффективно организовать данные по заявке на визу.',
        description_rada: 'Платформа электронной коммерции для RADA Cycling Wear, позволяющая клиентам легко и безопасно приобретать товары или заказывать индивидуальную велоодежду.',
        description_subito: 'Небольшая игра, чтобы повеселиться с моей семьей, основанная на "20 Second Showdown" от Big Potato Games. Две команды соревнуются, чтобы выполнить задачи как можно быстрее.',
        description_ccs: 'Проект для колумбийской компании "CCS Guitars" по демонстрации их специализированных гитар. Сайт также содержит историю компании и контактную информацию.',
        description_legalcollab: 'Сайт, созданный как финальный проект для университета. "Представьте группу из шести юристов, желающих предложить доступные юридические консультации, и они связываются с вами, чтобы создать свой сайт."',
        description_intranet: 'Интранет Canto Legal. Ресурс для сотрудников, чтобы находить информацию о компании, общаться друг с другом и организовывать внутренние мероприятия.',
        description_destype: 'Платформа для улучшения навыков набора текста. Так я научился набирать вслепую и, наконец, смог повысить свою продуктивность, набирая более 80 слов в минуту.',
        description_threlte: 'Зловещая сцена в саду с призраком. Этот проект был учебным опытом в Three.js, Blender и WebGL. Многие элементы сцены интерактивны.',
        description_clappforms: 'Платформа для создания настраиваемых форм. Ответы можно организовать и анализировать с помощью графиков и статистики. Это было в те времена, когда я осмелился создавать сайты только на чистом JavaScript...',
        description_ovaliza: 'Сайт электронной коммерции для Ovaliza, доминиканской компании, специализирующейся на запчастях для подержанных автомобилей. Клиенты могут просматривать каталог товаров и получать доступ к специализированным услугам.',
        description_descalendar: 'Мой первый сайт, созданный для того, чтобы помочь людям легко управлять своими календарями. Пользователи могут легко назначать и управлять встречами с другими.',
        description_deschat: 'Эскиз мессенджера, где пользователи могут общаться через текст, изображения и файлы. Платформа позволяет отправлять сообщения напрямую, используя телефонные номера.',
        description_pdfeditor: 'Эскиз для более крупного проекта. Эта версия загружает форму G-28, позволяя администраторам назначать значения полям и автоматически заполнять их данными клиента.',
        description_profilecards: 'Сайт, на котором отображаются карточки сотрудников с данными о рабочих днях, днях отпуска и многом другом. Также позволяет проводить оценку с использованием формы, управляемой Clapp Forms.',
    },
};