export const translator = {
    en: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        language: 'Language',
        homepage: "Homepage",
        attorneyCollaborativeOnlineService: "Attorney's Collaborative Online Service",
        unitedStatesFlag: 'United States\' Flag',
        spanishFlag: 'Spanish Flag',
        darkMode: 'Dark Mode',
        home: 'Home',
        aboutUs: 'About Us',
        legalResources: 'Legal Resources',
        getInTouch: 'Get In Touch',
        socialMedia: 'Social Media',
        clientPortal: 'Client Portal',
        ourTeam: 'Our Team',
        ourServices: 'Our Services',
        testimonials: 'Testimonials',
        pricing: 'Pricing',
        faq: 'FAQ',
        blog: 'Blog',
        externalLegalResources: 'External Legal Resources',
        legalDisclaimersAndPolicies: 'Legal Disclaimers And Policies',
        contactUs: 'Contact Us',
        joinOurTeam: 'Join Our Team',
        siteMap: 'Sitemap',
        siteNavigation: 'Site Navigation',
        image: 'Image',
        divorceProceedings: 'Divorce Proceedings',
        custodyProceedings: 'Custody Proceedings',
        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        dataProtection: 'Data Protection',
        refundPolicy: 'Refund Policy',
        lawyersImageDescription: 'Two lawyers, dressed in professional attire, are standing inside a courtroom. They are engaged in a handshake, symbolizing mutual agreement or the conclusion of legal proceedings.',
        legalCollabTeam: 'LegalCollab\'s Team.',
        lawyerThumbsUpImageDescription: 'Lawyer giving a thumbs up to the camera while speaking on the phone.',
        lawyerHelpingClientImageDescription: 'A lawyer helping a client in a courtroom.',
        nextImage: 'Next Image',
        carouselOneDescription: 'A lawyer in Court.',
        carouselTwoDescription: 'Three team members.',
        carouselThreeDescription: 'LegalCollab\'s team on a video meeting.',
        carouselFourDescription: 'Three team members.',
        needHelp: 'Need Help?',
        onlineChat: 'Online Chat',
        onlineMeeting: 'Online Meeting',
        close: 'Close',
        haveADoubt: 'Do you have a doubt? We\'re here for you!',
        sendUsAMessage: 'Send us a message',
        frequentlyAskedQuestions: 'Frequently Asked Questions',
        scheduleAMeeting: 'Schedule a Meeting',
        connectWithOurExperts: 'Connect with Our Experts through a personalized online meeting with our legal team. Discuss your case, ask questions, and get tailored advice from the comfort of your home.',
        homeDescription: 'Affordable online legal assistance for divorce and custody proceedings.',
        empoweringYourLegalJourney: 'Empowering Your Legal Journey Through Expert Guidance.',
        exploreOurServices: 'Explore Our Services',
        legalAssistance: 'Legal Assistance',
        navigateDivorce: 'Navigate divorce and custody proceedings with personalized legal assistance. Our team of experienced attorneys is committed to guiding you through every step of the process.',
        discoverOurServices: 'Discover Our Services',
        haveQuestions: 'Have questions or need personalized support? Connect with us directly. Our team is ready to assist you with any inquiries related to family law.',
        meetOurTeam: 'Meet Our Team',
        discoverOurTeam: 'Discover our team of dedicated attorneys specializing in family law. Learn about their vast experience and unwavering commitment to supporting our clients.',
        meetOurLegalExperts: 'Meet Our Legal Experts',
        decadesOfLegalExpertise: 'Decades of Legal Expertise',
        withDecadesOfExperience: 'With decades of experience, we\'ve successfully handled numerous cases. We understand the intricacies of family law, ensuring you receive top-notch legal representation.',
        whatOurClientsSay: 'What Our Clients Have To Say',
        readTestimonials: 'Read testimonials from clients who have benefited from our affordable online legal assistance. Your success story could be next!',
        carrollCounty: 'Carroll County',
        incrediblySupportiveTeam: 'Incredibly supportive team. They made a challenging process much easier.',
        baltimoreCounty: 'Baltimore County',
        exceptionalService: 'Exceptional service. I highly recommend LegalCollab for family law matters.',
        howardCounty: 'Howard County',
        professionalEfficientUnderstanding: 'Professional, efficient, and understanding. Grateful for their expertise.',
        viewMoreTestimonials: 'View more testimonials',
        bestMoments: 'Some of our best moments...',
        ourTeamDescription: "Meet our team of compassionate and skilled attorneys who are ready to champion your cause.",
        callingLegalProfessionals: 'Calling All Legal Professionals!',
        embarkOnJourney: 'Embark on a fulfilling journey with us. Elevate your career, collaborate with experienced professionals, and contribute to meaningful legal assistance.',
        exploreOpportunities: 'Explore Opportunities',
        Brian_Mitchell: "With a passion for family law, Brian Mitchell brings over a decade of experience to LegalCollab. Known for his empathetic approach, Brian is dedicated to helping clients navigate divorce and custody proceedings with understanding and expertise.",
        Alejandro_Rodriguez: "A seasoned attorney with a multicultural perspective, Alejandro Rodríguez is committed to providing legal support tailored to the unique needs of each client. Fluent in Spanish, English, and French, he ensures seamless communication and representation.",
        Emily_Davis: "Emily Davis, a compassionate advocate for family rights, believes in empowering clients during challenging times. Her strategic and thoughtful approach has earned her a reputation for achieving positive outcomes in complex family legal matters.",
        JiYeon_Kim: "Bringing diversity and a wealth of international legal experience, Ji-Yeon Kim is dedicated to helping families find resolution. Her global perspective enriches LegalCollab's approach to handling diverse divorce and custody cases.",
        Rahul_Patel: "Rahul Patel, a meticulous legal mind, excels in handling intricate legal nuances. His commitment to delivering comprehensive legal solutions ensures clients receive top-notch representation throughout the divorce and custody process.",
        Sofia_Lindström: "Sofia Lindström, a dedicated advocate for family rights, brings a Nordic perspective to LegalCollab. Her warm and understanding approach helps clients navigate the legal complexities of divorce and custody with ease.",
        inquiryPrompt: "Do you need a lawyer to help you with divorce or custody proceedings? We are here for you. Contact us!",
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phoneNumber: "Phone Number",
        subject: "Subject",
        category: "Category",
        generalInquiry: "General Inquiry",
        collaborationOpportunity: "Collaboration Opportunity",
        yourMessage: "Your Message",
        attachment: "Attachment",
        subscribeToNewsletter: "Subscribe to our newsletter",
        preferredContactMethod: "Preferred Contact Method",
        submitInquiry: "Submit Inquiry",
        howCanWeAssistYou: "How can we assist you?",
        inquirySubject: "Subject of your inquiry",
        contactInformation: "Contact Information",
        preferToReachOut: "If you prefer to reach out directly, here is our contact information:",
        visitOurOffice: "Visit Our Office",
        comeAndVisit: "Come and visit our office located at:",
        officeLocation: "Office Location",
        workingHours: "Working Hours",
        teamAvailable: "Our team is available to assist you during the following hours:",
        mondayToFriday: "Monday - Friday: 9:00 AM - 5:00 PM",
        weekends: "Weekends: By appointment",
        earlyDevelopmentStage: "This page is in an early development stage.",
        jumpTo: "Jump to what you are looking for",
    },
    es: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        language: 'Idioma',
        homepage: "Página de Inicio",
        attorneyCollaborativeOnlineService: "Servicio en Línea Colaborativo para Abogados",
        unitedStatesFlag: 'Bandera de los Estados Unidos',
        spanishFlag: 'Bandera Española',
        darkMode: 'Modo Oscuro',
        home: 'Inicio',
        aboutUs: 'Acerca de nosotros',
        legalResources: 'Recursos Legales',
        getInTouch: 'Ponte en Contacto',
        socialMedia: 'Redes Sociales',
        clientPortal: 'Portal del Cliente',
        ourTeam: 'Nuestro Equipo',
        ourServices: 'Servicios',
        testimonials: 'Testimonios',
        pricing: 'Precios',
        faq: 'Preguntas Frecuentes',
        blog: 'Blog',
        externalLegalResources: 'Recursos Legales Externos',
        legalDisclaimersAndPolicies: 'Avisos Legales y Políticas',
        contactUs: 'Contáctanos',
        joinOurTeam: 'Únete a Nuestro Equipo',
        siteMap: 'Mapa del sitio',
        siteNavigation: 'Navegación del Sitio',
        image: 'Imagen',
        divorceProceedings: 'Procedimientos de Divorcio',
        custodyProceedings: 'Procedimientos de Custodia',
        termsOfService: 'Términos de Servicio',
        privacyPolicy: 'Política de Privacidad',
        dataProtection: 'Protección de Datos',
        refundPolicy: 'Política de Reembolso',
        lawyersImageDescription: 'Dos abogados, vestidos de manera profesional, están de pie dentro de una sala de audiencias. Se están dando un apretón de manos, simbolizando un acuerdo mutuo o la conclusión de un procedimiento legal.',
        legalCollabTeam: 'El equipo de LegalCollab',
        lawyerThumbsUpImageDescription: 'Abogado dando un pulgar hacia arriba a la cámara mientras habla por teléfono.',
        lawyerHelpingClientImageDescription: 'Un abogado ayudando a un cliente en un tribunal.',
        nextImage: 'Siguiente Imagen',
        carouselOneDescription: 'Una abogada en una corte.',
        carouselTwoDescription: 'Tres miembros del equipo.',
        carouselThreeDescription: 'El equipo de LegalCollab en una videollamada.',
        carouselFourDescription: 'Tres miembros del equipo.',
        needHelp: '¿Necesitas ayuda?',
        onlineChat: 'Chat en línea',
        onlineMeeting: 'Reunión en línea',
        close: 'Cerrar',
        haveADoubt: '¿Tienes alguna duda? ¡Estamos aquí para ayudarte!',
        sendUsAMessage: 'Envíanos un mensaje',
        frequentlyAskedQuestions: 'Preguntas frecuentes',
        scheduleAMeeting: 'Programar una reunión',
        connectWithOurExperts: 'Conéctate con nuestros expertos a través de una reunión en línea personalizada con nuestro equipo legal. Discute tu caso, haz preguntas y recibe asesoramiento desde la comodidad de tu hogar.',
        homeDescription: 'Asistencia legal en línea asequible para procesos de divorcio y custodia.',
        empoweringYourLegalJourney: 'Empoderando tu trayectoria legal mediante orientación experta.',
        exploreOurServices: 'Explora Nuestros Servicios',
        legalAssistance: 'Asistencia Legal',
        navigateDivorce: 'Navega por los procedimientos de divorcio y custodia con asistencia legal personalizada. Nuestro equipo de abogados experimentados se compromete a guiarte en cada paso del proceso.',
        discoverOurServices: 'Descubre Nuestros Servicios',
        haveQuestions: '¿Tienes preguntas o necesitas apoyo personalizado? Conéctate con nosotros directamente. Nuestro equipo está listo para ayudarte con cualquier consulta relacionada con el derecho de familia.',
        meetOurTeam: 'Conoce a Nuestro Equipo',
        discoverOurTeam: 'Descubre nuestro equipo de abogados dedicados especializados en derecho de familia. Conoce su vasta experiencia y su compromiso inquebrantable de apoyar a nuestros clientes.',
        meetOurLegalExperts: 'Conoce a Nuestros Expertos Legales',
        decadesOfLegalExpertise: 'Décadas de Experiencia Legal',
        withDecadesOfExperience: 'Con décadas de experiencia, hemos manejado con éxito numerosos casos. Entendemos las complejidades del derecho de familia, asegurando que recibas una representación legal de primera.',
        whatOurClientsSay: 'Lo Que Dicen Nuestros Clientes',
        readTestimonials: 'Lee testimonios de clientes que se han beneficiado de nuestra asequible asistencia legal en línea. ¡Tu historia de éxito podría ser la próxima!',
        carrollCounty: 'Condado de Carroll',
        incrediblySupportiveTeam: 'Equipo increíblemente solidario. Hicieron un proceso desafiante mucho más fácil.',
        baltimoreCounty: 'Condado de Baltimore',
        exceptionalService: 'Servicio excepcional. Recomiendo altamente LegalCollab para asuntos de derecho de familia.',
        howardCounty: 'Condado de Howard',
        professionalEfficientUnderstanding: 'Profesionales, eficientes y comprensivos. Agradecido por su experiencia.',
        viewMoreTestimonials: 'Ver más testimonios',
        bestMoments: 'Algunos de nuestros mejores momentos...',
        ourTeamDescription: 'Conoce a nuestro equipo de abogados compasivos y hábiles que están listos para defender tu causa.',
        callingLegalProfessionals: '¡Llamando a todos los profesionales del derecho!',
        embarkOnJourney: 'Emprende un viaje gratificante con nosotros. Eleva tu carrera, colabora con profesionales experimentados y contribuye a una asistencia legal significativa.',
        exploreOpportunities: 'Explora Oportunidades',
        Brian_Mitchell: "Con pasión por el derecho de familia, Brian Mitchell aporta más de una década de experiencia a LegalCollab. Conocido por su enfoque empático, Brian se dedica a ayudar a los clientes a navegar por procesos de divorcio y custodia con comprensión y experiencia.",
        Alejandro_Rodriguez: "Un abogado experimentado con una perspectiva multicultural, Alejandro Rodríguez está comprometido a brindar apoyo legal adaptado a las necesidades únicas de cada cliente. Fluido en español, inglés y francés, asegura una comunicación y representación fluidas.",
        Emily_Davis: "Emily Davis, una defensora compasiva de los derechos familiares, cree en capacitar a los clientes durante tiempos desafiantes. Su enfoque estratégico y reflexivo le ha valido una reputación por lograr resultados positivos en asuntos legales familiares complejos.",
        JiYeon_Kim: "Aportando diversidad y una riqueza de experiencia legal internacional, Ji-Yeon Kim se dedica a ayudar a las familias a encontrar resoluciones. Su perspectiva global enriquece el enfoque de LegalCollab para manejar diversos casos de divorcio y custodia.",
        Rahul_Patel: "Rahul Patel, una mente legal meticulosa, sobresale en el manejo de matices legales intrincados. Su compromiso de brindar soluciones legales integrales asegura que los clientes reciban representación de primera clase durante todo el proceso de divorcio y custodia.",
        Sofia_Lindström: "Sofía Lindström, una defensora dedicada de los derechos familiares, aporta una perspectiva nórdica a LegalCollab. Su enfoque cálido y comprensivo ayuda a los clientes a navegar por las complejidades legales del divorcio y la custodia con facilidad.",
        inquiryPrompt: "¿Necesitas un abogado para ayudarte con un divorcio o procedimientos de custodia? Estamos aquí para ti. ¡Contáctanos!",
        firstName: "Nombre",
        lastName: "Apellido",
        email: "Correo Electrónico",
        phoneNumber: "Número de Teléfono",
        subject: "Asunto",
        category: "Categoría",
        generalInquiry: "Consulta General",
        collaborationOpportunity: "Oportunidad de Colaboración",
        yourMessage: "Tu Mensaje",
        attachment: "Adjunto",
        subscribeToNewsletter: "Suscríbete a nuestro boletín",
        preferredContactMethod: "Método de Contacto Preferido",
        submitInquiry: "Enviar Consulta",
        howCanWeAssistYou: "¿Cómo podemos ayudarte?",
        inquirySubject: "Asunto de tu consulta",
        contactInformation: "Información de Contacto",
        preferToReachOut: "Si prefieres comunicarte directamente, aquí está nuestra información de contacto:",
        visitOurOffice: "Visita Nuestra Oficina",
        comeAndVisit: "Ven y visita nuestra oficina ubicada en:",
        officeLocation: "Ubicación de la Oficina",
        workingHours: "Horario de Atención",
        teamAvailable: "Nuestro equipo está disponible para ayudarte durante las siguientes horas:",
        mondayToFriday: "Lunes a Viernes: 9:00 AM - 5:00 PM",
        weekends: "Fines de Semana: Con cita previa",
        earlyDevelopmentStage: "Esta página está en una etapa temprana de desarrollo.",
        jumpTo: "Ir a lo que estás buscando",
    },
};