export const translator = {
    en: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        language: 'Language',
        homepage: "Homepage",
        attorneyCollaborativeOnlineService: "Attorney's Collaborative Online Service",
        unitedStatesFlag: 'United States\' Flag',
        spanishFlag: 'Spanish Flag',
        darkMode: 'Dark Mode',
        home: 'Home',
        aboutUs: 'About Us',
        legalResources: 'Legal Resources',
        getInTouch: 'Get In Touch',
        socialMedia: 'Social Media',
        clientPortal: 'Client Portal',
        ourTeam: 'Our Team',
        ourServices: 'Our Services',
        testimonials: 'Testimonials',
        pricing: 'Pricing',
        faq: 'FAQ',
        blog: 'Blog',
        externalLegalResources: 'External Legal Resources',
        legalDisclaimersAndPolicies: 'Legal Disclaimers And Policies',
        contactUs: 'Contact Us',
        joinOurTeam: 'Join Our Team',
        siteMap: 'Sitemap',
        siteNavigation: 'Site Navigation',
        image: 'Image',
        divorceProceedings: 'Divorce Proceedings',
        custodyProceedings: 'Custody Proceedings',
        termsOfService: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        dataProtection: 'Data Protection',
        refundPolicy: 'Refund Policy',
        lawyersImageDescription: 'Two lawyers, dressed in professional attire, are standing inside a courtroom. They are engaged in a handshake, symbolizing mutual agreement or the conclusion of legal proceedings.',
        legalCollabTeam: 'LegalCollab\'s Team.',
        lawyerThumbsUpImageDescription: 'Lawyer giving a thumbs up to the camera while speaking on the phone.',
        lawyerHelpingClientImageDescription: 'A lawyer helping a client in a courtroom.',
        nextImage: 'Next Image',
        carouselOneDescription: 'A lawyer in Court.',
        carouselTwoDescription: 'Three team members.',
        carouselThreeDescription: 'LegalCollab\'s team on a video meeting.',
        carouselFourDescription: 'Three team members.',
        needHelp: 'Need Help?',
        onlineChat: 'Online Chat',
        onlineMeeting: 'Online Meeting',
        close: 'Close',
        haveADoubt: 'Do you have a doubt? We\'re here for you!',
        sendUsAMessage: 'Send us a message',
        frequentlyAskedQuestions: 'Frequently Asked Questions',
        scheduleAMeeting: 'Schedule a Meeting',
        connectWithOurExperts: 'Connect with Our Experts through a personalized online meeting with our legal team. Discuss your case, ask questions, and get tailored advice from the comfort of your home.',
        homeDescription: 'Affordable online legal assistance for divorce and custody proceedings.',
        empoweringYourLegalJourney: 'Empowering Your Legal Journey Through Expert Guidance.',
        exploreOurServices: 'Explore Our Services',
        legalAssistance: 'Legal Assistance',
        navigateDivorce: 'Navigate divorce and custody proceedings with personalized legal assistance. Our team of experienced attorneys is committed to guiding you through every step of the process.',
        discoverOurServices: 'Discover Our Services',
        haveQuestions: 'Have questions or need personalized support? Connect with us directly. Our team is ready to assist you with any inquiries related to family law.',
        meetOurTeam: 'Meet Our Team',
        discoverOurTeam: 'Discover our team of dedicated attorneys specializing in family law. Learn about their vast experience and unwavering commitment to supporting our clients.',
        meetOurLegalExperts: 'Meet Our Legal Experts',
        decadesOfLegalExpertise: 'Decades of Legal Expertise',
        withDecadesOfExperience: 'With decades of experience, we\'ve successfully handled numerous cases. We understand the intricacies of family law, ensuring you receive top-notch legal representation.',
        whatOurClientsSay: 'What Our Clients Have To Say',
        readTestimonials: 'Read testimonials from clients who have benefited from our affordable online legal assistance. Your success story could be next!',
        carrollCounty: 'Carroll County',
        incrediblySupportiveTeam: 'Incredibly supportive team. They made a challenging process much easier.',
        baltimoreCounty: 'Baltimore County',
        exceptionalService: 'Exceptional service. I highly recommend LegalCollab for family law matters.',
        howardCounty: 'Howard County',
        professionalEfficientUnderstanding: 'Professional, efficient, and understanding. Grateful for their expertise.',
        viewMoreTestimonials: 'View more testimonials',
    },
    es: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        language: 'Idioma',
        homepage: "Página de Inicio",
        attorneyCollaborativeOnlineService: "Servicio en Línea Colaborativo para Abogados",
        unitedStatesFlag: 'Bandera de los Estados Unidos',
        spanishFlag: 'Bandera Española',
        darkMode: 'Modo Oscuro',
        home: 'Inicio',
        aboutUs: 'Acerca de nosotros',
        legalResources: 'Recursos Legales',
        getInTouch: 'Ponte en Contacto',
        socialMedia: 'Redes Sociales',
        clientPortal: 'Portal del Cliente',
        ourTeam: 'Nuestro Equipo',
        ourServices: 'Servicios',
        testimonials: 'Testimonios',
        pricing: 'Precios',
        faq: 'Preguntas Frecuentes',
        blog: 'Blog',
        externalLegalResources: 'Recursos Legales Externos',
        legalDisclaimersAndPolicies: 'Avisos Legales y Políticas',
        contactUs: 'Contáctanos',
        joinOurTeam: 'Únete a Nuestro Equipo',
        siteMap: 'Mapa del sitio',
        siteNavigation: 'Navegación del Sitio',
        image: 'Imagen',
        divorceProceedings: 'Procedimientos de Divorcio',
        custodyProceedings: 'Procedimientos de Custodia',
        termsOfService: 'Términos de Servicio',
        privacyPolicy: 'Política de Privacidad',
        dataProtection: 'Protección de Datos',
        refundPolicy: 'Política de Reembolso',
        lawyersImageDescription: 'Dos abogados, vestidos de manera profesional, están de pie dentro de una sala de audiencias. Se están dando un apretón de manos, simbolizando un acuerdo mutuo o la conclusión de un procedimiento legal.',
        legalCollabTeam: 'El equipo de LegalCollab',
        lawyerThumbsUpImageDescription: 'Abogado dando un pulgar hacia arriba a la cámara mientras habla por teléfono.',
        lawyerHelpingClientImageDescription: 'Un abogado ayudando a un cliente en un tribunal.',
        nextImage: 'Siguiente Imagen',
        carouselOneDescription: 'Una abogada en una corte.',
        carouselTwoDescription: 'Tres miembros del equipo.',
        carouselThreeDescription: 'El equipo de LegalCollab en una videollamada.',
        carouselFourDescription: 'Tres miembros del equipo.',
        needHelp: '¿Necesitas ayuda?',
        onlineChat: 'Chat en línea',
        onlineMeeting: 'Reunión en línea',
        close: 'Cerrar',
        haveADoubt: '¿Tienes alguna duda? ¡Estamos aquí para ayudarte!',
        sendUsAMessage: 'Envíanos un mensaje',
        frequentlyAskedQuestions: 'Preguntas frecuentes',
        scheduleAMeeting: 'Programar una reunión',
        connectWithOurExperts: 'Conéctate con nuestros expertos a través de una reunión en línea personalizada con nuestro equipo legal. Discute tu caso, haz preguntas y recibe asesoramiento desde la comodidad de tu hogar.',
        homeDescription: 'Asistencia legal en línea asequible para procesos de divorcio y custodia.',
        empoweringYourLegalJourney: 'Empoderando tu trayectoria legal mediante orientación experta.',
        exploreOurServices: 'Explora Nuestros Servicios',
        legalAssistance: 'Asistencia Legal',
        navigateDivorce: 'Navega por los procedimientos de divorcio y custodia con asistencia legal personalizada. Nuestro equipo de abogados experimentados se compromete a guiarte en cada paso del proceso.',
        discoverOurServices: 'Descubre Nuestros Servicios',
        haveQuestions: '¿Tienes preguntas o necesitas apoyo personalizado? Conéctate con nosotros directamente. Nuestro equipo está listo para ayudarte con cualquier consulta relacionada con el derecho de familia.',
        meetOurTeam: 'Conoce a Nuestro Equipo',
        discoverOurTeam: 'Descubre nuestro equipo de abogados dedicados especializados en derecho de familia. Conoce su vasta experiencia y su compromiso inquebrantable de apoyar a nuestros clientes.',
        meetOurLegalExperts: 'Conoce a Nuestros Expertos Legales',
        decadesOfLegalExpertise: 'Décadas de Experiencia Legal',
        withDecadesOfExperience: 'Con décadas de experiencia, hemos manejado con éxito numerosos casos. Entendemos las complejidades del derecho de familia, asegurando que recibas una representación legal de primera.',
        whatOurClientsSay: 'Lo Que Dicen Nuestros Clientes',
        readTestimonials: 'Lee testimonios de clientes que se han beneficiado de nuestra asequible asistencia legal en línea. ¡Tu historia de éxito podría ser la próxima!',
        carrollCounty: 'Condado de Carroll',
        incrediblySupportiveTeam: 'Equipo increíblemente solidario. Hicieron un proceso desafiante mucho más fácil.',
        baltimoreCounty: 'Condado de Baltimore',
        exceptionalService: 'Servicio excepcional. Recomiendo altamente LegalCollab para asuntos de derecho de familia.',
        howardCounty: 'Condado de Howard',
        professionalEfficientUnderstanding: 'Profesionales, eficientes y comprensivos. Agradecido por su experiencia.',
        viewMoreTestimonials: 'Ver más testimonios',
    },
};