export const translator = {
    en: {
        comingSoon: 'Coming Soon',
        copyright: 'Copyright ©',
        allRightsReserved: 'All rights reserved.',
        language: 'Language',
        homepage: "Homepage",
        attorneyCollaborativeOnlineService: "Attorney's Collaborative Online Service",
        unitedStatesFlag: 'United States\' Flag',
        spanishFlag: 'Spanish Flag',
        darkMode: 'Dark Mode',
        home: 'Home',
        aboutUs: 'About Us',
        legalResources: 'Legal Resources',
        getInTouch: 'Get In Touch',
        socialMedia: 'Social Media',
        clientPortal: 'Client Portal',
        ourTeam: 'Our Team',
        ourServices: 'Our Services',
        testimonials: 'Testimonials',
        pricing: 'Pricing',
        faq: 'FAQ',
        blog: 'Blog',
        externalLegalResources: 'External Legal Resources',
        legalDisclaimersAndPolicies: 'Legal Disclaimers And Policies',
        contactUs: 'Contact Us',
        joinOurTeam: 'Join Our Team',
        siteMap: 'Sitemap',
        siteNavigation: 'Site Navigation',
    },
    es: {
        comingSoon: 'Próximamente',
        copyright: 'Derechos de autor ©',
        allRightsReserved: 'Todos los derechos reservados.',
        language: 'Idioma',
        homepage: "Página de Inicio",
        attorneyCollaborativeOnlineService: "Servicio en Línea Colaborativo para Abogados",
        unitedStatesFlag: 'Bandera de los Estados Unidos',
        spanishFlag: 'Bandera Española',
        darkMode: 'Modo Oscuro',
        home: 'Inicio',
        aboutUs: 'Acerca de nosotros',
        legalResources: 'Recursos Legales',
        getInTouch: 'Ponte en Contacto',
        socialMedia: 'Redes Sociales',
        clientPortal: 'Portal del Cliente',
        ourTeam: 'Nuestro Equipo',
        ourServices: 'Servicios',
        testimonials: 'Testimonios',
        pricing: 'Precios',
        faq: 'Preguntas Frecuentes',
        blog: 'Blog',
        externalLegalResources: 'Recursos Legales Externos',
        legalDisclaimersAndPolicies: 'Avisos Legales y Políticas',
        contactUs: 'Contáctanos',
        joinOurTeam: 'Únete a Nuestro Equipo',
        siteMap: 'Mapa del sitio',
        siteNavigation: 'Navegación del Sitio',
    },
};