import type { Profile } from "./stores";

export type Post = {
    id: number,
    userId: string,
    date: string,
    content: string,
    img: string,
    parentPostID: number | undefined,
    likes:number,
    comments:number,
}


//data


export const postsDB: Post[] = [
    {likes: 0, comments: 6, userId:'0', parentPostID: undefined, id: 0, date: new Date().toISOString(), content: "Vero totam modi nemo cumque optio. <br> https://clappforms.web.app", img:"" },
    {likes: 0, comments: 6, userId:'1', parentPostID: undefined, id: 1, date: new Date().toISOString(), content: '‘THE LATE LATE SHOW WITH JAMES CORDEN’ has ended after 8 years.', img: "https://pbs.twimg.com/media/Fuy26UuWAAAu0Q5?format=jpg&name=large" },
    {likes: 0, comments: 0, userId:'2', parentPostID: undefined, id: 2, date: new Date(2023, 3, 27, 6).toISOString(), img:"", content: "Quod nemo distinctio reprehenderit laboriosam accusamus iusto, dicta, dolore perspiciatis corporis dignissimos eos cum exercitationem deserunt? Deleniti, delectus quam? Vero non beatae labore eos esse quidem odit maxime doloremque culpa ducimus sit nemo quaerat a cupiditate ad velit nam qui laborum impedit neque, incidunt atque officia? <br><br> In optio officia accusantium, id doloremque aut laudantium doloribus magnam magni, dolorem, corrupti provident ut ab quidem eligendi eveniet neque quas vitae explicabo? Eius, aperiam natus laborum dolorem praesentium temporibus enim ducimus illum hic qui dicta aliquid, debitis facilis quidem ipsam voluptates! Odio officia nam laborum perspiciatis quidem cupiditate adipisci, incidunt natus dicta. <br><br> Deserunt veniam doloribus neque dolorum itaque obcaecati cum voluptatem sapiente nobis! Minus sunt tempora doloremque quos enim, quae dolorum, iste ex adipisci earum libero sint sequi culpa, inventore consectetur suscipit sed dignissimos cumque? Nisi quos nemo asperiores perferendis alias! <br><br> Voluptatem sunt, reprehenderit aperiam repellendus, officiis dolorum vel fugiat doloribus distinctio placeat corrupti eos hic repudiandae ipsum molestiae ullam ad tempore, iure ipsam nulla. Dolorum quod architecto illum neque. Explicabo quas alias voluptatum amet ad, quis recusandae id exercitationem impedit, beatae provident dolore obcaecati omnis quod placeat ipsam minus quasi. Reprehenderit placeat voluptatem illo." },
    {likes: 0, comments: 0, userId:'3', parentPostID: undefined, id: 3, date: new Date(2023, 3, 21).toISOString(), img:"", content: "Ducimus debitis amet sint quis, ea maiores, eaque dolore veniam, est doloremque animi nostrum distinctio magni saepe labore suscipit temporibus quasi recusandae repellendus. Perferendis velit possimus natus numquam officia reprehenderit commodi facere quis, maxime explicabo quisquam libero harum obcaecati! Vitae, ad molestiae unde architecto voluptatem obcaecati non nam tempore corrupti ipsam ab aperiam temporibus exercitationem quaerat ullam quo. Provident itaque maiores ipsum iure unde atque inventore id repellendus, molestiae, nam officiis laboriosam rem fugit pariatur, commodi aperiam incidunt accusamus expedita nobis nemo eum? Doloremque omnis enim ipsam quod, consequatur voluptatibus ad! Eius, quibusdam. A necessitatibus at voluptatem error." },
    {likes: 0, comments: 0, userId:'4', parentPostID: undefined, id: 4,  date: new Date(2023, 3, 27, 13, 5).toISOString(), img:"", content: "Maxime delectus culpa voluptate unde aperiam reprehenderit nobis incidunt explicabo natus velit consequuntur, quas, hic tempora quam vero dolor ipsum impedit pariatur quisquam optio fugit nesciunt laboriosam eaque. Sit beatae accusantium eum earum quidem distinctio impedit voluptates esse odio facere laboriosam, omnis rem consequuntur cum porro officiis alias deserunt modi. Minus, pariatur?" },
    {likes: 0, comments: 0, userId:'5', parentPostID: undefined, id: 5, date: new Date(2023, 2, 27).toISOString(), img:"", content: "Nobis dicta accusantium ut natus fuga accusamus repellat nostrum voluptatem reiciendis explicabo voluptatibus nam incidunt quasi adipisci, similique consectetur, ipsum vel porro." },
    {likes: 0, comments: 0, userId:'0', parentPostID: undefined, id: 6, date: new Date(2022, 11, 29).toISOString(), img:"", content: "Itaque velit accusantium magni sequi, in excepturi provident dolorum est perspiciatis aperiam laboriosam eius, porro eaque saepe esse placeat amet cumque sit! Corrupti est fugit nobis quidem incidunt minima tempore ipsa dolorem nam impedit illum voluptas amet dolore aperiam quam unde, laboriosam ipsum ratione delectus! Qui nihil sapiente, explicabo maxime perspiciatis molestias fugiat architecto deserunt beatae minus ad quod autem dolore suscipit." },

    {likes: 0, comments: 0, userId:'0', parentPostID: 0, id: 14, date: new Date().toISOString(), content: '‘THE LATE LATE SHOW WITH JAMES CORDEN’ has ended after 8 years.', img: "https://pbs.twimg.com/media/Fuy26UuWAAAu0Q5?format=jpg&name=large" },
    {likes: 0, comments: 0, userId:'1', parentPostID: 0, id: 15, date: new Date(2023, 3, 27, 6).toISOString(), img:"", content: "Quod nemo distinctio reprehenderit laboriosam accusamus iusto, dicta, dolore perspiciatis corporis dignissimos eos cum exercitationem deserunt? Deleniti, delectus quam? Vero non beatae labore eos esse quidem odit maxime doloremque culpa ducimus sit nemo quaerat a cupiditate ad velit nam qui laborum impedit neque, incidunt atque officia? <br><br> In optio officia accusantium, id doloremque aut laudantium doloribus magnam magni, dolorem, corrupti provident ut ab quidem eligendi eveniet neque quas vitae explicabo? Eius, aperiam natus laborum dolorem praesentium temporibus enim ducimus illum hic qui dicta aliquid, debitis facilis quidem ipsam voluptates! Odio officia nam laborum perspiciatis quidem cupiditate adipisci, incidunt natus dicta. <br><br> Deserunt veniam doloribus neque dolorum itaque obcaecati cum voluptatem sapiente nobis! Minus sunt tempora doloremque quos enim, quae dolorum, iste ex adipisci earum libero sint sequi culpa, inventore consectetur suscipit sed dignissimos cumque? Nisi quos nemo asperiores perferendis alias! <br><br> Voluptatem sunt, reprehenderit aperiam repellendus, officiis dolorum vel fugiat doloribus distinctio placeat corrupti eos hic repudiandae ipsum molestiae ullam ad tempore, iure ipsam nulla. Dolorum quod architecto illum neque. Explicabo quas alias voluptatum amet ad, quis recusandae id exercitationem impedit, beatae provident dolore obcaecati omnis quod placeat ipsam minus quasi. Reprehenderit placeat voluptatem illo." },
    {likes: 0, comments: 0, userId:'2', parentPostID: 0, id: 16, date: new Date(2023, 3, 21).toISOString(), img:"", content: "Ducimus debitis amet sint quis, ea maiores, eaque dolore veniam, est doloremque animi nostrum distinctio magni saepe labore suscipit temporibus quasi recusandae repellendus. Perferendis velit possimus natus numquam officia reprehenderit commodi facere quis, maxime explicabo quisquam libero harum obcaecati! Vitae, ad molestiae unde architecto voluptatem obcaecati non nam tempore corrupti ipsam ab aperiam temporibus exercitationem quaerat ullam quo. Provident itaque maiores ipsum iure unde atque inventore id repellendus, molestiae, nam officiis laboriosam rem fugit pariatur, commodi aperiam incidunt accusamus expedita nobis nemo eum? Doloremque omnis enim ipsam quod, consequatur voluptatibus ad! Eius, quibusdam. A necessitatibus at voluptatem error." },
    {likes: 0, comments: 0, userId:'3', parentPostID: 0, id: 17,  date: new Date(2023, 3, 27, 13, 5).toISOString(), img:"", content: "Maxime delectus culpa voluptate unde aperiam reprehenderit nobis incidunt explicabo natus velit consequuntur, quas, hic tempora quam vero dolor ipsum impedit pariatur quisquam optio fugit nesciunt laboriosam eaque. Sit beatae accusantium eum earum quidem distinctio impedit voluptates esse odio facere laboriosam, omnis rem consequuntur cum porro officiis alias deserunt modi. Minus, pariatur?" },
    {likes: 0, comments: 0, userId:'4', parentPostID: 0, id: 18, date: new Date(2023, 2, 27).toISOString(), img:"", content: "Nobis dicta accusantium ut natus fuga accusamus repellat nostrum voluptatem reiciendis explicabo voluptatibus nam incidunt quasi adipisci, similique consectetur, ipsum vel porro." },
    {likes: 0, comments: 0, userId:'5', parentPostID: 0, id: 19, date: new Date(2022, 11, 29).toISOString(), img:"", content: "Itaque velit accusantium magni sequi, in excepturi provident dolorum est perspiciatis aperiam laboriosam eius, porro eaque saepe esse placeat amet cumque sit! Corrupti est fugit nobis quidem incidunt minima tempore ipsa dolorem nam impedit illum voluptas amet dolore aperiam quam unde, laboriosam ipsum ratione delectus! Qui nihil sapiente, explicabo maxime perspiciatis molestias fugiat architecto deserunt beatae minus ad quod autem dolore suscipit." },

    {likes: 0, comments: 0, userId:'0', parentPostID: 1, id: 7, date: new Date().toISOString(), content: "Vero totam modi nemo cumque optio. <br> https://clappforms.web.app", img:"" },
    {likes: 0, comments: 0, userId:'1', parentPostID: 1, id: 9, date: new Date(2023, 3, 27, 6).toISOString(), img:"", content: "Quod nemo distinctio reprehenderit laboriosam accusamus iusto, dicta, dolore perspiciatis corporis dignissimos eos cum exercitationem deserunt? Deleniti, delectus quam? Vero non beatae labore eos esse quidem odit maxime doloremque culpa ducimus sit nemo quaerat a cupiditate ad velit nam qui laborum impedit neque, incidunt atque officia? <br><br> In optio officia accusantium, id doloremque aut laudantium doloribus magnam magni, dolorem, corrupti provident ut ab quidem eligendi eveniet neque quas vitae explicabo? Eius, aperiam natus laborum dolorem praesentium temporibus enim ducimus illum hic qui dicta aliquid, debitis facilis quidem ipsam voluptates! Odio officia nam laborum perspiciatis quidem cupiditate adipisci, incidunt natus dicta. <br><br> Deserunt veniam doloribus neque dolorum itaque obcaecati cum voluptatem sapiente nobis! Minus sunt tempora doloremque quos enim, quae dolorum, iste ex adipisci earum libero sint sequi culpa, inventore consectetur suscipit sed dignissimos cumque? Nisi quos nemo asperiores perferendis alias! <br><br> Voluptatem sunt, reprehenderit aperiam repellendus, officiis dolorum vel fugiat doloribus distinctio placeat corrupti eos hic repudiandae ipsum molestiae ullam ad tempore, iure ipsam nulla. Dolorum quod architecto illum neque. Explicabo quas alias voluptatum amet ad, quis recusandae id exercitationem impedit, beatae provident dolore obcaecati omnis quod placeat ipsam minus quasi. Reprehenderit placeat voluptatem illo." },
    {likes: 0, comments: 0, userId:'2', parentPostID: 1, id: 10, date: new Date(2023, 3, 21).toISOString(), img:"", content: "Ducimus debitis amet sint quis, ea maiores, eaque dolore veniam, est doloremque animi nostrum distinctio magni saepe labore suscipit temporibus quasi recusandae repellendus. Perferendis velit possimus natus numquam officia reprehenderit commodi facere quis, maxime explicabo quisquam libero harum obcaecati! Vitae, ad molestiae unde architecto voluptatem obcaecati non nam tempore corrupti ipsam ab aperiam temporibus exercitationem quaerat ullam quo. Provident itaque maiores ipsum iure unde atque inventore id repellendus, molestiae, nam officiis laboriosam rem fugit pariatur, commodi aperiam incidunt accusamus expedita nobis nemo eum? Doloremque omnis enim ipsam quod, consequatur voluptatibus ad! Eius, quibusdam. A necessitatibus at voluptatem error." },
    {likes: 0, comments: 0, userId:'3', parentPostID: 1, id: 11,  date: new Date(2023, 3, 27, 13, 5).toISOString(), img:"", content: "Maxime delectus culpa voluptate unde aperiam reprehenderit nobis incidunt explicabo natus velit consequuntur, quas, hic tempora quam vero dolor ipsum impedit pariatur quisquam optio fugit nesciunt laboriosam eaque. Sit beatae accusantium eum earum quidem distinctio impedit voluptates esse odio facere laboriosam, omnis rem consequuntur cum porro officiis alias deserunt modi. Minus, pariatur?" },
    {likes: 0, comments: 0, userId:'4', parentPostID: 1, id: 12, date: new Date(2023, 2, 27).toISOString(), img:"", content: "Nobis dicta accusantium ut natus fuga accusamus repellat nostrum voluptatem reiciendis explicabo voluptatibus nam incidunt quasi adipisci, similique consectetur, ipsum vel porro." },
    {likes: 0, comments: 0, userId:'5', parentPostID: 1, id: 13, date: new Date(2022, 11, 29).toISOString(), img:"", content: "Itaque velit accusantium magni sequi, in excepturi provident dolorum est perspiciatis aperiam laboriosam eius, porro eaque saepe esse placeat amet cumque sit! Corrupti est fugit nobis quidem incidunt minima tempore ipsa dolorem nam impedit illum voluptas amet dolore aperiam quam unde, laboriosam ipsum ratione delectus! Qui nihil sapiente, explicabo maxime perspiciatis molestias fugiat architecto deserunt beatae minus ad quod autem dolore suscipit." },
];

export const profileDB: Profile[] = [
    {
        id: '0',
        fullName: 'Jamie Chen',
        department: '',
        jobTitle: 'President of Sales',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZmlsZXxlbnwwfHwwfHw%3D&w=1000&q=80',
        birthday: '',
    },
    {
        id: '1',
        fullName: 'Alex Patel',
        department: '',
        jobTitle: 'Receptionist',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?cs=srgb&dl=pexels-pixabay-220453.jpg&fm=jpg',
        birthday: '',
    },
    {
        id: '2',
        fullName: 'Hanna Rodriguez',
        department: '',
        jobTitle: 'Marketing Coordinator',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://newprofilepic2.photo-cdn.net//assets/images/article/profile.jpg',
        birthday: '',
    },
    {
        id: '3',
        fullName: 'Taylor Nguyen',
        department: '',
        jobTitle: 'Web Designer',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://media.istockphoto.com/id/1338767515/photo/proud-african-woman-smiling-profile-of-successful-businesswoman-in-red-suit-excited-touching.jpg?s=612x612&w=0&k=20&c=51pi7rGUJps8sfEWtNDfKVw3rHxE_qCNkEFcUXyZ9cI=',
        birthday: '',
    },
    {
        id: '4',
        fullName: 'Casey Lee',
        department: '',
        jobTitle: 'Project Manager',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://writestylesonline.com/wp-content/uploads/2018/11/Three-Statistics-That-Will-Make-You-Rethink-Your-Professional-Profile-Picture.jpg',
        birthday: '',
    },
    {
        id: '5',
        fullName: 'Sarah Singh',
        department: '',
        jobTitle: 'Account Executive',
        mail: '',
        mobilePhone: '',
        officeLocation: '',
        preferredLanguage: '',
        profilePicture: 'https://shotkit.com/wp-content/uploads/bb-plugin/cache/cool-profile-pic-matheus-ferrero-landscape.jpeg',
        birthday: '',
    },
]