export const notifications: any[] = [
    {
        id: '0',
        content: `Today is Sarah Singh's Birthday!`, 
        seen: true,
        dismissed: false,
        date: new Date(2022, 7, 10).toISOString(),
    },
    {
        id: '1',
        content: 'Monthly assessment reunion starts in 1 hour.', 
        seen: true,
        dismissed: false,
        date: new Date(2022, 9, 15).toISOString(),
    },
    {
        id: '2',
        content: `Today is Taylor Nguyen's Birthday!`, 
        seen: true,
        dismissed: false,
        date: new Date(2022, 11, 20).toISOString(),
    },
    {
        id: '3',
        content: 'New announcement: Project deadline extended.',
        seen: true,
        dismissed: false,
        date: new Date(2023, 0, 5).toISOString(),
    },
    {
        id: '4',
        content: 'Upcoming team meeting on Friday.',
        seen: true,
        dismissed: false,
        date: new Date(2023, 1, 28).toISOString(),
    },
    {
        id: '5',
        content: 'Important security update: Please update your passwords.',
        seen: true,
        dismissed: false,
        date: new Date(2023, 2, 10).toISOString(),
    },
    {
        id: '6',
        content: 'New feature release: Real-time collaboration.',
        seen: true,
        dismissed: false,
        date: new Date(2023, 3, 18).toISOString(),
    },
    {
        id: '7',
        content: 'Celebrating 1000 users milestone!',
        seen: true,
        dismissed: false,
        date: new Date(2023, 3, 15).toISOString(),
    },
    {
        id: '8',
        content: 'Holiday office closure: December 25th - January 1st.',
        seen: false,
        dismissed: false,
        date: new Date(2023, 2, 27).toISOString(),
    },
    {
        id: '9',
        content: 'Product roadmap update: New features planned for Q3.',
        seen: false,
        dismissed: false,
        date: new Date(2023, 4, 11).toISOString(),
    },
    {
        id: '10',
        content: 'Reminder: Submit your monthly reports by end of day.',
        seen: false,
        dismissed: false,
        date: new Date().toISOString(),
    },
];