export const translator = {
    english: {
        error: `An error occurred.`,
        logInWithMicrosoft: 'Log in with Microsoft',
        copyright: 'Copyright',
        lawOfficeOfKatherineCanto: 'Law Office Of Katherine Canto',
        cantoLegalIntranet: 'Canto Legal Intranet',
        thePlaceWhereYouCanFind: 'The place where you can find ',
        subtitlePhrases: [
            'information about your department.',
            'policies and procedures.',
            'organization charts.',
            'announcements.',
            'your duties and rights.',
            'the requirements and benefits of our clients.',
            'labor benefits.',
            `our team's birthdays.`,
            'our ethics policy.'
        ],
        goToOurWebsite: 'Go to our website',
        unitedStatesFlag: 'united states flag',
        spanishFlag: 'spanish flag',
        multipleAccountsDetected: 'Multiple accounts detected.',
        logoCantoLegal: 'Logo Canto Legal',
        logOut: 'Log Out',
        home: 'Home',
        people: 'People',
        generalInformation: 'General Information',
        profile: 'profile',
        minutesRead: 'minutes read',
        cantoLegalEmployee: "Canto Legal Employee",
        teams: 'Teams',
        teamsSubtitle: 'Alone we can do so little; together we can do so much.',
        articles: {
            policies: "<h2>Introduction:</h2><br>Canto Legal is an immigration law office that is dedicated to assisting clients with their immigration needs. The office is committed to providing high-quality legal services in a timely and efficient manner, while ensuring that all clients are treated with dignity and respect. In this article, we will discuss the policies and procedures that are in place at Canto Legal to ensure that the office runs smoothly and that clients receive the best possible service.<br><br><h2>Client Communication:</h2><br>At Canto Legal, we believe that effective communication with our clients is essential to providing high-quality legal services. We are committed to keeping our clients informed throughout the entire immigration process, and we strive to respond to all client inquiries and concerns in a timely manner. To ensure that communication is clear and consistent, all clients are assigned a dedicated attorney who will serve as their primary point of contact throughout their case.<br><br><h2>Client Confidentiality:</h2><br>Canto Legal takes client confidentiality very seriously. All client information and communications are kept strictly confidential, and only authorized personnel have access to client files. To ensure that client confidentiality is maintained, all staff members are required to sign a confidentiality agreement upon employment.<br><br><h2>Case Management:</h2><br>To ensure that all client cases are handled efficiently and effectively, Canto Legal has implemented a comprehensive case management system. All client cases are assigned to an attorney, who is responsible for managing the case from start to finish. Each case is assigned a unique identification number, and all case-related documents and communications are stored in the client’s electronic file. Regular case status updates are provided to clients to keep them informed of the progress of their case.<br><br><h2>Legal Research:</h2><br>At Canto Legal, we believe that staying up-to-date on changes to immigration laws and regulations is essential to providing high-quality legal services. To ensure that our attorneys are well-informed, we have a dedicated legal research team that monitors changes to immigration laws and regulations and provides regular updates to our attorneys. This ensures that our attorneys are able to provide accurate and up-to-date legal advice to our clients.<br><br><h2>Fee Structure:</h2><br>Canto Legal has a transparent fee structure that is based on the complexity of the case and the amount of time required to complete the work. All fees are discussed with clients upfront, and clients are provided with a detailed fee agreement that outlines the scope of work, the fee structure, and the payment schedule. Clients are also provided with regular billing statements that detail the work that has been completed and the fees charged.<br><br><h2>Billing Practices:</h2><br>Canto Legal is committed to providing transparent and accurate billing statements to our clients. All billing statements include a detailed description of the work that has been completed, the time spent on each task, and the fees charged. Clients are encouraged to review their billing statements regularly and to raise any questions or concerns with their attorney.<br><br><h2>Staff Training and Development:</h2><br>At Canto Legal, we believe that investing in the training and development of our staff is essential to providing high-quality legal services. We provide regular training sessions to our staff on topics such as immigration law, case management, and client communication. We also encourage our staff to attend conferences and seminars to stay up-to-date on changes to immigration laws and regulations.<br><br><h2>Conclusion:</h2><br>Canto Legal is committed to providing high-quality legal services to our clients. Our policies and procedures are designed to ensure that all clients are treated with dignity and respect, that communication is clear and consistent, and that all cases are handled efficiently and effectively. We believe that by maintaining high standards of professionalism and by investing in the training and development of our staff, we are able to provide the best possible service to our clients."
        },
        teamNames: [
            'My company',
            'My department'
        ],
        sendAMessage: 'Send a message',
        seeProfile: 'See profile',
        justPublished: 'Just published',
        minute: 'minute',
        hour: 'hour',
        day: 'day',
        month: 'month',
        months: 'months',
        year: 'year',
        hace: '',
        ago: 'ago',
        and: 'and',
        reply: 'Reply',
        like: 'Like',
        comments: 'Comments',
        cancel: 'Cancel',
        submit: 'Submit',
        showMore: 'Show more',
        showLess: 'Show less',
        unableToLoad: 'Unable to load',
        repliesTo: 'Replies to:',
        thisPostDoesNotHaveAnyReplies: `This post doesn't have any replies yet.`,
    },
    español: {
        error: 'Ha ocurrido un error.',
        logInWithMicrosoft: 'Iniciar sesión con Microsoft',
        copyright: 'Derechos de autor',
        lawOfficeOfKatherineCanto: 'Oficina Legal de Katherine Canto',
        cantoLegalIntranet: 'Intranet de Canto Legal',
        thePlaceWhereYouCanFind: 'El lugar donde puedes encontrar ',
        subtitlePhrases: [
            'información acerca de tu departamento.',
            'políticas y procedimientos.',
            'organigramas.',
            'anuncios.',
            'tus deberes y derechos.',
            'los requisitos y beneficios de nuestros clientes.',
            'beneficios laborales.',
            'los cumpleaños de nuestro equipo.',
            'nuestra política de ética.'
        ],
        goToOurWebsite: 'Visita nuestro sitio web',
        unitedStatesFlag: 'bandera de los Estados Unidos',
        spanishFlag: 'bandera de España',
        multipleAccountsDetected: 'Se han detectado varias cuentas.',
        logoCantoLegal: 'Logo de Canto Legal',
        logOut: 'Cerrar sesión',
        home: 'Inicio',
        people: 'Personas',
        generalInformation: 'Información General',
        profile: 'Perfil',
        minutesRead: 'minutos de lectura',
        cantoLegalEmployee: "Empleado(a) de Canto Legal",
        teams: 'Equipos',
        teamsSubtitle: 'El trabajo en equipo divide el trabajo y multiplica los resultados.',
        articles: {
            policies: "<h2>Introducción:</h2><br>Canto Legal es una oficina de abogados especializada en inmigración que se dedica a ayudar a sus clientes con sus necesidades migratorias. La oficina se compromete a proporcionar servicios legales de alta calidad de manera oportuna y eficiente, al mismo tiempo que se asegura de tratar a todos los clientes con dignidad y respeto. En este artículo, discutiremos las políticas y procedimientos que están en vigor en Canto Legal para asegurarse de que la oficina funcione sin problemas y de que los clientes reciban el mejor servicio posible.<br><br><h2>Comunicación con el cliente:</h2><br>En Canto Legal, creemos que una comunicación efectiva con nuestros clientes es esencial para proporcionar servicios legales de alta calidad. Estamos comprometidos en mantener a nuestros clientes informados durante todo el proceso migratorio y nos esforzamos por responder a todas las consultas y preocupaciones de los clientes de manera oportuna. Para asegurarnos de que la comunicación sea clara y consistente, a cada cliente se le asigna un abogado dedicado que será su principal punto de contacto durante todo el caso.<br><br><h2>Confidencialidad del cliente:</h2><br>Canto Legal toma muy en serio la confidencialidad del cliente. Toda la información y comunicación del cliente se mantiene estrictamente confidencial, y solo el personal autorizado tiene acceso a los archivos del cliente. Para asegurar que se mantenga la confidencialidad del cliente, se requiere que todos los miembros del personal firmen un acuerdo de confidencialidad al momento de su contratación.<br><br><h2>Gestión de casos:</h2><br>Para asegurarnos de que todos los casos de los clientes se manejen de manera eficiente y efectiva, Canto Legal ha implementado un sistema de gestión de casos integral. Todos los casos de los clientes se asignan a un abogado que es responsable de manejar el caso desde el inicio hasta el final. Cada caso se asigna un número de identificación único y todos los documentos y comunicaciones relacionados con el caso se almacenan en el archivo electrónico del cliente. Se proporcionan actualizaciones regulares del estado del caso a los clientes para mantenerlos informados sobre el progreso de su caso.<br><br><h2>Investigación legal:</h2><br>En Canto Legal, creemos que estar al tanto de los cambios en las leyes y regulaciones migratorias es esencial para proporcionar servicios legales de alta calidad. Para asegurarnos de que nuestros abogados estén bien informados, contamos con un equipo de investigación legal dedicado que monitorea los cambios en las leyes y regulaciones migratorias y proporciona actualizaciones regulares a nuestros abogados. Esto garantiza que nuestros abogados puedan brindar asesoramiento legal preciso y actualizado a nuestros clientes.<br><br><h2>Estructura de tarifas:</h2><br>Canto Legal tiene una estructura de tarifas transparente que se basa en la complejidad del caso y la cantidad de tiempo requerida para completar el trabajo. Todas las tarifas se discuten con los clientes por adelantado, y se les proporciona un acuerdo detallado de tarifas que describe el alcance del trabajo, la estructura de tarifas y el calendario de pagos. También se proporcionan estados de cuenta de facturación regulares a los clientes que detallan el trabajo que se ha completado y las tarifas cobradas.<br><br><h2>Prácticas de facturación:</h2><br>Canto Legal se compromete a proporcionar estados de cuenta de facturación transparentes y precisos a nuestros clientes. Todos los estados de cuenta de facturación incluyen una descripción detallada del trabajo que se ha completado, el tiempo dedicado a cada tarea y las tarifas cobradas. Se anima a los clientes a revisar regularmente sus estados de cuenta de facturación y a plantear cualquier pregunta o inquietud con su abogado.<br><br><h2>Formación y desarrollo del personal:</h2><br>En Canto Legal, creemos que invertir en la formación y desarrollo de nuestro personal es esencial para proporcionar servicios legales de alta calidad. Ofrecemos sesiones de capacitación periódicas a nuestro personal sobre temas como la ley de inmigración, la gestión de casos y la comunicación con el cliente. También alentamos a nuestro personal a asistir a conferencias y seminarios para mantenerse al día sobre los cambios en las leyes y regulaciones de inmigración.<br><br><h2>Conclusión:</h2><br>Canto Legal se compromete a proporcionar servicios legales de alta calidad a nuestros clientes. Nuestras políticas y procedimientos están diseñados para garantizar que todos los clientes sean tratados con dignidad y respeto, que la comunicación sea clara y constante, y que todos los casos se manejen de manera eficiente y efectiva. Creemos que al mantener altos estándares de profesionalismo y al invertir en la formación y desarrollo de nuestro personal, podemos brindar el mejor servicio posible a nuestros clientes."
        },
        teamNames: [
            'Mi compañía',
            'Mi departamento'
        ],
        sendAMessage: 'Enviar un mensaje',
        seeProfile: 'Ver perfil',
        justPublished: 'Recién publicado',
        minute: 'minuto',
        hour: 'hora',
        day: 'día',
        month: 'mes',
        months: 'meses',
        year: 'año',
        hace: 'Hace',
        ago: '',
        and: 'y',
        reply: 'Responder',
        like: 'Me gusta',
        comments: 'Comentarios',
        cancel: 'Cancelar',
        submit: 'Confirmar',
        showMore: 'Mostrar más',
        showLess: 'Mostrar menos',
        unableToLoad: 'Error cargando imagen',
        repliesTo: `Comentarios de:`,
        thisPostDoesNotHaveAnyReplies: 'Este post no tiene comentarios.',

    }
}
