export const translator = {
    fr: {
        error: `Une erreur s'est produite.`,
        highScore: 'Meilleur Score',
        wpm: 'MPM',
        wordsPerMinute: 'Mots Par Minute',
        seconds: 'Secondes',
        type: 'Tapez',
        gettingWords: 'Obtention des mots. Les instructions doivent être lues en quelques secondes. Sinon, essayez de cliquer quelque part au hasard, ou vérifiez votre connexion Internet.',
        accuracy: 'Précision',
        playAgain: 'Rejouer',
        encouragement: [
            "Bonne chance!",
            "On y va!",
            "Tu peux le faire!",
            "Avance sans peur!",
            "Ne jamais abandonner!",
            "Donne ton meilleur!",
            "Tout ira bien!",
            "Reste calme!",
            "Sois courageux!",
            "Aie confiance en toi!",
            "Toujours positif!",
            "N'abandonne pas!",
            "Tu es en contrôle!",
            "À fond la caisse!",
            "Force et honneur!",
            "Ne lâche rien!",
            "Garde espoir!",
            "Reste concentré!",
            "Ne t'arrête pas!",
            "Tu vas réussir!",
        ],
        badScore: [
            "La prochaine fois, ça ira mieux.",
            "Ne te décourage pas, c'est en forgeant qu'on devient forgeron.",
            "L'important, c'est de participer.",
            "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
            "Chaque échec est une chance de grandir et de s'améliorer.",
        ],
        goodScore: [
            "Impressionnant!",
            "Excellent travail!",
            "Bravo!",
            "Félicitations!",
            "Vous êtes incroyable!",
            "Super travail!"
        ],
        bestScore: [
            "Tu as battu ton meilleur score!",
            "Bravo! Tu as établi un nouveau record!",
            "Super travail! Tu progresses de plus en plus!",
            "Impressionnant! Ton score est incroyable!"
        ],
        hold: 'Maintenez',
        enter: 'Entrée',
        restart: 'Redémarrer',
        toRestart: 'pour redémarrer',
        pause: 'Pause',
    },
    es: {
        error: `Ha ocurrido un error.`,
        highScore: 'Mejor Puntuación',
        wpm: 'PPM',
        wordsPerMinute: 'Palabras Por Minuto',
        seconds: 'Segundos',
        type: 'Escribe',
        gettingWords: 'Obteniendo palabras. La instrucción debe leerse en unos segundos. Si no, intenta hacer clic en algún lugar al azar o verifica tu conexión a Internet.',
        accuracy: 'Precisión',
        playAgain: 'Volver A Jugar',
        encouragement: [
            "¡Buena suerte!",
            "¡Vamos!",
            "¡Tú puedes!",
            "¡Sigue adelante!",
            "¡No te rindas!",
            "¡Esfuérzate!",
            "¡Todo saldrá bien!",
            "¡Mantén la calma!",
            "¡Sé valiente!",
            "¡Confía en ti!",
            "¡Siempre positivo!",
            "¡No dejes de intentarlo!",
            "¡Tienes el control!",
            "¡A por todas!",
            "¡Dale con todo!",
            "¡Fuerza!",
            "¡No pierdas la esperanza!",
            "¡Mantén el foco!",
            "¡No te detengas!",
            "¡Triunfarás!",
        ],
        badScore: [
            "La próxima vez lo harás mejor.",
            "No te desanimes, la práctica hace al maestro.",
            "Lo importante es participar.",
            "El éxito no es definitivo, el fracaso no es fatal: es el coraje de continuar lo que cuenta.",
            "Cada fracaso es una oportunidad para crecer y mejorar.",
        ],
        goodScore: [
            "¡Impresionante!",
            "¡Excelente trabajo!",
            "¡Bravo!",
            "¡Felicidades!",
            "¡Eres increíble!",
            "¡Gran trabajo!"
        ],
        bestScore: [
            "¡Has superado tu mejor puntuación!",
            "¡Impresionante! ¡Has marcado un nuevo récord!",
            "¡Excelente trabajo! ¡Sigues mejorando cada día!",
            "¡Increíble! ¡Tu puntuación es impresionante!"
        ],
        hold: 'Mantén',
        enter: 'Enter',
        restart: 'Reiniciar',
        toRestart: 'para reiniciar',
        pause: 'Pausa',
    },
    it: {
        error: `Si è verificato un errore.`,
        highScore: 'Miglior Punteggio',
        wpm: 'PAM',
        wordsPerMinute: 'Parole Al Minuto',
        seconds: 'Secondi',
        type: 'Digita',
        gettingWords: 'Ottenere parole. Le istruzioni dovrebbero essere lette entro qualche secondo. Se non è così, prova a fare clic in un punto qualsiasi o controlla la tua connessione Internet.',
        accuracy: 'Precisione',
        playAgain: 'Rigiocare',
        encouragement: [
            "In bocca al lupo!",
            "Fai del tuo meglio!",
            "Sii coraggioso!",
            "Non mollare!",
            "Vai avanti!",
            "Credevi negli altri.",
            "Non temere il fallimento!",
            "Sii determinato!",
            "Puoi farcela!",
            "Sii forte!",
            "Sii sempre positivo!",
            "Non arrenderti mai!",
            "Sei un vincente!",
            "Non perdere la speranza!",
            "Lavora sodo!",
            "Credici!",
            "Respira e mantieni la calma!",
            "Non smettere di lottare!",
            "Non abbassare la guardia!",
            "Non arrenderti!",
        ],
        badScore: [
            "La prossima volta andrà meglio.",
            "Non scoraggiarti, l'esperienza fa il maestro.",
            "L'importante è partecipare.",
            "Il successo non è definitivo, il fallimento non è fatale: è il coraggio di continuare che conta.",
            "Ogni fallimento è un'opportunità per crescere e migliorare.",
        ],
        goodScore: [
            "Impressionante!",
            "Ottimo lavoro!",
            "Bravo!",
            "Complimenti!",
            "Sei incredibile!",
            "Gran bel lavoro!"
        ],
        bestScore: [
            "Hai battuto il tuo punteggio più alto!",
            "Incredibile! Hai stabilito un nuovo record!",
            "Ottimo lavoro! Stai migliorando sempre di più!",
            "Impressionante! Il tuo punteggio è incredibile!"
        ],
        hold: 'Tieni',
        enter: 'Invio',
        restart: 'Riavvia',
        toRestart: 'per riavviare',
        pause: 'Pausa',
    },
    en: {
        error: `An error occurred.`,
        highScore: 'High Score',
        wpm: 'WPM',
        wordsPerMinute: 'Words Per Minute',
        seconds: 'Seconds',
        type: 'Type',
        gettingWords: 'Getting Words. Instruction should be read within a couple seconds. If not, try clicking somewhere random, or check your internet connection.',
        accuracy: 'Accuracy',
        playAgain: 'Play Again',
        encouragement: [
            "Good luck!",
            "You got this!",
            "Believe in yourself!",
            "Stay focused!",
            "Breathe and stay calm!",
            "Go for it!",
            "Bring your A-game!",
            "Push yourself!",
            "You can do it!",
            "Never give up!",
            "You're a winner!",
            "Keep shining!",
            "Stay positive!",
            "Stay strong!",
            "Keep your head up!",
            "Don't give up!",
            "Stay motivated!",
            "Give it your all!",
            "Keep going!",
            "You've got what it takes!",
        ],
        badScore: [
            "You'll do better next time.",
            "Don't give up, practice makes perfect.",
            "It's the taking part that counts.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "Every failure is a chance to grow and improve.",
        ],
        goodScore: [
            "Impressive!",
            "Excellent work!",
            "Well done!",
            "Congratulations!",
            "You are amazing!",
            "Great job!"
        ],
        bestScore: [
            "You just beat your highest score!",
            "Impressive! You set a new record!",
            "Great job! You're improving more and more!",
            "Incredible! Your score is amazing!"
        ],
        hold: 'Hold',
        enter: 'Enter',
        restart: 'Restart',
        toRestart: 'to restart',
        pause: 'Pause',
    },
    ru: {
        error: `Произошла ошибка.`,
        highScore: 'Лучший счет',
        wpm: 'Свм',
        wordsPerMinute: 'Слов в минуту',
        seconds: 'Секунды',
        type: 'Введите',
        gettingWords: 'Получение слов. Инструкция должна быть прочитана в течение нескольких секунд. Если нет, попробуйте щелкнуть где-нибудь случайно или проверьте ваше интернет-соединение.',
        accuracy: 'Точность',
        playAgain: 'Играть снова',
        encouragement: [
            "Удачи!",
            "Дерзай!",
            "Ты сможешь!",
            "Не сдавайся!",
            "Давай, ты готов!",
            "Не переживай!",
            "Вперед!",
            "Держи курс!",
            "Все получится!",
            "Ты силен!",
            "Никогда не сдавайся!",
            "Только вперед!",
            "Не отступай!",
            "Никто не сможет тебе помешать!",
            "Ты можешь это сделать!",
            "Силы тебе!",
            "Не унывай!",
            "Духа тебе!",
            "Победа будет за тобой!",
            "У тебя все получится!",
        ],
        badScore: [
            "В следующий раз будет лучше.",
            "Не расстраивайся, практика делает мастера.",
            "Главное - участвовать.",
            "Успех не является окончательным, неудача не является смертельной: смелость продолжать двигаться вперед имеет значение.",
            "Каждая неудача - шанс для роста и улучшения.",
        ],
        goodScore: [
            "Впечатляюще!",
            "Отличная работа!",
            "Молодец!",
            "Поздравляем!",
            "Ты потрясающий!",
            "Отличный результат!"
        ],
        bestScore: [
            "Вы только что побили свой рекорд!",
            "Впечатляюще! Вы установили новый рекорд!",
            "Отличная работа! Вы улучшаете свои результаты с каждым разом!",
            "Невероятно! Ваш счет просто потрясающий!"
        ],
        hold: 'Удерживайте',
        enter: 'Enter',
        restart: 'Перезагрузка',
        toRestart: 'для перезапуска',
        pause: 'Пауза',
    },
    de: {
        error: `Ein Fehler ist aufgetreten.`,
        highScore: 'Höchstpunktzahl',
        wpm: 'WPM',
        wordsPerMinute: 'Wörter pro Minute',
        seconds: 'Sekunden',
        type: 'Tippen',
        gettingWords: 'Wörter werden geladen. Die Anweisungen sollten innerhalb weniger Sekunden angezeigt werden. Wenn nicht, versuchen Sie irgendwo zufällig zu klicken oder überprüfen Sie Ihre Internetverbindung.',
        accuracy: 'Genauigkeit',
        playAgain: 'Nochmal spielen',
        encouragement: [
            "Viel Glück!",
            "Du schaffst das!",
            "Glaub an dich!",
            "Bleib konzentriert!",
            "Atme tief durch und bleib ruhig!",
            "Auf geht's!",
            "Gib dein Bestes!",
            "Fordere dich selbst heraus!",
            "Du kannst es!",
            "Gib niemals auf!",
            "Du bist ein Gewinner!",
            "Strahle weiter!",
            "Bleib positiv!",
            "Bleib stark!",
            "Kopf hoch!",
            "Nicht aufgeben!",
            "Bleib motiviert!",
            "Gib alles!",
            "Mach weiter!",
            "Du hast, was es braucht!",
        ],
        badScore: [
            "Nächstes Mal wird es besser.",
            "Gib nicht auf, Übung macht den Meister.",
            "Dabei sein ist alles.",
            "Erfolg ist nicht endgültig, Misserfolg nicht fatal: Es ist der Mut weiterzumachen, der zählt.",
            "Jeder Misserfolg ist eine Chance, zu wachsen und sich zu verbessern.",
        ],
        goodScore: [
            "Beeindruckend!",
            "Ausgezeichnete Arbeit!",
            "Gut gemacht!",
            "Herzlichen Glückwunsch!",
            "Du bist großartig!",
            "Großartige Arbeit!"
        ],
        bestScore: [
            "Du hast gerade deinen Höchstpunktzahl geschlagen!",
            "Beeindruckend! Du hast einen neuen Rekord aufgestellt!",
            "Großartige Arbeit! Du wirst immer besser!",
            "Unglaublich! Dein Punktestand ist beeindruckend!"
        ],
        hold: 'Halten',
        enter: 'Enter',
        restart: 'Neustarten',
        toRestart: 'zum Neustarten',
        pause: 'Pause',
    }
}
